/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.config.noise;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class NoiseGeneratorConfigs {

    // @formatter:off
    public static final DefaultedRegistryReference<NoiseGeneratorConfig> AMPLIFIED = NoiseGeneratorConfigs.key(ResourceKey.minecraft("amplified"));

    public static final DefaultedRegistryReference<NoiseGeneratorConfig> CAVES = NoiseGeneratorConfigs.key(ResourceKey.minecraft("caves"));

    public static final DefaultedRegistryReference<NoiseGeneratorConfig> END = NoiseGeneratorConfigs.key(ResourceKey.minecraft("end"));

    public static final DefaultedRegistryReference<NoiseGeneratorConfig> FLOATING_ISLANDS = NoiseGeneratorConfigs.key(ResourceKey.minecraft("floating_islands"));

    public static final DefaultedRegistryReference<NoiseGeneratorConfig> LARGE_BIOMES = NoiseGeneratorConfigs.key(ResourceKey.minecraft("large_biomes"));

    public static final DefaultedRegistryReference<NoiseGeneratorConfig> NETHER = NoiseGeneratorConfigs.key(ResourceKey.minecraft("nether"));

    public static final DefaultedRegistryReference<NoiseGeneratorConfig> OVERWORLD = NoiseGeneratorConfigs.key(ResourceKey.minecraft("overworld"));

    // @formatter:on
    private NoiseGeneratorConfigs() {
    }

    public static Registry<NoiseGeneratorConfig> registry() {
        return Sponge.server().registry(RegistryTypes.NOISE_GENERATOR_CONFIG);
    }

    private static DefaultedRegistryReference<NoiseGeneratorConfig> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.NOISE_GENERATOR_CONFIG, location).asDefaultedReference(Sponge::server);
    }
}
