/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.feature;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class ConfiguredFeatures {

    // @formatter:off
    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ACACIA = ConfiguredFeatures.key(ResourceKey.minecraft("acacia"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> AMETHYST_GEODE = ConfiguredFeatures.key(ResourceKey.minecraft("amethyst_geode"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> AZALEA_TREE = ConfiguredFeatures.key(ResourceKey.minecraft("azalea_tree"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BAMBOO_NO_PODZOL = ConfiguredFeatures.key(ResourceKey.minecraft("bamboo_no_podzol"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BAMBOO_SOME_PODZOL = ConfiguredFeatures.key(ResourceKey.minecraft("bamboo_some_podzol"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BAMBOO_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("bamboo_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BASALT_BLOBS = ConfiguredFeatures.key(ResourceKey.minecraft("basalt_blobs"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BASALT_PILLAR = ConfiguredFeatures.key(ResourceKey.minecraft("basalt_pillar"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BIRCH = ConfiguredFeatures.key(ResourceKey.minecraft("birch"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BIRCH_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("birch_bees_0002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BIRCH_BEES_002 = ConfiguredFeatures.key(ResourceKey.minecraft("birch_bees_002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BIRCH_BEES_005 = ConfiguredFeatures.key(ResourceKey.minecraft("birch_bees_005"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BIRCH_TALL = ConfiguredFeatures.key(ResourceKey.minecraft("birch_tall"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BLACKSTONE_BLOBS = ConfiguredFeatures.key(ResourceKey.minecraft("blackstone_blobs"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BLUE_ICE = ConfiguredFeatures.key(ResourceKey.minecraft("blue_ice"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> BONUS_CHEST = ConfiguredFeatures.key(ResourceKey.minecraft("bonus_chest"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CAVE_VINE = ConfiguredFeatures.key(ResourceKey.minecraft("cave_vine"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CAVE_VINE_IN_MOSS = ConfiguredFeatures.key(ResourceKey.minecraft("cave_vine_in_moss"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CHORUS_PLANT = ConfiguredFeatures.key(ResourceKey.minecraft("chorus_plant"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CLAY_POOL_WITH_DRIPLEAVES = ConfiguredFeatures.key(ResourceKey.minecraft("clay_pool_with_dripleaves"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CLAY_WITH_DRIPLEAVES = ConfiguredFeatures.key(ResourceKey.minecraft("clay_with_dripleaves"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CRIMSON_FOREST_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("crimson_forest_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CRIMSON_FOREST_VEGETATION_BONEMEAL = ConfiguredFeatures.key(ResourceKey.minecraft("crimson_forest_vegetation_bonemeal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CRIMSON_FUNGUS = ConfiguredFeatures.key(ResourceKey.minecraft("crimson_fungus"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> CRIMSON_FUNGUS_PLANTED = ConfiguredFeatures.key(ResourceKey.minecraft("crimson_fungus_planted"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DARK_FOREST_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("dark_forest_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DARK_OAK = ConfiguredFeatures.key(ResourceKey.minecraft("dark_oak"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DELTA = ConfiguredFeatures.key(ResourceKey.minecraft("delta"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DESERT_WELL = ConfiguredFeatures.key(ResourceKey.minecraft("desert_well"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DISK_CLAY = ConfiguredFeatures.key(ResourceKey.minecraft("disk_clay"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DISK_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("disk_grass"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DISK_GRAVEL = ConfiguredFeatures.key(ResourceKey.minecraft("disk_gravel"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DISK_SAND = ConfiguredFeatures.key(ResourceKey.minecraft("disk_sand"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DRIPLEAF = ConfiguredFeatures.key(ResourceKey.minecraft("dripleaf"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> DRIPSTONE_CLUSTER = ConfiguredFeatures.key(ResourceKey.minecraft("dripstone_cluster"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> END_GATEWAY_DELAYED = ConfiguredFeatures.key(ResourceKey.minecraft("end_gateway_delayed"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> END_GATEWAY_RETURN = ConfiguredFeatures.key(ResourceKey.minecraft("end_gateway_return"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> END_ISLAND = ConfiguredFeatures.key(ResourceKey.minecraft("end_island"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> END_SPIKE = ConfiguredFeatures.key(ResourceKey.minecraft("end_spike"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FANCY_OAK = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FANCY_OAK_BEES = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FANCY_OAK_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees_0002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FANCY_OAK_BEES_002 = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees_002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FANCY_OAK_BEES_005 = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees_005"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FLOWER_DEFAULT = ConfiguredFeatures.key(ResourceKey.minecraft("flower_default"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FLOWER_FLOWER_FOREST = ConfiguredFeatures.key(ResourceKey.minecraft("flower_flower_forest"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FLOWER_MEADOW = ConfiguredFeatures.key(ResourceKey.minecraft("flower_meadow"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FLOWER_PLAIN = ConfiguredFeatures.key(ResourceKey.minecraft("flower_plain"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FLOWER_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("flower_swamp"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FOREST_FLOWERS = ConfiguredFeatures.key(ResourceKey.minecraft("forest_flowers"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FOREST_ROCK = ConfiguredFeatures.key(ResourceKey.minecraft("forest_rock"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FOSSIL_COAL = ConfiguredFeatures.key(ResourceKey.minecraft("fossil_coal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FOSSIL_DIAMONDS = ConfiguredFeatures.key(ResourceKey.minecraft("fossil_diamonds"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> FREEZE_TOP_LAYER = ConfiguredFeatures.key(ResourceKey.minecraft("freeze_top_layer"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> GLOW_LICHEN = ConfiguredFeatures.key(ResourceKey.minecraft("glow_lichen"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> GLOWSTONE_EXTRA = ConfiguredFeatures.key(ResourceKey.minecraft("glowstone_extra"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> HUGE_BROWN_MUSHROOM = ConfiguredFeatures.key(ResourceKey.minecraft("huge_brown_mushroom"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> HUGE_RED_MUSHROOM = ConfiguredFeatures.key(ResourceKey.minecraft("huge_red_mushroom"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ICE_PATCH = ConfiguredFeatures.key(ResourceKey.minecraft("ice_patch"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ICE_SPIKE = ConfiguredFeatures.key(ResourceKey.minecraft("ice_spike"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ICEBERG_BLUE = ConfiguredFeatures.key(ResourceKey.minecraft("iceberg_blue"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ICEBERG_PACKED = ConfiguredFeatures.key(ResourceKey.minecraft("iceberg_packed"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> JUNGLE_BUSH = ConfiguredFeatures.key(ResourceKey.minecraft("jungle_bush"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> JUNGLE_TREE = ConfiguredFeatures.key(ResourceKey.minecraft("jungle_tree"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> JUNGLE_TREE_NO_VINE = ConfiguredFeatures.key(ResourceKey.minecraft("jungle_tree_no_vine"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> KELP = ConfiguredFeatures.key(ResourceKey.minecraft("kelp"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> LAKE_LAVA = ConfiguredFeatures.key(ResourceKey.minecraft("lake_lava"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> LARGE_BASALT_COLUMNS = ConfiguredFeatures.key(ResourceKey.minecraft("large_basalt_columns"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> LARGE_DRIPSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("large_dripstone"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> LUSH_CAVES_CLAY = ConfiguredFeatures.key(ResourceKey.minecraft("lush_caves_clay"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MANGROVE = ConfiguredFeatures.key(ResourceKey.minecraft("mangrove"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MANGROVE_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("mangrove_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MEADOW_TREES = ConfiguredFeatures.key(ResourceKey.minecraft("meadow_trees"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MEGA_JUNGLE_TREE = ConfiguredFeatures.key(ResourceKey.minecraft("mega_jungle_tree"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MEGA_PINE = ConfiguredFeatures.key(ResourceKey.minecraft("mega_pine"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MEGA_SPRUCE = ConfiguredFeatures.key(ResourceKey.minecraft("mega_spruce"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MONSTER_ROOM = ConfiguredFeatures.key(ResourceKey.minecraft("monster_room"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MOSS_PATCH = ConfiguredFeatures.key(ResourceKey.minecraft("moss_patch"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MOSS_PATCH_BONEMEAL = ConfiguredFeatures.key(ResourceKey.minecraft("moss_patch_bonemeal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MOSS_PATCH_CEILING = ConfiguredFeatures.key(ResourceKey.minecraft("moss_patch_ceiling"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MOSS_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("moss_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> MUSHROOM_ISLAND_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("mushroom_island_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> NETHER_SPROUTS = ConfiguredFeatures.key(ResourceKey.minecraft("nether_sprouts"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> NETHER_SPROUTS_BONEMEAL = ConfiguredFeatures.key(ResourceKey.minecraft("nether_sprouts_bonemeal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> OAK = ConfiguredFeatures.key(ResourceKey.minecraft("oak"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> OAK_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("oak_bees_0002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> OAK_BEES_002 = ConfiguredFeatures.key(ResourceKey.minecraft("oak_bees_002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> OAK_BEES_005 = ConfiguredFeatures.key(ResourceKey.minecraft("oak_bees_005"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_ANCIENT_DEBRIS_LARGE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_ancient_debris_large"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_ANCIENT_DEBRIS_SMALL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_ancient_debris_small"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_ANDESITE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_andesite"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_BLACKSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_blackstone"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_CLAY = ConfiguredFeatures.key(ResourceKey.minecraft("ore_clay"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_COAL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_coal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_COAL_BURIED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_coal_buried"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_COPPER_LARGE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_copper_large"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_COPPER_SMALL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_copper_small"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_DIAMOND_BURIED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diamond_buried"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_DIAMOND_LARGE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diamond_large"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_DIAMOND_SMALL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diamond_small"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_DIORITE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diorite"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_DIRT = ConfiguredFeatures.key(ResourceKey.minecraft("ore_dirt"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_EMERALD = ConfiguredFeatures.key(ResourceKey.minecraft("ore_emerald"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_GOLD = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_GOLD_BURIED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold_buried"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_GRANITE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_granite"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_GRAVEL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gravel"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_GRAVEL_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gravel_nether"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_INFESTED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_infested"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_IRON = ConfiguredFeatures.key(ResourceKey.minecraft("ore_iron"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_IRON_SMALL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_iron_small"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_LAPIS = ConfiguredFeatures.key(ResourceKey.minecraft("ore_lapis"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_LAPIS_BURIED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_lapis_buried"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_MAGMA = ConfiguredFeatures.key(ResourceKey.minecraft("ore_magma"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_NETHER_GOLD = ConfiguredFeatures.key(ResourceKey.minecraft("ore_nether_gold"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_QUARTZ = ConfiguredFeatures.key(ResourceKey.minecraft("ore_quartz"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_REDSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_redstone"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_SOUL_SAND = ConfiguredFeatures.key(ResourceKey.minecraft("ore_soul_sand"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ORE_TUFF = ConfiguredFeatures.key(ResourceKey.minecraft("ore_tuff"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_BERRY_BUSH = ConfiguredFeatures.key(ResourceKey.minecraft("patch_berry_bush"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_BROWN_MUSHROOM = ConfiguredFeatures.key(ResourceKey.minecraft("patch_brown_mushroom"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_CACTUS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_cactus"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_CRIMSON_ROOTS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_crimson_roots"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_DEAD_BUSH = ConfiguredFeatures.key(ResourceKey.minecraft("patch_dead_bush"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_FIRE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_fire"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_GRASS_JUNGLE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_jungle"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_LARGE_FERN = ConfiguredFeatures.key(ResourceKey.minecraft("patch_large_fern"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_MELON = ConfiguredFeatures.key(ResourceKey.minecraft("patch_melon"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_PUMPKIN = ConfiguredFeatures.key(ResourceKey.minecraft("patch_pumpkin"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_RED_MUSHROOM = ConfiguredFeatures.key(ResourceKey.minecraft("patch_red_mushroom"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_SOUL_FIRE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_soul_fire"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_SUGAR_CANE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sugar_cane"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_SUNFLOWER = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sunflower"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_TAIGA_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_taiga_grass"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_TALL_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_tall_grass"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PATCH_WATERLILY = ConfiguredFeatures.key(ResourceKey.minecraft("patch_waterlily"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PILE_HAY = ConfiguredFeatures.key(ResourceKey.minecraft("pile_hay"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PILE_ICE = ConfiguredFeatures.key(ResourceKey.minecraft("pile_ice"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PILE_MELON = ConfiguredFeatures.key(ResourceKey.minecraft("pile_melon"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PILE_PUMPKIN = ConfiguredFeatures.key(ResourceKey.minecraft("pile_pumpkin"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PILE_SNOW = ConfiguredFeatures.key(ResourceKey.minecraft("pile_snow"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> PINE = ConfiguredFeatures.key(ResourceKey.minecraft("pine"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> POINTED_DRIPSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("pointed_dripstone"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> ROOTED_AZALEA_TREE = ConfiguredFeatures.key(ResourceKey.minecraft("rooted_azalea_tree"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SCULK_PATCH_ANCIENT_CITY = ConfiguredFeatures.key(ResourceKey.minecraft("sculk_patch_ancient_city"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SCULK_PATCH_DEEP_DARK = ConfiguredFeatures.key(ResourceKey.minecraft("sculk_patch_deep_dark"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SCULK_VEIN = ConfiguredFeatures.key(ResourceKey.minecraft("sculk_vein"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SEA_PICKLE = ConfiguredFeatures.key(ResourceKey.minecraft("sea_pickle"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SEAGRASS_MID = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_mid"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SEAGRASS_SHORT = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_short"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SEAGRASS_SIMPLE = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_simple"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SEAGRASS_SLIGHTLY_LESS_SHORT = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_slightly_less_short"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SEAGRASS_TALL = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_tall"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SINGLE_PIECE_OF_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("single_piece_of_grass"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SMALL_BASALT_COLUMNS = ConfiguredFeatures.key(ResourceKey.minecraft("small_basalt_columns"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPORE_BLOSSOM = ConfiguredFeatures.key(ResourceKey.minecraft("spore_blossom"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRING_LAVA_FROZEN = ConfiguredFeatures.key(ResourceKey.minecraft("spring_lava_frozen"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRING_LAVA_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("spring_lava_nether"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRING_LAVA_OVERWORLD = ConfiguredFeatures.key(ResourceKey.minecraft("spring_lava_overworld"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRING_NETHER_CLOSED = ConfiguredFeatures.key(ResourceKey.minecraft("spring_nether_closed"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRING_NETHER_OPEN = ConfiguredFeatures.key(ResourceKey.minecraft("spring_nether_open"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRING_WATER = ConfiguredFeatures.key(ResourceKey.minecraft("spring_water"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SPRUCE = ConfiguredFeatures.key(ResourceKey.minecraft("spruce"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SUPER_BIRCH_BEES = ConfiguredFeatures.key(ResourceKey.minecraft("super_birch_bees"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SUPER_BIRCH_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("super_birch_bees_0002"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> SWAMP_OAK = ConfiguredFeatures.key(ResourceKey.minecraft("swamp_oak"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TALL_MANGROVE = ConfiguredFeatures.key(ResourceKey.minecraft("tall_mangrove"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_BIRCH_AND_OAK = ConfiguredFeatures.key(ResourceKey.minecraft("trees_birch_and_oak"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_FLOWER_FOREST = ConfiguredFeatures.key(ResourceKey.minecraft("trees_flower_forest"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_GROVE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_grove"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_JUNGLE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_jungle"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_OLD_GROWTH_PINE_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_old_growth_pine_taiga"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_OLD_GROWTH_SPRUCE_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_old_growth_spruce_taiga"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_PLAINS = ConfiguredFeatures.key(ResourceKey.minecraft("trees_plains"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_SAVANNA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_savanna"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_SPARSE_JUNGLE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_sparse_jungle"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_taiga"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_WATER = ConfiguredFeatures.key(ResourceKey.minecraft("trees_water"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TREES_WINDSWEPT_HILLS = ConfiguredFeatures.key(ResourceKey.minecraft("trees_windswept_hills"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TWISTING_VINES = ConfiguredFeatures.key(ResourceKey.minecraft("twisting_vines"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> TWISTING_VINES_BONEMEAL = ConfiguredFeatures.key(ResourceKey.minecraft("twisting_vines_bonemeal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> UNDERWATER_MAGMA = ConfiguredFeatures.key(ResourceKey.minecraft("underwater_magma"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> VINES = ConfiguredFeatures.key(ResourceKey.minecraft("vines"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> VOID_START_PLATFORM = ConfiguredFeatures.key(ResourceKey.minecraft("void_start_platform"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> WARM_OCEAN_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("warm_ocean_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> WARPED_FOREST_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("warped_forest_vegetation"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> WARPED_FOREST_VEGETATION_BONEMEAL = ConfiguredFeatures.key(ResourceKey.minecraft("warped_forest_vegetation_bonemeal"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> WARPED_FUNGUS = ConfiguredFeatures.key(ResourceKey.minecraft("warped_fungus"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> WARPED_FUNGUS_PLANTED = ConfiguredFeatures.key(ResourceKey.minecraft("warped_fungus_planted"));

    public static final DefaultedRegistryReference<ConfiguredFeature<?>> WEEPING_VINES = ConfiguredFeatures.key(ResourceKey.minecraft("weeping_vines"));

    // @formatter:on
    private ConfiguredFeatures() {
    }

    public static Registry<ConfiguredFeature<?>> registry() {
        return Sponge.server().registry(RegistryTypes.CONFIGURED_FEATURE);
    }

    private static DefaultedRegistryReference<ConfiguredFeature<?>> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.CONFIGURED_FEATURE, location).asDefaultedReference(Sponge::server);
    }
}
