/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.feature;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryReference;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.server.ServerWorld;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.WORLD)
public final class ConfiguredFeatures {

    // @formatter:off
    public static final RegistryReference<ConfiguredFeature<?, ?>> ACACIA = ConfiguredFeatures.key(ResourceKey.minecraft("acacia"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ACACIA_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("acacia_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> AMETHYST_GEODE = ConfiguredFeatures.key(ResourceKey.minecraft("amethyst_geode"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BAMBOO = ConfiguredFeatures.key(ResourceKey.minecraft("bamboo"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BAMBOO_LIGHT = ConfiguredFeatures.key(ResourceKey.minecraft("bamboo_light"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BAMBOO_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("bamboo_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BASALT_BLOBS = ConfiguredFeatures.key(ResourceKey.minecraft("basalt_blobs"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BASALT_PILLAR = ConfiguredFeatures.key(ResourceKey.minecraft("basalt_pillar"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BIRCH_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("birch_bees_0002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BIRCH_BEES_002 = ConfiguredFeatures.key(ResourceKey.minecraft("birch_bees_002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BIRCH_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("birch_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BIRCH_TALL = ConfiguredFeatures.key(ResourceKey.minecraft("birch_tall"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BLACKSTONE_BLOBS = ConfiguredFeatures.key(ResourceKey.minecraft("blackstone_blobs"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BLUE_ICE = ConfiguredFeatures.key(ResourceKey.minecraft("blue_ice"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BROWN_MUSHROOM_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("brown_mushroom_nether"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BROWN_MUSHROOM_NORMAL = ConfiguredFeatures.key(ResourceKey.minecraft("brown_mushroom_normal"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BROWN_MUSHROOM_OLD_GROWTH = ConfiguredFeatures.key(ResourceKey.minecraft("brown_mushroom_old_growth"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BROWN_MUSHROOM_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("brown_mushroom_swamp"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> BROWN_MUSHROOM_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("brown_mushroom_taiga"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> CAVE_VINES = ConfiguredFeatures.key(ResourceKey.minecraft("cave_vines"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> CHORUS_PLANT = ConfiguredFeatures.key(ResourceKey.minecraft("chorus_plant"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> CLASSIC_VINES_CAVE_FEATURE = ConfiguredFeatures.key(ResourceKey.minecraft("classic_vines_cave_feature"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> CRIMSON_FOREST_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("crimson_forest_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> CRIMSON_FUNGI = ConfiguredFeatures.key(ResourceKey.minecraft("crimson_fungi"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DARK_FOREST_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("dark_forest_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DARK_OAK_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("dark_oak_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DELTA = ConfiguredFeatures.key(ResourceKey.minecraft("delta"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DESERT_WELL = ConfiguredFeatures.key(ResourceKey.minecraft("desert_well"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DISK_CLAY = ConfiguredFeatures.key(ResourceKey.minecraft("disk_clay"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DISK_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("disk_grass"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DISK_GRAVEL = ConfiguredFeatures.key(ResourceKey.minecraft("disk_gravel"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DISK_SAND = ConfiguredFeatures.key(ResourceKey.minecraft("disk_sand"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> DRIPSTONE_CLUSTER = ConfiguredFeatures.key(ResourceKey.minecraft("dripstone_cluster"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> END_GATEWAY_RETURN = ConfiguredFeatures.key(ResourceKey.minecraft("end_gateway_return"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> END_ISLAND_DECORATED = ConfiguredFeatures.key(ResourceKey.minecraft("end_island_decorated"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> END_SPIKE = ConfiguredFeatures.key(ResourceKey.minecraft("end_spike"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FANCY_OAK_BEES = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FANCY_OAK_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees_0002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FANCY_OAK_BEES_002 = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_bees_002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FANCY_OAK_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("fancy_oak_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_DEFAULT = ConfiguredFeatures.key(ResourceKey.minecraft("flower_default"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_FLOWER_FOREST = ConfiguredFeatures.key(ResourceKey.minecraft("flower_flower_forest"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_FOREST_FLOWERS = ConfiguredFeatures.key(ResourceKey.minecraft("flower_forest_flowers"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_MEADOW = ConfiguredFeatures.key(ResourceKey.minecraft("flower_meadow"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_PLAIN = ConfiguredFeatures.key(ResourceKey.minecraft("flower_plain"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_PLAINS = ConfiguredFeatures.key(ResourceKey.minecraft("flower_plains"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("flower_swamp"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FLOWER_WARM = ConfiguredFeatures.key(ResourceKey.minecraft("flower_warm"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FOREST_FLOWERS = ConfiguredFeatures.key(ResourceKey.minecraft("forest_flowers"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FOREST_ROCK = ConfiguredFeatures.key(ResourceKey.minecraft("forest_rock"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FOSSIL_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("fossil_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FOSSIL_UPPER = ConfiguredFeatures.key(ResourceKey.minecraft("fossil_upper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> FREEZE_TOP_LAYER = ConfiguredFeatures.key(ResourceKey.minecraft("freeze_top_layer"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> GLOW_LICHEN = ConfiguredFeatures.key(ResourceKey.minecraft("glow_lichen"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> GLOWSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("glowstone"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> GLOWSTONE_EXTRA = ConfiguredFeatures.key(ResourceKey.minecraft("glowstone_extra"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> GRASS_BONEMEAL = ConfiguredFeatures.key(ResourceKey.minecraft("grass_bonemeal"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ICE_PATCH = ConfiguredFeatures.key(ResourceKey.minecraft("ice_patch"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ICE_SPIKE = ConfiguredFeatures.key(ResourceKey.minecraft("ice_spike"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ICEBERG_BLUE = ConfiguredFeatures.key(ResourceKey.minecraft("iceberg_blue"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ICEBERG_PACKED = ConfiguredFeatures.key(ResourceKey.minecraft("iceberg_packed"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> JUNGLE_BUSH = ConfiguredFeatures.key(ResourceKey.minecraft("jungle_bush"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> JUNGLE_TREE = ConfiguredFeatures.key(ResourceKey.minecraft("jungle_tree"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> KELP_COLD = ConfiguredFeatures.key(ResourceKey.minecraft("kelp_cold"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> KELP_WARM = ConfiguredFeatures.key(ResourceKey.minecraft("kelp_warm"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LAKE_LAVA_SURFACE = ConfiguredFeatures.key(ResourceKey.minecraft("lake_lava_surface"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LAKE_LAVA_UNDERGROUND = ConfiguredFeatures.key(ResourceKey.minecraft("lake_lava_underground"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LARGE_BASALT_COLUMNS = ConfiguredFeatures.key(ResourceKey.minecraft("large_basalt_columns"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LARGE_DRIPSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("large_dripstone"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LUSH_CAVES_CEILING_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("lush_caves_ceiling_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LUSH_CAVES_CLAY = ConfiguredFeatures.key(ResourceKey.minecraft("lush_caves_clay"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> LUSH_CAVES_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("lush_caves_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MANGROVE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("mangrove_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MEGA_JUNGLE_TREE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("mega_jungle_tree_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MEGA_PINE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("mega_pine_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MEGA_SPRUCE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("mega_spruce_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MONSTER_ROOM = ConfiguredFeatures.key(ResourceKey.minecraft("monster_room"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MONSTER_ROOM_DEEP = ConfiguredFeatures.key(ResourceKey.minecraft("monster_room_deep"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> MUSHROOM_ISLAND_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("mushroom_island_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> NETHER_SPROUTS = ConfiguredFeatures.key(ResourceKey.minecraft("nether_sprouts"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> OAK = ConfiguredFeatures.key(ResourceKey.minecraft("oak"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> OAK_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("oak_bees_0002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> OAK_BEES_002 = ConfiguredFeatures.key(ResourceKey.minecraft("oak_bees_002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> OAK_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("oak_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_ANCIENT_DEBRIS_LARGE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_ancient_debris_large"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_ANDESITE_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_andesite_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_ANDESITE_UPPER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_andesite_upper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_BLACKSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_blackstone"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_CLAY = ConfiguredFeatures.key(ResourceKey.minecraft("ore_clay"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_COAL_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_coal_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_COAL_UPPER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_coal_upper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_COPPER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_copper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_COPPER_LARGE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_copper_large"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DEBRIS_SMALL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_debris_small"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DIAMOND = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diamond"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DIAMOND_BURIED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diamond_buried"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DIAMOND_LARGE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diamond_large"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DIORITE_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diorite_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DIORITE_UPPER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_diorite_upper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_DIRT = ConfiguredFeatures.key(ResourceKey.minecraft("ore_dirt"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_EMERALD = ConfiguredFeatures.key(ResourceKey.minecraft("ore_emerald"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GOLD = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GOLD_DELTAS = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold_deltas"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GOLD_EXTRA = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold_extra"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GOLD_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GOLD_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gold_nether"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GRANITE_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_granite_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GRANITE_UPPER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_granite_upper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GRAVEL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gravel"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_GRAVEL_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_gravel_nether"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_INFESTED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_infested"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_IRON_MIDDLE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_iron_middle"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_IRON_SMALL = ConfiguredFeatures.key(ResourceKey.minecraft("ore_iron_small"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_IRON_UPPER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_iron_upper"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_LAPIS = ConfiguredFeatures.key(ResourceKey.minecraft("ore_lapis"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_LAPIS_BURIED = ConfiguredFeatures.key(ResourceKey.minecraft("ore_lapis_buried"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_MAGMA = ConfiguredFeatures.key(ResourceKey.minecraft("ore_magma"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_QUARTZ_DELTAS = ConfiguredFeatures.key(ResourceKey.minecraft("ore_quartz_deltas"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_QUARTZ_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_quartz_nether"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_REDSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("ore_redstone"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_REDSTONE_LOWER = ConfiguredFeatures.key(ResourceKey.minecraft("ore_redstone_lower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_SOUL_SAND = ConfiguredFeatures.key(ResourceKey.minecraft("ore_soul_sand"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ORE_TUFF = ConfiguredFeatures.key(ResourceKey.minecraft("ore_tuff"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_BERRY_BUSH = ConfiguredFeatures.key(ResourceKey.minecraft("patch_berry_bush"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_BERRY_COMMON = ConfiguredFeatures.key(ResourceKey.minecraft("patch_berry_common"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_BERRY_RARE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_berry_rare"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_CACTUS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_cactus"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_CACTUS_DECORATED = ConfiguredFeatures.key(ResourceKey.minecraft("patch_cactus_decorated"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_CACTUS_DESERT = ConfiguredFeatures.key(ResourceKey.minecraft("patch_cactus_desert"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_CRIMSON_ROOTS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_crimson_roots"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_DEAD_BUSH = ConfiguredFeatures.key(ResourceKey.minecraft("patch_dead_bush"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_DEAD_BUSH_2 = ConfiguredFeatures.key(ResourceKey.minecraft("patch_dead_bush_2"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_DEAD_BUSH_BADLANDS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_dead_bush_badlands"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_FIRE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_fire"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_BADLANDS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_badlands"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_FOREST = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_forest"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_JUNGLE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_jungle"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_NORMAL = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_normal"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_PLAIN = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_plain"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_SAVANNA = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_savanna"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_taiga"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_GRASS_TAIGA_2 = ConfiguredFeatures.key(ResourceKey.minecraft("patch_grass_taiga_2"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_LARGE_FERN = ConfiguredFeatures.key(ResourceKey.minecraft("patch_large_fern"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_MELON = ConfiguredFeatures.key(ResourceKey.minecraft("patch_melon"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_MELON_SPARSE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_melon_sparse"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_PUMPKIN = ConfiguredFeatures.key(ResourceKey.minecraft("patch_pumpkin"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_SOUL_FIRE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_soul_fire"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_SUGAR_CANE = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sugar_cane"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_SUGAR_CANE_BADLANDS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sugar_cane_badlands"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_SUGAR_CANE_DESERT = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sugar_cane_desert"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_SUGAR_CANE_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sugar_cane_swamp"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_SUNFLOWER = ConfiguredFeatures.key(ResourceKey.minecraft("patch_sunflower"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_TAIGA_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_taiga_grass"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_TALL_GRASS = ConfiguredFeatures.key(ResourceKey.minecraft("patch_tall_grass"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_TALL_GRASS_2 = ConfiguredFeatures.key(ResourceKey.minecraft("patch_tall_grass_2"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PATCH_WATERLILY = ConfiguredFeatures.key(ResourceKey.minecraft("patch_waterlily"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PILE_HAY = ConfiguredFeatures.key(ResourceKey.minecraft("pile_hay"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PILE_ICE = ConfiguredFeatures.key(ResourceKey.minecraft("pile_ice"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PILE_MELON = ConfiguredFeatures.key(ResourceKey.minecraft("pile_melon"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PILE_PUMPKIN = ConfiguredFeatures.key(ResourceKey.minecraft("pile_pumpkin"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PILE_SNOW = ConfiguredFeatures.key(ResourceKey.minecraft("pile_snow"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PINE = ConfiguredFeatures.key(ResourceKey.minecraft("pine"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PINE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("pine_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> PINE_ON_SNOW = ConfiguredFeatures.key(ResourceKey.minecraft("pine_on_snow"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> POINTED_DRIPSTONE = ConfiguredFeatures.key(ResourceKey.minecraft("pointed_dripstone"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> RED_MUSHROOM_NETHER = ConfiguredFeatures.key(ResourceKey.minecraft("red_mushroom_nether"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> RED_MUSHROOM_NORMAL = ConfiguredFeatures.key(ResourceKey.minecraft("red_mushroom_normal"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> RED_MUSHROOM_OLD_GROWTH = ConfiguredFeatures.key(ResourceKey.minecraft("red_mushroom_old_growth"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> RED_MUSHROOM_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("red_mushroom_swamp"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> RED_MUSHROOM_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("red_mushroom_taiga"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> ROOTED_AZALEA_TREE = ConfiguredFeatures.key(ResourceKey.minecraft("rooted_azalea_tree"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SCULK_PATCH_ANCIENT_CITY = ConfiguredFeatures.key(ResourceKey.minecraft("sculk_patch_ancient_city"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SCULK_PATCH_DEEP_DARK = ConfiguredFeatures.key(ResourceKey.minecraft("sculk_patch_deep_dark"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SCULK_VEIN = ConfiguredFeatures.key(ResourceKey.minecraft("sculk_vein"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEA_PICKLE = ConfiguredFeatures.key(ResourceKey.minecraft("sea_pickle"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_COLD = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_cold"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_DEEP = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_deep"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_DEEP_COLD = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_deep_cold"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_DEEP_WARM = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_deep_warm"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_NORMAL = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_normal"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_RIVER = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_river"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_SIMPLE = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_simple"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_swamp"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SEAGRASS_WARM = ConfiguredFeatures.key(ResourceKey.minecraft("seagrass_warm"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SMALL_BASALT_COLUMNS = ConfiguredFeatures.key(ResourceKey.minecraft("small_basalt_columns"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPORE_BLOSSOM = ConfiguredFeatures.key(ResourceKey.minecraft("spore_blossom"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_CLOSED = ConfiguredFeatures.key(ResourceKey.minecraft("spring_closed"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_CLOSED_DOUBLE = ConfiguredFeatures.key(ResourceKey.minecraft("spring_closed_double"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_DELTA = ConfiguredFeatures.key(ResourceKey.minecraft("spring_delta"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_LAVA = ConfiguredFeatures.key(ResourceKey.minecraft("spring_lava"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_LAVA_FROZEN = ConfiguredFeatures.key(ResourceKey.minecraft("spring_lava_frozen"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_OPEN = ConfiguredFeatures.key(ResourceKey.minecraft("spring_open"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRING_WATER = ConfiguredFeatures.key(ResourceKey.minecraft("spring_water"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRUCE = ConfiguredFeatures.key(ResourceKey.minecraft("spruce"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRUCE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("spruce_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SPRUCE_ON_SNOW = ConfiguredFeatures.key(ResourceKey.minecraft("spruce_on_snow"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SUPER_BIRCH_BEES = ConfiguredFeatures.key(ResourceKey.minecraft("super_birch_bees"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> SUPER_BIRCH_BEES_0002 = ConfiguredFeatures.key(ResourceKey.minecraft("super_birch_bees_0002"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TALL_MANGROVE_CHECKED = ConfiguredFeatures.key(ResourceKey.minecraft("tall_mangrove_checked"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_BADLANDS = ConfiguredFeatures.key(ResourceKey.minecraft("trees_badlands"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_BIRCH = ConfiguredFeatures.key(ResourceKey.minecraft("trees_birch"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_BIRCH_AND_OAK = ConfiguredFeatures.key(ResourceKey.minecraft("trees_birch_and_oak"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_FLOWER_FOREST = ConfiguredFeatures.key(ResourceKey.minecraft("trees_flower_forest"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_GROVE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_grove"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_JUNGLE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_jungle"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_MANGROVE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_mangrove"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_MEADOW = ConfiguredFeatures.key(ResourceKey.minecraft("trees_meadow"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_OLD_GROWTH_PINE_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_old_growth_pine_taiga"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_OLD_GROWTH_SPRUCE_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_old_growth_spruce_taiga"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_PLAINS = ConfiguredFeatures.key(ResourceKey.minecraft("trees_plains"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_SAVANNA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_savanna"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_SNOWY = ConfiguredFeatures.key(ResourceKey.minecraft("trees_snowy"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_SPARSE_JUNGLE = ConfiguredFeatures.key(ResourceKey.minecraft("trees_sparse_jungle"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_SWAMP = ConfiguredFeatures.key(ResourceKey.minecraft("trees_swamp"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_TAIGA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_taiga"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_WATER = ConfiguredFeatures.key(ResourceKey.minecraft("trees_water"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_WINDSWEPT_FOREST = ConfiguredFeatures.key(ResourceKey.minecraft("trees_windswept_forest"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_WINDSWEPT_HILLS = ConfiguredFeatures.key(ResourceKey.minecraft("trees_windswept_hills"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TREES_WINDSWEPT_SAVANNA = ConfiguredFeatures.key(ResourceKey.minecraft("trees_windswept_savanna"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> TWISTING_VINES = ConfiguredFeatures.key(ResourceKey.minecraft("twisting_vines"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> UNDERWATER_MAGMA = ConfiguredFeatures.key(ResourceKey.minecraft("underwater_magma"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> VINES = ConfiguredFeatures.key(ResourceKey.minecraft("vines"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> VOID_START_PLATFORM = ConfiguredFeatures.key(ResourceKey.minecraft("void_start_platform"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> WARM_OCEAN_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("warm_ocean_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> WARPED_FOREST_VEGETATION = ConfiguredFeatures.key(ResourceKey.minecraft("warped_forest_vegetation"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> WARPED_FUNGI = ConfiguredFeatures.key(ResourceKey.minecraft("warped_fungi"));

    public static final RegistryReference<ConfiguredFeature<?, ?>> WEEPING_VINES = ConfiguredFeatures.key(ResourceKey.minecraft("weeping_vines"));

    // @formatter:on
    private ConfiguredFeatures() {
    }

    public static Registry<ConfiguredFeature<?, ?>> registry(final ServerWorld world) {
        return world.registry(RegistryTypes.CONFIGURED_FEATURE);
    }

    private static RegistryReference<ConfiguredFeature<?, ?>> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.CONFIGURED_FEATURE, location).asReference();
    }
}
