/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.feature;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class Features {

    //@formatter:off
    public static final DefaultedRegistryReference<Feature> ACACIA = Features.key(ResourceKey.minecraft("acacia"));

    public static final DefaultedRegistryReference<Feature> AMETHYST_GEODE = Features.key(ResourceKey.minecraft("amethyst_geode"));

    public static final DefaultedRegistryReference<Feature> AZALEA_TREE = Features.key(ResourceKey.minecraft("azalea_tree"));

    public static final DefaultedRegistryReference<Feature> BAMBOO_NO_PODZOL = Features.key(ResourceKey.minecraft("bamboo_no_podzol"));

    public static final DefaultedRegistryReference<Feature> BAMBOO_SOME_PODZOL = Features.key(ResourceKey.minecraft("bamboo_some_podzol"));

    public static final DefaultedRegistryReference<Feature> BAMBOO_VEGETATION = Features.key(ResourceKey.minecraft("bamboo_vegetation"));

    public static final DefaultedRegistryReference<Feature> BASALT_BLOBS = Features.key(ResourceKey.minecraft("basalt_blobs"));

    public static final DefaultedRegistryReference<Feature> BASALT_PILLAR = Features.key(ResourceKey.minecraft("basalt_pillar"));

    public static final DefaultedRegistryReference<Feature> BIRCH = Features.key(ResourceKey.minecraft("birch"));

    public static final DefaultedRegistryReference<Feature> BIRCH_BEES_0002 = Features.key(ResourceKey.minecraft("birch_bees_0002"));

    public static final DefaultedRegistryReference<Feature> BIRCH_BEES_002 = Features.key(ResourceKey.minecraft("birch_bees_002"));

    public static final DefaultedRegistryReference<Feature> BIRCH_BEES_005 = Features.key(ResourceKey.minecraft("birch_bees_005"));

    public static final DefaultedRegistryReference<Feature> BIRCH_TALL = Features.key(ResourceKey.minecraft("birch_tall"));

    public static final DefaultedRegistryReference<Feature> BLACKSTONE_BLOBS = Features.key(ResourceKey.minecraft("blackstone_blobs"));

    public static final DefaultedRegistryReference<Feature> BLUE_ICE = Features.key(ResourceKey.minecraft("blue_ice"));

    public static final DefaultedRegistryReference<Feature> BONUS_CHEST = Features.key(ResourceKey.minecraft("bonus_chest"));

    public static final DefaultedRegistryReference<Feature> CAVE_VINE = Features.key(ResourceKey.minecraft("cave_vine"));

    public static final DefaultedRegistryReference<Feature> CAVE_VINE_IN_MOSS = Features.key(ResourceKey.minecraft("cave_vine_in_moss"));

    public static final DefaultedRegistryReference<Feature> CHERRY = Features.key(ResourceKey.minecraft("cherry"));

    public static final DefaultedRegistryReference<Feature> CHERRY_BEES_005 = Features.key(ResourceKey.minecraft("cherry_bees_005"));

    public static final DefaultedRegistryReference<Feature> CHORUS_PLANT = Features.key(ResourceKey.minecraft("chorus_plant"));

    public static final DefaultedRegistryReference<Feature> CLAY_POOL_WITH_DRIPLEAVES = Features.key(ResourceKey.minecraft("clay_pool_with_dripleaves"));

    public static final DefaultedRegistryReference<Feature> CLAY_WITH_DRIPLEAVES = Features.key(ResourceKey.minecraft("clay_with_dripleaves"));

    public static final DefaultedRegistryReference<Feature> CRIMSON_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("crimson_forest_vegetation"));

    public static final DefaultedRegistryReference<Feature> CRIMSON_FOREST_VEGETATION_BONEMEAL = Features.key(ResourceKey.minecraft("crimson_forest_vegetation_bonemeal"));

    public static final DefaultedRegistryReference<Feature> CRIMSON_FUNGUS = Features.key(ResourceKey.minecraft("crimson_fungus"));

    public static final DefaultedRegistryReference<Feature> CRIMSON_FUNGUS_PLANTED = Features.key(ResourceKey.minecraft("crimson_fungus_planted"));

    public static final DefaultedRegistryReference<Feature> DARK_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("dark_forest_vegetation"));

    public static final DefaultedRegistryReference<Feature> DARK_OAK = Features.key(ResourceKey.minecraft("dark_oak"));

    public static final DefaultedRegistryReference<Feature> DELTA = Features.key(ResourceKey.minecraft("delta"));

    public static final DefaultedRegistryReference<Feature> DESERT_WELL = Features.key(ResourceKey.minecraft("desert_well"));

    public static final DefaultedRegistryReference<Feature> DISK_CLAY = Features.key(ResourceKey.minecraft("disk_clay"));

    public static final DefaultedRegistryReference<Feature> DISK_GRASS = Features.key(ResourceKey.minecraft("disk_grass"));

    public static final DefaultedRegistryReference<Feature> DISK_GRAVEL = Features.key(ResourceKey.minecraft("disk_gravel"));

    public static final DefaultedRegistryReference<Feature> DISK_SAND = Features.key(ResourceKey.minecraft("disk_sand"));

    public static final DefaultedRegistryReference<Feature> DRIPLEAF = Features.key(ResourceKey.minecraft("dripleaf"));

    public static final DefaultedRegistryReference<Feature> DRIPSTONE_CLUSTER = Features.key(ResourceKey.minecraft("dripstone_cluster"));

    public static final DefaultedRegistryReference<Feature> END_GATEWAY_DELAYED = Features.key(ResourceKey.minecraft("end_gateway_delayed"));

    public static final DefaultedRegistryReference<Feature> END_GATEWAY_RETURN = Features.key(ResourceKey.minecraft("end_gateway_return"));

    public static final DefaultedRegistryReference<Feature> END_ISLAND = Features.key(ResourceKey.minecraft("end_island"));

    public static final DefaultedRegistryReference<Feature> END_SPIKE = Features.key(ResourceKey.minecraft("end_spike"));

    public static final DefaultedRegistryReference<Feature> FANCY_OAK = Features.key(ResourceKey.minecraft("fancy_oak"));

    public static final DefaultedRegistryReference<Feature> FANCY_OAK_BEES = Features.key(ResourceKey.minecraft("fancy_oak_bees"));

    public static final DefaultedRegistryReference<Feature> FANCY_OAK_BEES_0002 = Features.key(ResourceKey.minecraft("fancy_oak_bees_0002"));

    public static final DefaultedRegistryReference<Feature> FANCY_OAK_BEES_002 = Features.key(ResourceKey.minecraft("fancy_oak_bees_002"));

    public static final DefaultedRegistryReference<Feature> FANCY_OAK_BEES_005 = Features.key(ResourceKey.minecraft("fancy_oak_bees_005"));

    public static final DefaultedRegistryReference<Feature> FLOWER_CHERRY = Features.key(ResourceKey.minecraft("flower_cherry"));

    public static final DefaultedRegistryReference<Feature> FLOWER_DEFAULT = Features.key(ResourceKey.minecraft("flower_default"));

    public static final DefaultedRegistryReference<Feature> FLOWER_FLOWER_FOREST = Features.key(ResourceKey.minecraft("flower_flower_forest"));

    public static final DefaultedRegistryReference<Feature> FLOWER_MEADOW = Features.key(ResourceKey.minecraft("flower_meadow"));

    public static final DefaultedRegistryReference<Feature> FLOWER_PLAIN = Features.key(ResourceKey.minecraft("flower_plain"));

    public static final DefaultedRegistryReference<Feature> FLOWER_SWAMP = Features.key(ResourceKey.minecraft("flower_swamp"));

    public static final DefaultedRegistryReference<Feature> FOREST_FLOWERS = Features.key(ResourceKey.minecraft("forest_flowers"));

    public static final DefaultedRegistryReference<Feature> FOREST_ROCK = Features.key(ResourceKey.minecraft("forest_rock"));

    public static final DefaultedRegistryReference<Feature> FOSSIL_COAL = Features.key(ResourceKey.minecraft("fossil_coal"));

    public static final DefaultedRegistryReference<Feature> FOSSIL_DIAMONDS = Features.key(ResourceKey.minecraft("fossil_diamonds"));

    public static final DefaultedRegistryReference<Feature> FREEZE_TOP_LAYER = Features.key(ResourceKey.minecraft("freeze_top_layer"));

    public static final DefaultedRegistryReference<Feature> GLOW_LICHEN = Features.key(ResourceKey.minecraft("glow_lichen"));

    public static final DefaultedRegistryReference<Feature> GLOWSTONE_EXTRA = Features.key(ResourceKey.minecraft("glowstone_extra"));

    public static final DefaultedRegistryReference<Feature> HUGE_BROWN_MUSHROOM = Features.key(ResourceKey.minecraft("huge_brown_mushroom"));

    public static final DefaultedRegistryReference<Feature> HUGE_RED_MUSHROOM = Features.key(ResourceKey.minecraft("huge_red_mushroom"));

    public static final DefaultedRegistryReference<Feature> ICE_PATCH = Features.key(ResourceKey.minecraft("ice_patch"));

    public static final DefaultedRegistryReference<Feature> ICE_SPIKE = Features.key(ResourceKey.minecraft("ice_spike"));

    public static final DefaultedRegistryReference<Feature> ICEBERG_BLUE = Features.key(ResourceKey.minecraft("iceberg_blue"));

    public static final DefaultedRegistryReference<Feature> ICEBERG_PACKED = Features.key(ResourceKey.minecraft("iceberg_packed"));

    public static final DefaultedRegistryReference<Feature> JUNGLE_BUSH = Features.key(ResourceKey.minecraft("jungle_bush"));

    public static final DefaultedRegistryReference<Feature> JUNGLE_TREE = Features.key(ResourceKey.minecraft("jungle_tree"));

    public static final DefaultedRegistryReference<Feature> JUNGLE_TREE_NO_VINE = Features.key(ResourceKey.minecraft("jungle_tree_no_vine"));

    public static final DefaultedRegistryReference<Feature> KELP = Features.key(ResourceKey.minecraft("kelp"));

    public static final DefaultedRegistryReference<Feature> LAKE_LAVA = Features.key(ResourceKey.minecraft("lake_lava"));

    public static final DefaultedRegistryReference<Feature> LARGE_BASALT_COLUMNS = Features.key(ResourceKey.minecraft("large_basalt_columns"));

    public static final DefaultedRegistryReference<Feature> LARGE_DRIPSTONE = Features.key(ResourceKey.minecraft("large_dripstone"));

    public static final DefaultedRegistryReference<Feature> LUSH_CAVES_CLAY = Features.key(ResourceKey.minecraft("lush_caves_clay"));

    public static final DefaultedRegistryReference<Feature> MANGROVE = Features.key(ResourceKey.minecraft("mangrove"));

    public static final DefaultedRegistryReference<Feature> MANGROVE_VEGETATION = Features.key(ResourceKey.minecraft("mangrove_vegetation"));

    public static final DefaultedRegistryReference<Feature> MEADOW_TREES = Features.key(ResourceKey.minecraft("meadow_trees"));

    public static final DefaultedRegistryReference<Feature> MEGA_JUNGLE_TREE = Features.key(ResourceKey.minecraft("mega_jungle_tree"));

    public static final DefaultedRegistryReference<Feature> MEGA_PINE = Features.key(ResourceKey.minecraft("mega_pine"));

    public static final DefaultedRegistryReference<Feature> MEGA_SPRUCE = Features.key(ResourceKey.minecraft("mega_spruce"));

    public static final DefaultedRegistryReference<Feature> MONSTER_ROOM = Features.key(ResourceKey.minecraft("monster_room"));

    public static final DefaultedRegistryReference<Feature> MOSS_PATCH = Features.key(ResourceKey.minecraft("moss_patch"));

    public static final DefaultedRegistryReference<Feature> MOSS_PATCH_BONEMEAL = Features.key(ResourceKey.minecraft("moss_patch_bonemeal"));

    public static final DefaultedRegistryReference<Feature> MOSS_PATCH_CEILING = Features.key(ResourceKey.minecraft("moss_patch_ceiling"));

    public static final DefaultedRegistryReference<Feature> MOSS_VEGETATION = Features.key(ResourceKey.minecraft("moss_vegetation"));

    public static final DefaultedRegistryReference<Feature> MUSHROOM_ISLAND_VEGETATION = Features.key(ResourceKey.minecraft("mushroom_island_vegetation"));

    public static final DefaultedRegistryReference<Feature> NETHER_SPROUTS = Features.key(ResourceKey.minecraft("nether_sprouts"));

    public static final DefaultedRegistryReference<Feature> NETHER_SPROUTS_BONEMEAL = Features.key(ResourceKey.minecraft("nether_sprouts_bonemeal"));

    public static final DefaultedRegistryReference<Feature> OAK = Features.key(ResourceKey.minecraft("oak"));

    public static final DefaultedRegistryReference<Feature> OAK_BEES_0002 = Features.key(ResourceKey.minecraft("oak_bees_0002"));

    public static final DefaultedRegistryReference<Feature> OAK_BEES_002 = Features.key(ResourceKey.minecraft("oak_bees_002"));

    public static final DefaultedRegistryReference<Feature> OAK_BEES_005 = Features.key(ResourceKey.minecraft("oak_bees_005"));

    public static final DefaultedRegistryReference<Feature> ORE_ANCIENT_DEBRIS_LARGE = Features.key(ResourceKey.minecraft("ore_ancient_debris_large"));

    public static final DefaultedRegistryReference<Feature> ORE_ANCIENT_DEBRIS_SMALL = Features.key(ResourceKey.minecraft("ore_ancient_debris_small"));

    public static final DefaultedRegistryReference<Feature> ORE_ANDESITE = Features.key(ResourceKey.minecraft("ore_andesite"));

    public static final DefaultedRegistryReference<Feature> ORE_BLACKSTONE = Features.key(ResourceKey.minecraft("ore_blackstone"));

    public static final DefaultedRegistryReference<Feature> ORE_CLAY = Features.key(ResourceKey.minecraft("ore_clay"));

    public static final DefaultedRegistryReference<Feature> ORE_COAL = Features.key(ResourceKey.minecraft("ore_coal"));

    public static final DefaultedRegistryReference<Feature> ORE_COAL_BURIED = Features.key(ResourceKey.minecraft("ore_coal_buried"));

    public static final DefaultedRegistryReference<Feature> ORE_COPPER_LARGE = Features.key(ResourceKey.minecraft("ore_copper_large"));

    public static final DefaultedRegistryReference<Feature> ORE_COPPER_SMALL = Features.key(ResourceKey.minecraft("ore_copper_small"));

    public static final DefaultedRegistryReference<Feature> ORE_DIAMOND_BURIED = Features.key(ResourceKey.minecraft("ore_diamond_buried"));

    public static final DefaultedRegistryReference<Feature> ORE_DIAMOND_LARGE = Features.key(ResourceKey.minecraft("ore_diamond_large"));

    public static final DefaultedRegistryReference<Feature> ORE_DIAMOND_MEDIUM = Features.key(ResourceKey.minecraft("ore_diamond_medium"));

    public static final DefaultedRegistryReference<Feature> ORE_DIAMOND_SMALL = Features.key(ResourceKey.minecraft("ore_diamond_small"));

    public static final DefaultedRegistryReference<Feature> ORE_DIORITE = Features.key(ResourceKey.minecraft("ore_diorite"));

    public static final DefaultedRegistryReference<Feature> ORE_DIRT = Features.key(ResourceKey.minecraft("ore_dirt"));

    public static final DefaultedRegistryReference<Feature> ORE_EMERALD = Features.key(ResourceKey.minecraft("ore_emerald"));

    public static final DefaultedRegistryReference<Feature> ORE_GOLD = Features.key(ResourceKey.minecraft("ore_gold"));

    public static final DefaultedRegistryReference<Feature> ORE_GOLD_BURIED = Features.key(ResourceKey.minecraft("ore_gold_buried"));

    public static final DefaultedRegistryReference<Feature> ORE_GRANITE = Features.key(ResourceKey.minecraft("ore_granite"));

    public static final DefaultedRegistryReference<Feature> ORE_GRAVEL = Features.key(ResourceKey.minecraft("ore_gravel"));

    public static final DefaultedRegistryReference<Feature> ORE_GRAVEL_NETHER = Features.key(ResourceKey.minecraft("ore_gravel_nether"));

    public static final DefaultedRegistryReference<Feature> ORE_INFESTED = Features.key(ResourceKey.minecraft("ore_infested"));

    public static final DefaultedRegistryReference<Feature> ORE_IRON = Features.key(ResourceKey.minecraft("ore_iron"));

    public static final DefaultedRegistryReference<Feature> ORE_IRON_SMALL = Features.key(ResourceKey.minecraft("ore_iron_small"));

    public static final DefaultedRegistryReference<Feature> ORE_LAPIS = Features.key(ResourceKey.minecraft("ore_lapis"));

    public static final DefaultedRegistryReference<Feature> ORE_LAPIS_BURIED = Features.key(ResourceKey.minecraft("ore_lapis_buried"));

    public static final DefaultedRegistryReference<Feature> ORE_MAGMA = Features.key(ResourceKey.minecraft("ore_magma"));

    public static final DefaultedRegistryReference<Feature> ORE_NETHER_GOLD = Features.key(ResourceKey.minecraft("ore_nether_gold"));

    public static final DefaultedRegistryReference<Feature> ORE_QUARTZ = Features.key(ResourceKey.minecraft("ore_quartz"));

    public static final DefaultedRegistryReference<Feature> ORE_REDSTONE = Features.key(ResourceKey.minecraft("ore_redstone"));

    public static final DefaultedRegistryReference<Feature> ORE_SOUL_SAND = Features.key(ResourceKey.minecraft("ore_soul_sand"));

    public static final DefaultedRegistryReference<Feature> ORE_TUFF = Features.key(ResourceKey.minecraft("ore_tuff"));

    public static final DefaultedRegistryReference<Feature> PATCH_BERRY_BUSH = Features.key(ResourceKey.minecraft("patch_berry_bush"));

    public static final DefaultedRegistryReference<Feature> PATCH_BROWN_MUSHROOM = Features.key(ResourceKey.minecraft("patch_brown_mushroom"));

    public static final DefaultedRegistryReference<Feature> PATCH_CACTUS = Features.key(ResourceKey.minecraft("patch_cactus"));

    public static final DefaultedRegistryReference<Feature> PATCH_CRIMSON_ROOTS = Features.key(ResourceKey.minecraft("patch_crimson_roots"));

    public static final DefaultedRegistryReference<Feature> PATCH_DEAD_BUSH = Features.key(ResourceKey.minecraft("patch_dead_bush"));

    public static final DefaultedRegistryReference<Feature> PATCH_FIRE = Features.key(ResourceKey.minecraft("patch_fire"));

    public static final DefaultedRegistryReference<Feature> PATCH_GRASS = Features.key(ResourceKey.minecraft("patch_grass"));

    public static final DefaultedRegistryReference<Feature> PATCH_GRASS_JUNGLE = Features.key(ResourceKey.minecraft("patch_grass_jungle"));

    public static final DefaultedRegistryReference<Feature> PATCH_LARGE_FERN = Features.key(ResourceKey.minecraft("patch_large_fern"));

    public static final DefaultedRegistryReference<Feature> PATCH_MELON = Features.key(ResourceKey.minecraft("patch_melon"));

    public static final DefaultedRegistryReference<Feature> PATCH_PUMPKIN = Features.key(ResourceKey.minecraft("patch_pumpkin"));

    public static final DefaultedRegistryReference<Feature> PATCH_RED_MUSHROOM = Features.key(ResourceKey.minecraft("patch_red_mushroom"));

    public static final DefaultedRegistryReference<Feature> PATCH_SOUL_FIRE = Features.key(ResourceKey.minecraft("patch_soul_fire"));

    public static final DefaultedRegistryReference<Feature> PATCH_SUGAR_CANE = Features.key(ResourceKey.minecraft("patch_sugar_cane"));

    public static final DefaultedRegistryReference<Feature> PATCH_SUNFLOWER = Features.key(ResourceKey.minecraft("patch_sunflower"));

    public static final DefaultedRegistryReference<Feature> PATCH_TAIGA_GRASS = Features.key(ResourceKey.minecraft("patch_taiga_grass"));

    public static final DefaultedRegistryReference<Feature> PATCH_TALL_GRASS = Features.key(ResourceKey.minecraft("patch_tall_grass"));

    public static final DefaultedRegistryReference<Feature> PATCH_WATERLILY = Features.key(ResourceKey.minecraft("patch_waterlily"));

    public static final DefaultedRegistryReference<Feature> PILE_HAY = Features.key(ResourceKey.minecraft("pile_hay"));

    public static final DefaultedRegistryReference<Feature> PILE_ICE = Features.key(ResourceKey.minecraft("pile_ice"));

    public static final DefaultedRegistryReference<Feature> PILE_MELON = Features.key(ResourceKey.minecraft("pile_melon"));

    public static final DefaultedRegistryReference<Feature> PILE_PUMPKIN = Features.key(ResourceKey.minecraft("pile_pumpkin"));

    public static final DefaultedRegistryReference<Feature> PILE_SNOW = Features.key(ResourceKey.minecraft("pile_snow"));

    public static final DefaultedRegistryReference<Feature> PINE = Features.key(ResourceKey.minecraft("pine"));

    public static final DefaultedRegistryReference<Feature> POINTED_DRIPSTONE = Features.key(ResourceKey.minecraft("pointed_dripstone"));

    public static final DefaultedRegistryReference<Feature> ROOTED_AZALEA_TREE = Features.key(ResourceKey.minecraft("rooted_azalea_tree"));

    public static final DefaultedRegistryReference<Feature> SCULK_PATCH_ANCIENT_CITY = Features.key(ResourceKey.minecraft("sculk_patch_ancient_city"));

    public static final DefaultedRegistryReference<Feature> SCULK_PATCH_DEEP_DARK = Features.key(ResourceKey.minecraft("sculk_patch_deep_dark"));

    public static final DefaultedRegistryReference<Feature> SCULK_VEIN = Features.key(ResourceKey.minecraft("sculk_vein"));

    public static final DefaultedRegistryReference<Feature> SEA_PICKLE = Features.key(ResourceKey.minecraft("sea_pickle"));

    public static final DefaultedRegistryReference<Feature> SEAGRASS_MID = Features.key(ResourceKey.minecraft("seagrass_mid"));

    public static final DefaultedRegistryReference<Feature> SEAGRASS_SHORT = Features.key(ResourceKey.minecraft("seagrass_short"));

    public static final DefaultedRegistryReference<Feature> SEAGRASS_SIMPLE = Features.key(ResourceKey.minecraft("seagrass_simple"));

    public static final DefaultedRegistryReference<Feature> SEAGRASS_SLIGHTLY_LESS_SHORT = Features.key(ResourceKey.minecraft("seagrass_slightly_less_short"));

    public static final DefaultedRegistryReference<Feature> SEAGRASS_TALL = Features.key(ResourceKey.minecraft("seagrass_tall"));

    public static final DefaultedRegistryReference<Feature> SINGLE_PIECE_OF_GRASS = Features.key(ResourceKey.minecraft("single_piece_of_grass"));

    public static final DefaultedRegistryReference<Feature> SMALL_BASALT_COLUMNS = Features.key(ResourceKey.minecraft("small_basalt_columns"));

    public static final DefaultedRegistryReference<Feature> SPORE_BLOSSOM = Features.key(ResourceKey.minecraft("spore_blossom"));

    public static final DefaultedRegistryReference<Feature> SPRING_LAVA_FROZEN = Features.key(ResourceKey.minecraft("spring_lava_frozen"));

    public static final DefaultedRegistryReference<Feature> SPRING_LAVA_NETHER = Features.key(ResourceKey.minecraft("spring_lava_nether"));

    public static final DefaultedRegistryReference<Feature> SPRING_LAVA_OVERWORLD = Features.key(ResourceKey.minecraft("spring_lava_overworld"));

    public static final DefaultedRegistryReference<Feature> SPRING_NETHER_CLOSED = Features.key(ResourceKey.minecraft("spring_nether_closed"));

    public static final DefaultedRegistryReference<Feature> SPRING_NETHER_OPEN = Features.key(ResourceKey.minecraft("spring_nether_open"));

    public static final DefaultedRegistryReference<Feature> SPRING_WATER = Features.key(ResourceKey.minecraft("spring_water"));

    public static final DefaultedRegistryReference<Feature> SPRUCE = Features.key(ResourceKey.minecraft("spruce"));

    public static final DefaultedRegistryReference<Feature> SUPER_BIRCH_BEES = Features.key(ResourceKey.minecraft("super_birch_bees"));

    public static final DefaultedRegistryReference<Feature> SUPER_BIRCH_BEES_0002 = Features.key(ResourceKey.minecraft("super_birch_bees_0002"));

    public static final DefaultedRegistryReference<Feature> SWAMP_OAK = Features.key(ResourceKey.minecraft("swamp_oak"));

    public static final DefaultedRegistryReference<Feature> TALL_MANGROVE = Features.key(ResourceKey.minecraft("tall_mangrove"));

    public static final DefaultedRegistryReference<Feature> TREES_BIRCH_AND_OAK = Features.key(ResourceKey.minecraft("trees_birch_and_oak"));

    public static final DefaultedRegistryReference<Feature> TREES_FLOWER_FOREST = Features.key(ResourceKey.minecraft("trees_flower_forest"));

    public static final DefaultedRegistryReference<Feature> TREES_GROVE = Features.key(ResourceKey.minecraft("trees_grove"));

    public static final DefaultedRegistryReference<Feature> TREES_JUNGLE = Features.key(ResourceKey.minecraft("trees_jungle"));

    public static final DefaultedRegistryReference<Feature> TREES_OLD_GROWTH_PINE_TAIGA = Features.key(ResourceKey.minecraft("trees_old_growth_pine_taiga"));

    public static final DefaultedRegistryReference<Feature> TREES_OLD_GROWTH_SPRUCE_TAIGA = Features.key(ResourceKey.minecraft("trees_old_growth_spruce_taiga"));

    public static final DefaultedRegistryReference<Feature> TREES_PLAINS = Features.key(ResourceKey.minecraft("trees_plains"));

    public static final DefaultedRegistryReference<Feature> TREES_SAVANNA = Features.key(ResourceKey.minecraft("trees_savanna"));

    public static final DefaultedRegistryReference<Feature> TREES_SPARSE_JUNGLE = Features.key(ResourceKey.minecraft("trees_sparse_jungle"));

    public static final DefaultedRegistryReference<Feature> TREES_TAIGA = Features.key(ResourceKey.minecraft("trees_taiga"));

    public static final DefaultedRegistryReference<Feature> TREES_WATER = Features.key(ResourceKey.minecraft("trees_water"));

    public static final DefaultedRegistryReference<Feature> TREES_WINDSWEPT_HILLS = Features.key(ResourceKey.minecraft("trees_windswept_hills"));

    public static final DefaultedRegistryReference<Feature> TWISTING_VINES = Features.key(ResourceKey.minecraft("twisting_vines"));

    public static final DefaultedRegistryReference<Feature> TWISTING_VINES_BONEMEAL = Features.key(ResourceKey.minecraft("twisting_vines_bonemeal"));

    public static final DefaultedRegistryReference<Feature> UNDERWATER_MAGMA = Features.key(ResourceKey.minecraft("underwater_magma"));

    public static final DefaultedRegistryReference<Feature> VINES = Features.key(ResourceKey.minecraft("vines"));

    public static final DefaultedRegistryReference<Feature> VOID_START_PLATFORM = Features.key(ResourceKey.minecraft("void_start_platform"));

    public static final DefaultedRegistryReference<Feature> WARM_OCEAN_VEGETATION = Features.key(ResourceKey.minecraft("warm_ocean_vegetation"));

    public static final DefaultedRegistryReference<Feature> WARPED_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("warped_forest_vegetation"));

    public static final DefaultedRegistryReference<Feature> WARPED_FOREST_VEGETATION_BONEMEAL = Features.key(ResourceKey.minecraft("warped_forest_vegetation_bonemeal"));

    public static final DefaultedRegistryReference<Feature> WARPED_FUNGUS = Features.key(ResourceKey.minecraft("warped_fungus"));

    public static final DefaultedRegistryReference<Feature> WARPED_FUNGUS_PLANTED = Features.key(ResourceKey.minecraft("warped_fungus_planted"));

    public static final DefaultedRegistryReference<Feature> WEEPING_VINES = Features.key(ResourceKey.minecraft("weeping_vines"));

    //@formatter:on
    private Features() {
    }

    public static Registry<Feature> registry() {
        return Sponge.server().registry(RegistryTypes.FEATURE);
    }

    private static DefaultedRegistryReference<Feature> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.FEATURE, location).asDefaultedReference(Sponge::server);
    }
}
