/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.feature;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryReference;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.server.ServerWorld;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.WORLD)
public final class Features {

    // @formatter:off
    public static final RegistryReference<Feature<?>> ACACIA = Features.key(ResourceKey.minecraft("acacia"));

    public static final RegistryReference<Feature<?>> ACACIA_CHECKED = Features.key(ResourceKey.minecraft("acacia_checked"));

    public static final RegistryReference<Feature<?>> AMETHYST_GEODE = Features.key(ResourceKey.minecraft("amethyst_geode"));

    public static final RegistryReference<Feature<?>> BAMBOO = Features.key(ResourceKey.minecraft("bamboo"));

    public static final RegistryReference<Feature<?>> BAMBOO_LIGHT = Features.key(ResourceKey.minecraft("bamboo_light"));

    public static final RegistryReference<Feature<?>> BAMBOO_VEGETATION = Features.key(ResourceKey.minecraft("bamboo_vegetation"));

    public static final RegistryReference<Feature<?>> BASALT_BLOBS = Features.key(ResourceKey.minecraft("basalt_blobs"));

    public static final RegistryReference<Feature<?>> BASALT_PILLAR = Features.key(ResourceKey.minecraft("basalt_pillar"));

    public static final RegistryReference<Feature<?>> BIRCH_BEES_0002 = Features.key(ResourceKey.minecraft("birch_bees_0002"));

    public static final RegistryReference<Feature<?>> BIRCH_BEES_002 = Features.key(ResourceKey.minecraft("birch_bees_002"));

    public static final RegistryReference<Feature<?>> BIRCH_CHECKED = Features.key(ResourceKey.minecraft("birch_checked"));

    public static final RegistryReference<Feature<?>> BIRCH_TALL = Features.key(ResourceKey.minecraft("birch_tall"));

    public static final RegistryReference<Feature<?>> BLACKSTONE_BLOBS = Features.key(ResourceKey.minecraft("blackstone_blobs"));

    public static final RegistryReference<Feature<?>> BLUE_ICE = Features.key(ResourceKey.minecraft("blue_ice"));

    public static final RegistryReference<Feature<?>> BROWN_MUSHROOM_NETHER = Features.key(ResourceKey.minecraft("brown_mushroom_nether"));

    public static final RegistryReference<Feature<?>> BROWN_MUSHROOM_NORMAL = Features.key(ResourceKey.minecraft("brown_mushroom_normal"));

    public static final RegistryReference<Feature<?>> BROWN_MUSHROOM_OLD_GROWTH = Features.key(ResourceKey.minecraft("brown_mushroom_old_growth"));

    public static final RegistryReference<Feature<?>> BROWN_MUSHROOM_SWAMP = Features.key(ResourceKey.minecraft("brown_mushroom_swamp"));

    public static final RegistryReference<Feature<?>> BROWN_MUSHROOM_TAIGA = Features.key(ResourceKey.minecraft("brown_mushroom_taiga"));

    public static final RegistryReference<Feature<?>> CAVE_VINES = Features.key(ResourceKey.minecraft("cave_vines"));

    public static final RegistryReference<Feature<?>> CHORUS_PLANT = Features.key(ResourceKey.minecraft("chorus_plant"));

    public static final RegistryReference<Feature<?>> CLASSIC_VINES_CAVE_FEATURE = Features.key(ResourceKey.minecraft("classic_vines_cave_feature"));

    public static final RegistryReference<Feature<?>> CRIMSON_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("crimson_forest_vegetation"));

    public static final RegistryReference<Feature<?>> CRIMSON_FUNGI = Features.key(ResourceKey.minecraft("crimson_fungi"));

    public static final RegistryReference<Feature<?>> DARK_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("dark_forest_vegetation"));

    public static final RegistryReference<Feature<?>> DARK_OAK_CHECKED = Features.key(ResourceKey.minecraft("dark_oak_checked"));

    public static final RegistryReference<Feature<?>> DELTA = Features.key(ResourceKey.minecraft("delta"));

    public static final RegistryReference<Feature<?>> DESERT_WELL = Features.key(ResourceKey.minecraft("desert_well"));

    public static final RegistryReference<Feature<?>> DISK_CLAY = Features.key(ResourceKey.minecraft("disk_clay"));

    public static final RegistryReference<Feature<?>> DISK_GRASS = Features.key(ResourceKey.minecraft("disk_grass"));

    public static final RegistryReference<Feature<?>> DISK_GRAVEL = Features.key(ResourceKey.minecraft("disk_gravel"));

    public static final RegistryReference<Feature<?>> DISK_SAND = Features.key(ResourceKey.minecraft("disk_sand"));

    public static final RegistryReference<Feature<?>> DRIPSTONE_CLUSTER = Features.key(ResourceKey.minecraft("dripstone_cluster"));

    public static final RegistryReference<Feature<?>> END_GATEWAY_RETURN = Features.key(ResourceKey.minecraft("end_gateway_return"));

    public static final RegistryReference<Feature<?>> END_ISLAND_DECORATED = Features.key(ResourceKey.minecraft("end_island_decorated"));

    public static final RegistryReference<Feature<?>> END_SPIKE = Features.key(ResourceKey.minecraft("end_spike"));

    public static final RegistryReference<Feature<?>> FANCY_OAK_BEES = Features.key(ResourceKey.minecraft("fancy_oak_bees"));

    public static final RegistryReference<Feature<?>> FANCY_OAK_BEES_0002 = Features.key(ResourceKey.minecraft("fancy_oak_bees_0002"));

    public static final RegistryReference<Feature<?>> FANCY_OAK_BEES_002 = Features.key(ResourceKey.minecraft("fancy_oak_bees_002"));

    public static final RegistryReference<Feature<?>> FANCY_OAK_CHECKED = Features.key(ResourceKey.minecraft("fancy_oak_checked"));

    public static final RegistryReference<Feature<?>> FLOWER_DEFAULT = Features.key(ResourceKey.minecraft("flower_default"));

    public static final RegistryReference<Feature<?>> FLOWER_FLOWER_FOREST = Features.key(ResourceKey.minecraft("flower_flower_forest"));

    public static final RegistryReference<Feature<?>> FLOWER_FOREST_FLOWERS = Features.key(ResourceKey.minecraft("flower_forest_flowers"));

    public static final RegistryReference<Feature<?>> FLOWER_MEADOW = Features.key(ResourceKey.minecraft("flower_meadow"));

    public static final RegistryReference<Feature<?>> FLOWER_PLAIN = Features.key(ResourceKey.minecraft("flower_plain"));

    public static final RegistryReference<Feature<?>> FLOWER_PLAINS = Features.key(ResourceKey.minecraft("flower_plains"));

    public static final RegistryReference<Feature<?>> FLOWER_SWAMP = Features.key(ResourceKey.minecraft("flower_swamp"));

    public static final RegistryReference<Feature<?>> FLOWER_WARM = Features.key(ResourceKey.minecraft("flower_warm"));

    public static final RegistryReference<Feature<?>> FOREST_FLOWERS = Features.key(ResourceKey.minecraft("forest_flowers"));

    public static final RegistryReference<Feature<?>> FOREST_ROCK = Features.key(ResourceKey.minecraft("forest_rock"));

    public static final RegistryReference<Feature<?>> FOSSIL_LOWER = Features.key(ResourceKey.minecraft("fossil_lower"));

    public static final RegistryReference<Feature<?>> FOSSIL_UPPER = Features.key(ResourceKey.minecraft("fossil_upper"));

    public static final RegistryReference<Feature<?>> FREEZE_TOP_LAYER = Features.key(ResourceKey.minecraft("freeze_top_layer"));

    public static final RegistryReference<Feature<?>> GLOW_LICHEN = Features.key(ResourceKey.minecraft("glow_lichen"));

    public static final RegistryReference<Feature<?>> GLOWSTONE = Features.key(ResourceKey.minecraft("glowstone"));

    public static final RegistryReference<Feature<?>> GLOWSTONE_EXTRA = Features.key(ResourceKey.minecraft("glowstone_extra"));

    public static final RegistryReference<Feature<?>> GRASS_BONEMEAL = Features.key(ResourceKey.minecraft("grass_bonemeal"));

    public static final RegistryReference<Feature<?>> ICE_PATCH = Features.key(ResourceKey.minecraft("ice_patch"));

    public static final RegistryReference<Feature<?>> ICE_SPIKE = Features.key(ResourceKey.minecraft("ice_spike"));

    public static final RegistryReference<Feature<?>> ICEBERG_BLUE = Features.key(ResourceKey.minecraft("iceberg_blue"));

    public static final RegistryReference<Feature<?>> ICEBERG_PACKED = Features.key(ResourceKey.minecraft("iceberg_packed"));

    public static final RegistryReference<Feature<?>> JUNGLE_BUSH = Features.key(ResourceKey.minecraft("jungle_bush"));

    public static final RegistryReference<Feature<?>> JUNGLE_TREE = Features.key(ResourceKey.minecraft("jungle_tree"));

    public static final RegistryReference<Feature<?>> KELP_COLD = Features.key(ResourceKey.minecraft("kelp_cold"));

    public static final RegistryReference<Feature<?>> KELP_WARM = Features.key(ResourceKey.minecraft("kelp_warm"));

    public static final RegistryReference<Feature<?>> LAKE_LAVA_SURFACE = Features.key(ResourceKey.minecraft("lake_lava_surface"));

    public static final RegistryReference<Feature<?>> LAKE_LAVA_UNDERGROUND = Features.key(ResourceKey.minecraft("lake_lava_underground"));

    public static final RegistryReference<Feature<?>> LARGE_BASALT_COLUMNS = Features.key(ResourceKey.minecraft("large_basalt_columns"));

    public static final RegistryReference<Feature<?>> LARGE_DRIPSTONE = Features.key(ResourceKey.minecraft("large_dripstone"));

    public static final RegistryReference<Feature<?>> LUSH_CAVES_CEILING_VEGETATION = Features.key(ResourceKey.minecraft("lush_caves_ceiling_vegetation"));

    public static final RegistryReference<Feature<?>> LUSH_CAVES_CLAY = Features.key(ResourceKey.minecraft("lush_caves_clay"));

    public static final RegistryReference<Feature<?>> LUSH_CAVES_VEGETATION = Features.key(ResourceKey.minecraft("lush_caves_vegetation"));

    public static final RegistryReference<Feature<?>> MANGROVE_CHECKED = Features.key(ResourceKey.minecraft("mangrove_checked"));

    public static final RegistryReference<Feature<?>> MEGA_JUNGLE_TREE_CHECKED = Features.key(ResourceKey.minecraft("mega_jungle_tree_checked"));

    public static final RegistryReference<Feature<?>> MEGA_PINE_CHECKED = Features.key(ResourceKey.minecraft("mega_pine_checked"));

    public static final RegistryReference<Feature<?>> MEGA_SPRUCE_CHECKED = Features.key(ResourceKey.minecraft("mega_spruce_checked"));

    public static final RegistryReference<Feature<?>> MONSTER_ROOM = Features.key(ResourceKey.minecraft("monster_room"));

    public static final RegistryReference<Feature<?>> MONSTER_ROOM_DEEP = Features.key(ResourceKey.minecraft("monster_room_deep"));

    public static final RegistryReference<Feature<?>> MUSHROOM_ISLAND_VEGETATION = Features.key(ResourceKey.minecraft("mushroom_island_vegetation"));

    public static final RegistryReference<Feature<?>> NETHER_SPROUTS = Features.key(ResourceKey.minecraft("nether_sprouts"));

    public static final RegistryReference<Feature<?>> OAK = Features.key(ResourceKey.minecraft("oak"));

    public static final RegistryReference<Feature<?>> OAK_BEES_0002 = Features.key(ResourceKey.minecraft("oak_bees_0002"));

    public static final RegistryReference<Feature<?>> OAK_BEES_002 = Features.key(ResourceKey.minecraft("oak_bees_002"));

    public static final RegistryReference<Feature<?>> OAK_CHECKED = Features.key(ResourceKey.minecraft("oak_checked"));

    public static final RegistryReference<Feature<?>> ORE_ANCIENT_DEBRIS_LARGE = Features.key(ResourceKey.minecraft("ore_ancient_debris_large"));

    public static final RegistryReference<Feature<?>> ORE_ANDESITE_LOWER = Features.key(ResourceKey.minecraft("ore_andesite_lower"));

    public static final RegistryReference<Feature<?>> ORE_ANDESITE_UPPER = Features.key(ResourceKey.minecraft("ore_andesite_upper"));

    public static final RegistryReference<Feature<?>> ORE_BLACKSTONE = Features.key(ResourceKey.minecraft("ore_blackstone"));

    public static final RegistryReference<Feature<?>> ORE_CLAY = Features.key(ResourceKey.minecraft("ore_clay"));

    public static final RegistryReference<Feature<?>> ORE_COAL_LOWER = Features.key(ResourceKey.minecraft("ore_coal_lower"));

    public static final RegistryReference<Feature<?>> ORE_COAL_UPPER = Features.key(ResourceKey.minecraft("ore_coal_upper"));

    public static final RegistryReference<Feature<?>> ORE_COPPER = Features.key(ResourceKey.minecraft("ore_copper"));

    public static final RegistryReference<Feature<?>> ORE_COPPER_LARGE = Features.key(ResourceKey.minecraft("ore_copper_large"));

    public static final RegistryReference<Feature<?>> ORE_DEBRIS_SMALL = Features.key(ResourceKey.minecraft("ore_debris_small"));

    public static final RegistryReference<Feature<?>> ORE_DIAMOND = Features.key(ResourceKey.minecraft("ore_diamond"));

    public static final RegistryReference<Feature<?>> ORE_DIAMOND_BURIED = Features.key(ResourceKey.minecraft("ore_diamond_buried"));

    public static final RegistryReference<Feature<?>> ORE_DIAMOND_LARGE = Features.key(ResourceKey.minecraft("ore_diamond_large"));

    public static final RegistryReference<Feature<?>> ORE_DIORITE_LOWER = Features.key(ResourceKey.minecraft("ore_diorite_lower"));

    public static final RegistryReference<Feature<?>> ORE_DIORITE_UPPER = Features.key(ResourceKey.minecraft("ore_diorite_upper"));

    public static final RegistryReference<Feature<?>> ORE_DIRT = Features.key(ResourceKey.minecraft("ore_dirt"));

    public static final RegistryReference<Feature<?>> ORE_EMERALD = Features.key(ResourceKey.minecraft("ore_emerald"));

    public static final RegistryReference<Feature<?>> ORE_GOLD = Features.key(ResourceKey.minecraft("ore_gold"));

    public static final RegistryReference<Feature<?>> ORE_GOLD_DELTAS = Features.key(ResourceKey.minecraft("ore_gold_deltas"));

    public static final RegistryReference<Feature<?>> ORE_GOLD_EXTRA = Features.key(ResourceKey.minecraft("ore_gold_extra"));

    public static final RegistryReference<Feature<?>> ORE_GOLD_LOWER = Features.key(ResourceKey.minecraft("ore_gold_lower"));

    public static final RegistryReference<Feature<?>> ORE_GOLD_NETHER = Features.key(ResourceKey.minecraft("ore_gold_nether"));

    public static final RegistryReference<Feature<?>> ORE_GRANITE_LOWER = Features.key(ResourceKey.minecraft("ore_granite_lower"));

    public static final RegistryReference<Feature<?>> ORE_GRANITE_UPPER = Features.key(ResourceKey.minecraft("ore_granite_upper"));

    public static final RegistryReference<Feature<?>> ORE_GRAVEL = Features.key(ResourceKey.minecraft("ore_gravel"));

    public static final RegistryReference<Feature<?>> ORE_GRAVEL_NETHER = Features.key(ResourceKey.minecraft("ore_gravel_nether"));

    public static final RegistryReference<Feature<?>> ORE_INFESTED = Features.key(ResourceKey.minecraft("ore_infested"));

    public static final RegistryReference<Feature<?>> ORE_IRON_MIDDLE = Features.key(ResourceKey.minecraft("ore_iron_middle"));

    public static final RegistryReference<Feature<?>> ORE_IRON_SMALL = Features.key(ResourceKey.minecraft("ore_iron_small"));

    public static final RegistryReference<Feature<?>> ORE_IRON_UPPER = Features.key(ResourceKey.minecraft("ore_iron_upper"));

    public static final RegistryReference<Feature<?>> ORE_LAPIS = Features.key(ResourceKey.minecraft("ore_lapis"));

    public static final RegistryReference<Feature<?>> ORE_LAPIS_BURIED = Features.key(ResourceKey.minecraft("ore_lapis_buried"));

    public static final RegistryReference<Feature<?>> ORE_MAGMA = Features.key(ResourceKey.minecraft("ore_magma"));

    public static final RegistryReference<Feature<?>> ORE_QUARTZ_DELTAS = Features.key(ResourceKey.minecraft("ore_quartz_deltas"));

    public static final RegistryReference<Feature<?>> ORE_QUARTZ_NETHER = Features.key(ResourceKey.minecraft("ore_quartz_nether"));

    public static final RegistryReference<Feature<?>> ORE_REDSTONE = Features.key(ResourceKey.minecraft("ore_redstone"));

    public static final RegistryReference<Feature<?>> ORE_REDSTONE_LOWER = Features.key(ResourceKey.minecraft("ore_redstone_lower"));

    public static final RegistryReference<Feature<?>> ORE_SOUL_SAND = Features.key(ResourceKey.minecraft("ore_soul_sand"));

    public static final RegistryReference<Feature<?>> ORE_TUFF = Features.key(ResourceKey.minecraft("ore_tuff"));

    public static final RegistryReference<Feature<?>> PATCH_BERRY_BUSH = Features.key(ResourceKey.minecraft("patch_berry_bush"));

    public static final RegistryReference<Feature<?>> PATCH_BERRY_COMMON = Features.key(ResourceKey.minecraft("patch_berry_common"));

    public static final RegistryReference<Feature<?>> PATCH_BERRY_RARE = Features.key(ResourceKey.minecraft("patch_berry_rare"));

    public static final RegistryReference<Feature<?>> PATCH_CACTUS = Features.key(ResourceKey.minecraft("patch_cactus"));

    public static final RegistryReference<Feature<?>> PATCH_CACTUS_DECORATED = Features.key(ResourceKey.minecraft("patch_cactus_decorated"));

    public static final RegistryReference<Feature<?>> PATCH_CACTUS_DESERT = Features.key(ResourceKey.minecraft("patch_cactus_desert"));

    public static final RegistryReference<Feature<?>> PATCH_CRIMSON_ROOTS = Features.key(ResourceKey.minecraft("patch_crimson_roots"));

    public static final RegistryReference<Feature<?>> PATCH_DEAD_BUSH = Features.key(ResourceKey.minecraft("patch_dead_bush"));

    public static final RegistryReference<Feature<?>> PATCH_DEAD_BUSH_2 = Features.key(ResourceKey.minecraft("patch_dead_bush_2"));

    public static final RegistryReference<Feature<?>> PATCH_DEAD_BUSH_BADLANDS = Features.key(ResourceKey.minecraft("patch_dead_bush_badlands"));

    public static final RegistryReference<Feature<?>> PATCH_FIRE = Features.key(ResourceKey.minecraft("patch_fire"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_BADLANDS = Features.key(ResourceKey.minecraft("patch_grass_badlands"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_FOREST = Features.key(ResourceKey.minecraft("patch_grass_forest"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_JUNGLE = Features.key(ResourceKey.minecraft("patch_grass_jungle"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_NORMAL = Features.key(ResourceKey.minecraft("patch_grass_normal"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_PLAIN = Features.key(ResourceKey.minecraft("patch_grass_plain"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_SAVANNA = Features.key(ResourceKey.minecraft("patch_grass_savanna"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_TAIGA = Features.key(ResourceKey.minecraft("patch_grass_taiga"));

    public static final RegistryReference<Feature<?>> PATCH_GRASS_TAIGA_2 = Features.key(ResourceKey.minecraft("patch_grass_taiga_2"));

    public static final RegistryReference<Feature<?>> PATCH_LARGE_FERN = Features.key(ResourceKey.minecraft("patch_large_fern"));

    public static final RegistryReference<Feature<?>> PATCH_MELON = Features.key(ResourceKey.minecraft("patch_melon"));

    public static final RegistryReference<Feature<?>> PATCH_MELON_SPARSE = Features.key(ResourceKey.minecraft("patch_melon_sparse"));

    public static final RegistryReference<Feature<?>> PATCH_PUMPKIN = Features.key(ResourceKey.minecraft("patch_pumpkin"));

    public static final RegistryReference<Feature<?>> PATCH_SOUL_FIRE = Features.key(ResourceKey.minecraft("patch_soul_fire"));

    public static final RegistryReference<Feature<?>> PATCH_SUGAR_CANE = Features.key(ResourceKey.minecraft("patch_sugar_cane"));

    public static final RegistryReference<Feature<?>> PATCH_SUGAR_CANE_BADLANDS = Features.key(ResourceKey.minecraft("patch_sugar_cane_badlands"));

    public static final RegistryReference<Feature<?>> PATCH_SUGAR_CANE_DESERT = Features.key(ResourceKey.minecraft("patch_sugar_cane_desert"));

    public static final RegistryReference<Feature<?>> PATCH_SUGAR_CANE_SWAMP = Features.key(ResourceKey.minecraft("patch_sugar_cane_swamp"));

    public static final RegistryReference<Feature<?>> PATCH_SUNFLOWER = Features.key(ResourceKey.minecraft("patch_sunflower"));

    public static final RegistryReference<Feature<?>> PATCH_TAIGA_GRASS = Features.key(ResourceKey.minecraft("patch_taiga_grass"));

    public static final RegistryReference<Feature<?>> PATCH_TALL_GRASS = Features.key(ResourceKey.minecraft("patch_tall_grass"));

    public static final RegistryReference<Feature<?>> PATCH_TALL_GRASS_2 = Features.key(ResourceKey.minecraft("patch_tall_grass_2"));

    public static final RegistryReference<Feature<?>> PATCH_WATERLILY = Features.key(ResourceKey.minecraft("patch_waterlily"));

    public static final RegistryReference<Feature<?>> PILE_HAY = Features.key(ResourceKey.minecraft("pile_hay"));

    public static final RegistryReference<Feature<?>> PILE_ICE = Features.key(ResourceKey.minecraft("pile_ice"));

    public static final RegistryReference<Feature<?>> PILE_MELON = Features.key(ResourceKey.minecraft("pile_melon"));

    public static final RegistryReference<Feature<?>> PILE_PUMPKIN = Features.key(ResourceKey.minecraft("pile_pumpkin"));

    public static final RegistryReference<Feature<?>> PILE_SNOW = Features.key(ResourceKey.minecraft("pile_snow"));

    public static final RegistryReference<Feature<?>> PINE = Features.key(ResourceKey.minecraft("pine"));

    public static final RegistryReference<Feature<?>> PINE_CHECKED = Features.key(ResourceKey.minecraft("pine_checked"));

    public static final RegistryReference<Feature<?>> PINE_ON_SNOW = Features.key(ResourceKey.minecraft("pine_on_snow"));

    public static final RegistryReference<Feature<?>> POINTED_DRIPSTONE = Features.key(ResourceKey.minecraft("pointed_dripstone"));

    public static final RegistryReference<Feature<?>> RED_MUSHROOM_NETHER = Features.key(ResourceKey.minecraft("red_mushroom_nether"));

    public static final RegistryReference<Feature<?>> RED_MUSHROOM_NORMAL = Features.key(ResourceKey.minecraft("red_mushroom_normal"));

    public static final RegistryReference<Feature<?>> RED_MUSHROOM_OLD_GROWTH = Features.key(ResourceKey.minecraft("red_mushroom_old_growth"));

    public static final RegistryReference<Feature<?>> RED_MUSHROOM_SWAMP = Features.key(ResourceKey.minecraft("red_mushroom_swamp"));

    public static final RegistryReference<Feature<?>> RED_MUSHROOM_TAIGA = Features.key(ResourceKey.minecraft("red_mushroom_taiga"));

    public static final RegistryReference<Feature<?>> ROOTED_AZALEA_TREE = Features.key(ResourceKey.minecraft("rooted_azalea_tree"));

    public static final RegistryReference<Feature<?>> SCULK_PATCH_ANCIENT_CITY = Features.key(ResourceKey.minecraft("sculk_patch_ancient_city"));

    public static final RegistryReference<Feature<?>> SCULK_PATCH_DEEP_DARK = Features.key(ResourceKey.minecraft("sculk_patch_deep_dark"));

    public static final RegistryReference<Feature<?>> SCULK_VEIN = Features.key(ResourceKey.minecraft("sculk_vein"));

    public static final RegistryReference<Feature<?>> SEA_PICKLE = Features.key(ResourceKey.minecraft("sea_pickle"));

    public static final RegistryReference<Feature<?>> SEAGRASS_COLD = Features.key(ResourceKey.minecraft("seagrass_cold"));

    public static final RegistryReference<Feature<?>> SEAGRASS_DEEP = Features.key(ResourceKey.minecraft("seagrass_deep"));

    public static final RegistryReference<Feature<?>> SEAGRASS_DEEP_COLD = Features.key(ResourceKey.minecraft("seagrass_deep_cold"));

    public static final RegistryReference<Feature<?>> SEAGRASS_DEEP_WARM = Features.key(ResourceKey.minecraft("seagrass_deep_warm"));

    public static final RegistryReference<Feature<?>> SEAGRASS_NORMAL = Features.key(ResourceKey.minecraft("seagrass_normal"));

    public static final RegistryReference<Feature<?>> SEAGRASS_RIVER = Features.key(ResourceKey.minecraft("seagrass_river"));

    public static final RegistryReference<Feature<?>> SEAGRASS_SIMPLE = Features.key(ResourceKey.minecraft("seagrass_simple"));

    public static final RegistryReference<Feature<?>> SEAGRASS_SWAMP = Features.key(ResourceKey.minecraft("seagrass_swamp"));

    public static final RegistryReference<Feature<?>> SEAGRASS_WARM = Features.key(ResourceKey.minecraft("seagrass_warm"));

    public static final RegistryReference<Feature<?>> SMALL_BASALT_COLUMNS = Features.key(ResourceKey.minecraft("small_basalt_columns"));

    public static final RegistryReference<Feature<?>> SPORE_BLOSSOM = Features.key(ResourceKey.minecraft("spore_blossom"));

    public static final RegistryReference<Feature<?>> SPRING_CLOSED = Features.key(ResourceKey.minecraft("spring_closed"));

    public static final RegistryReference<Feature<?>> SPRING_CLOSED_DOUBLE = Features.key(ResourceKey.minecraft("spring_closed_double"));

    public static final RegistryReference<Feature<?>> SPRING_DELTA = Features.key(ResourceKey.minecraft("spring_delta"));

    public static final RegistryReference<Feature<?>> SPRING_LAVA = Features.key(ResourceKey.minecraft("spring_lava"));

    public static final RegistryReference<Feature<?>> SPRING_LAVA_FROZEN = Features.key(ResourceKey.minecraft("spring_lava_frozen"));

    public static final RegistryReference<Feature<?>> SPRING_OPEN = Features.key(ResourceKey.minecraft("spring_open"));

    public static final RegistryReference<Feature<?>> SPRING_WATER = Features.key(ResourceKey.minecraft("spring_water"));

    public static final RegistryReference<Feature<?>> SPRUCE = Features.key(ResourceKey.minecraft("spruce"));

    public static final RegistryReference<Feature<?>> SPRUCE_CHECKED = Features.key(ResourceKey.minecraft("spruce_checked"));

    public static final RegistryReference<Feature<?>> SPRUCE_ON_SNOW = Features.key(ResourceKey.minecraft("spruce_on_snow"));

    public static final RegistryReference<Feature<?>> SUPER_BIRCH_BEES = Features.key(ResourceKey.minecraft("super_birch_bees"));

    public static final RegistryReference<Feature<?>> SUPER_BIRCH_BEES_0002 = Features.key(ResourceKey.minecraft("super_birch_bees_0002"));

    public static final RegistryReference<Feature<?>> TALL_MANGROVE_CHECKED = Features.key(ResourceKey.minecraft("tall_mangrove_checked"));

    public static final RegistryReference<Feature<?>> TREES_BADLANDS = Features.key(ResourceKey.minecraft("trees_badlands"));

    public static final RegistryReference<Feature<?>> TREES_BIRCH = Features.key(ResourceKey.minecraft("trees_birch"));

    public static final RegistryReference<Feature<?>> TREES_BIRCH_AND_OAK = Features.key(ResourceKey.minecraft("trees_birch_and_oak"));

    public static final RegistryReference<Feature<?>> TREES_FLOWER_FOREST = Features.key(ResourceKey.minecraft("trees_flower_forest"));

    public static final RegistryReference<Feature<?>> TREES_GROVE = Features.key(ResourceKey.minecraft("trees_grove"));

    public static final RegistryReference<Feature<?>> TREES_JUNGLE = Features.key(ResourceKey.minecraft("trees_jungle"));

    public static final RegistryReference<Feature<?>> TREES_MANGROVE = Features.key(ResourceKey.minecraft("trees_mangrove"));

    public static final RegistryReference<Feature<?>> TREES_MEADOW = Features.key(ResourceKey.minecraft("trees_meadow"));

    public static final RegistryReference<Feature<?>> TREES_OLD_GROWTH_PINE_TAIGA = Features.key(ResourceKey.minecraft("trees_old_growth_pine_taiga"));

    public static final RegistryReference<Feature<?>> TREES_OLD_GROWTH_SPRUCE_TAIGA = Features.key(ResourceKey.minecraft("trees_old_growth_spruce_taiga"));

    public static final RegistryReference<Feature<?>> TREES_PLAINS = Features.key(ResourceKey.minecraft("trees_plains"));

    public static final RegistryReference<Feature<?>> TREES_SAVANNA = Features.key(ResourceKey.minecraft("trees_savanna"));

    public static final RegistryReference<Feature<?>> TREES_SNOWY = Features.key(ResourceKey.minecraft("trees_snowy"));

    public static final RegistryReference<Feature<?>> TREES_SPARSE_JUNGLE = Features.key(ResourceKey.minecraft("trees_sparse_jungle"));

    public static final RegistryReference<Feature<?>> TREES_SWAMP = Features.key(ResourceKey.minecraft("trees_swamp"));

    public static final RegistryReference<Feature<?>> TREES_TAIGA = Features.key(ResourceKey.minecraft("trees_taiga"));

    public static final RegistryReference<Feature<?>> TREES_WATER = Features.key(ResourceKey.minecraft("trees_water"));

    public static final RegistryReference<Feature<?>> TREES_WINDSWEPT_FOREST = Features.key(ResourceKey.minecraft("trees_windswept_forest"));

    public static final RegistryReference<Feature<?>> TREES_WINDSWEPT_HILLS = Features.key(ResourceKey.minecraft("trees_windswept_hills"));

    public static final RegistryReference<Feature<?>> TREES_WINDSWEPT_SAVANNA = Features.key(ResourceKey.minecraft("trees_windswept_savanna"));

    public static final RegistryReference<Feature<?>> TWISTING_VINES = Features.key(ResourceKey.minecraft("twisting_vines"));

    public static final RegistryReference<Feature<?>> UNDERWATER_MAGMA = Features.key(ResourceKey.minecraft("underwater_magma"));

    public static final RegistryReference<Feature<?>> VINES = Features.key(ResourceKey.minecraft("vines"));

    public static final RegistryReference<Feature<?>> VOID_START_PLATFORM = Features.key(ResourceKey.minecraft("void_start_platform"));

    public static final RegistryReference<Feature<?>> WARM_OCEAN_VEGETATION = Features.key(ResourceKey.minecraft("warm_ocean_vegetation"));

    public static final RegistryReference<Feature<?>> WARPED_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("warped_forest_vegetation"));

    public static final RegistryReference<Feature<?>> WARPED_FUNGI = Features.key(ResourceKey.minecraft("warped_fungi"));

    public static final RegistryReference<Feature<?>> WEEPING_VINES = Features.key(ResourceKey.minecraft("weeping_vines"));

    // @formatter:on
    private Features() {
    }

    public static Registry<Feature<?>> registry(final ServerWorld world) {
        return world.registry(RegistryTypes.FEATURE);
    }

    private static RegistryReference<Feature<?>> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.FEATURE, location).asReference();
    }
}
