/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.feature;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class Features {

    // @formatter:off
    public static final DefaultedRegistryReference<Feature> BAMBOO = Features.key(ResourceKey.minecraft("bamboo"));

    public static final DefaultedRegistryReference<Feature> BASALT_COLUMNS = Features.key(ResourceKey.minecraft("basalt_columns"));

    public static final DefaultedRegistryReference<Feature> BASALT_PILLAR = Features.key(ResourceKey.minecraft("basalt_pillar"));

    public static final DefaultedRegistryReference<Feature> BLOCK_COLUMN = Features.key(ResourceKey.minecraft("block_column"));

    public static final DefaultedRegistryReference<Feature> BLOCK_PILE = Features.key(ResourceKey.minecraft("block_pile"));

    public static final DefaultedRegistryReference<Feature> BLUE_ICE = Features.key(ResourceKey.minecraft("blue_ice"));

    public static final DefaultedRegistryReference<Feature> BONUS_CHEST = Features.key(ResourceKey.minecraft("bonus_chest"));

    public static final DefaultedRegistryReference<Feature> CHORUS_PLANT = Features.key(ResourceKey.minecraft("chorus_plant"));

    public static final DefaultedRegistryReference<Feature> CORAL_CLAW = Features.key(ResourceKey.minecraft("coral_claw"));

    public static final DefaultedRegistryReference<Feature> CORAL_MUSHROOM = Features.key(ResourceKey.minecraft("coral_mushroom"));

    public static final DefaultedRegistryReference<Feature> CORAL_TREE = Features.key(ResourceKey.minecraft("coral_tree"));

    public static final DefaultedRegistryReference<Feature> DELTA_FEATURE = Features.key(ResourceKey.minecraft("delta_feature"));

    public static final DefaultedRegistryReference<Feature> DESERT_WELL = Features.key(ResourceKey.minecraft("desert_well"));

    public static final DefaultedRegistryReference<Feature> DISK = Features.key(ResourceKey.minecraft("disk"));

    public static final DefaultedRegistryReference<Feature> DRIPSTONE_CLUSTER = Features.key(ResourceKey.minecraft("dripstone_cluster"));

    public static final DefaultedRegistryReference<Feature> END_GATEWAY = Features.key(ResourceKey.minecraft("end_gateway"));

    public static final DefaultedRegistryReference<Feature> END_ISLAND = Features.key(ResourceKey.minecraft("end_island"));

    public static final DefaultedRegistryReference<Feature> END_SPIKE = Features.key(ResourceKey.minecraft("end_spike"));

    public static final DefaultedRegistryReference<Feature> FILL_LAYER = Features.key(ResourceKey.minecraft("fill_layer"));

    public static final DefaultedRegistryReference<Feature> FLOWER = Features.key(ResourceKey.minecraft("flower"));

    public static final DefaultedRegistryReference<Feature> FOREST_ROCK = Features.key(ResourceKey.minecraft("forest_rock"));

    public static final DefaultedRegistryReference<Feature> FOSSIL = Features.key(ResourceKey.minecraft("fossil"));

    public static final DefaultedRegistryReference<Feature> FREEZE_TOP_LAYER = Features.key(ResourceKey.minecraft("freeze_top_layer"));

    public static final DefaultedRegistryReference<Feature> GEODE = Features.key(ResourceKey.minecraft("geode"));

    public static final DefaultedRegistryReference<Feature> GLOWSTONE_BLOB = Features.key(ResourceKey.minecraft("glowstone_blob"));

    public static final DefaultedRegistryReference<Feature> HUGE_BROWN_MUSHROOM = Features.key(ResourceKey.minecraft("huge_brown_mushroom"));

    public static final DefaultedRegistryReference<Feature> HUGE_FUNGUS = Features.key(ResourceKey.minecraft("huge_fungus"));

    public static final DefaultedRegistryReference<Feature> HUGE_RED_MUSHROOM = Features.key(ResourceKey.minecraft("huge_red_mushroom"));

    public static final DefaultedRegistryReference<Feature> ICE_SPIKE = Features.key(ResourceKey.minecraft("ice_spike"));

    public static final DefaultedRegistryReference<Feature> ICEBERG = Features.key(ResourceKey.minecraft("iceberg"));

    public static final DefaultedRegistryReference<Feature> KELP = Features.key(ResourceKey.minecraft("kelp"));

    public static final DefaultedRegistryReference<Feature> LAKE = Features.key(ResourceKey.minecraft("lake"));

    public static final DefaultedRegistryReference<Feature> LARGE_DRIPSTONE = Features.key(ResourceKey.minecraft("large_dripstone"));

    public static final DefaultedRegistryReference<Feature> MONSTER_ROOM = Features.key(ResourceKey.minecraft("monster_room"));

    public static final DefaultedRegistryReference<Feature> MULTIFACE_GROWTH = Features.key(ResourceKey.minecraft("multiface_growth"));

    public static final DefaultedRegistryReference<Feature> NETHER_FOREST_VEGETATION = Features.key(ResourceKey.minecraft("nether_forest_vegetation"));

    public static final DefaultedRegistryReference<Feature> NETHERRACK_REPLACE_BLOBS = Features.key(ResourceKey.minecraft("netherrack_replace_blobs"));

    public static final DefaultedRegistryReference<Feature> NO_BONEMEAL_FLOWER = Features.key(ResourceKey.minecraft("no_bonemeal_flower"));

    public static final DefaultedRegistryReference<Feature> NO_OP = Features.key(ResourceKey.minecraft("no_op"));

    public static final DefaultedRegistryReference<Feature> ORE = Features.key(ResourceKey.minecraft("ore"));

    public static final DefaultedRegistryReference<Feature> POINTED_DRIPSTONE = Features.key(ResourceKey.minecraft("pointed_dripstone"));

    public static final DefaultedRegistryReference<Feature> RANDOM_BOOLEAN_SELECTOR = Features.key(ResourceKey.minecraft("random_boolean_selector"));

    public static final DefaultedRegistryReference<Feature> RANDOM_PATCH = Features.key(ResourceKey.minecraft("random_patch"));

    public static final DefaultedRegistryReference<Feature> RANDOM_SELECTOR = Features.key(ResourceKey.minecraft("random_selector"));

    public static final DefaultedRegistryReference<Feature> REPLACE_SINGLE_BLOCK = Features.key(ResourceKey.minecraft("replace_single_block"));

    public static final DefaultedRegistryReference<Feature> ROOT_SYSTEM = Features.key(ResourceKey.minecraft("root_system"));

    public static final DefaultedRegistryReference<Feature> SCATTERED_ORE = Features.key(ResourceKey.minecraft("scattered_ore"));

    public static final DefaultedRegistryReference<Feature> SCULK_PATCH = Features.key(ResourceKey.minecraft("sculk_patch"));

    public static final DefaultedRegistryReference<Feature> SEA_PICKLE = Features.key(ResourceKey.minecraft("sea_pickle"));

    public static final DefaultedRegistryReference<Feature> SEAGRASS = Features.key(ResourceKey.minecraft("seagrass"));

    public static final DefaultedRegistryReference<Feature> SIMPLE_BLOCK = Features.key(ResourceKey.minecraft("simple_block"));

    public static final DefaultedRegistryReference<Feature> SIMPLE_RANDOM_SELECTOR = Features.key(ResourceKey.minecraft("simple_random_selector"));

    public static final DefaultedRegistryReference<Feature> SPRING_FEATURE = Features.key(ResourceKey.minecraft("spring_feature"));

    public static final DefaultedRegistryReference<Feature> TREE = Features.key(ResourceKey.minecraft("tree"));

    public static final DefaultedRegistryReference<Feature> TWISTING_VINES = Features.key(ResourceKey.minecraft("twisting_vines"));

    public static final DefaultedRegistryReference<Feature> UNDERWATER_MAGMA = Features.key(ResourceKey.minecraft("underwater_magma"));

    public static final DefaultedRegistryReference<Feature> VEGETATION_PATCH = Features.key(ResourceKey.minecraft("vegetation_patch"));

    public static final DefaultedRegistryReference<Feature> VINES = Features.key(ResourceKey.minecraft("vines"));

    public static final DefaultedRegistryReference<Feature> VOID_START_PLATFORM = Features.key(ResourceKey.minecraft("void_start_platform"));

    public static final DefaultedRegistryReference<Feature> WATERLOGGED_VEGETATION_PATCH = Features.key(ResourceKey.minecraft("waterlogged_vegetation_patch"));

    public static final DefaultedRegistryReference<Feature> WEEPING_VINES = Features.key(ResourceKey.minecraft("weeping_vines"));

    // @formatter:on
    private Features() {
    }

    public static Registry<Feature> registry() {
        return Sponge.server().registry(RegistryTypes.FEATURE);
    }

    private static DefaultedRegistryReference<Feature> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.FEATURE, location).asDefaultedReference(Sponge::server);
    }
}
