/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.feature;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryReference;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.server.ServerWorld;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.WORLD)
public final class PlacedFeatures {

    // @formatter:off
    public static final RegistryReference<PlacedFeature> ACACIA = PlacedFeatures.key(ResourceKey.minecraft("acacia"));

    public static final RegistryReference<PlacedFeature> ACACIA_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("acacia_checked"));

    public static final RegistryReference<PlacedFeature> AMETHYST_GEODE = PlacedFeatures.key(ResourceKey.minecraft("amethyst_geode"));

    public static final RegistryReference<PlacedFeature> BAMBOO = PlacedFeatures.key(ResourceKey.minecraft("bamboo"));

    public static final RegistryReference<PlacedFeature> BAMBOO_LIGHT = PlacedFeatures.key(ResourceKey.minecraft("bamboo_light"));

    public static final RegistryReference<PlacedFeature> BAMBOO_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("bamboo_vegetation"));

    public static final RegistryReference<PlacedFeature> BASALT_BLOBS = PlacedFeatures.key(ResourceKey.minecraft("basalt_blobs"));

    public static final RegistryReference<PlacedFeature> BASALT_PILLAR = PlacedFeatures.key(ResourceKey.minecraft("basalt_pillar"));

    public static final RegistryReference<PlacedFeature> BIRCH_BEES_0002 = PlacedFeatures.key(ResourceKey.minecraft("birch_bees_0002"));

    public static final RegistryReference<PlacedFeature> BIRCH_BEES_002 = PlacedFeatures.key(ResourceKey.minecraft("birch_bees_002"));

    public static final RegistryReference<PlacedFeature> BIRCH_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("birch_checked"));

    public static final RegistryReference<PlacedFeature> BIRCH_TALL = PlacedFeatures.key(ResourceKey.minecraft("birch_tall"));

    public static final RegistryReference<PlacedFeature> BLACKSTONE_BLOBS = PlacedFeatures.key(ResourceKey.minecraft("blackstone_blobs"));

    public static final RegistryReference<PlacedFeature> BLUE_ICE = PlacedFeatures.key(ResourceKey.minecraft("blue_ice"));

    public static final RegistryReference<PlacedFeature> BROWN_MUSHROOM_NETHER = PlacedFeatures.key(ResourceKey.minecraft("brown_mushroom_nether"));

    public static final RegistryReference<PlacedFeature> BROWN_MUSHROOM_NORMAL = PlacedFeatures.key(ResourceKey.minecraft("brown_mushroom_normal"));

    public static final RegistryReference<PlacedFeature> BROWN_MUSHROOM_OLD_GROWTH = PlacedFeatures.key(ResourceKey.minecraft("brown_mushroom_old_growth"));

    public static final RegistryReference<PlacedFeature> BROWN_MUSHROOM_SWAMP = PlacedFeatures.key(ResourceKey.minecraft("brown_mushroom_swamp"));

    public static final RegistryReference<PlacedFeature> BROWN_MUSHROOM_TAIGA = PlacedFeatures.key(ResourceKey.minecraft("brown_mushroom_taiga"));

    public static final RegistryReference<PlacedFeature> CAVE_VINES = PlacedFeatures.key(ResourceKey.minecraft("cave_vines"));

    public static final RegistryReference<PlacedFeature> CHORUS_PLANT = PlacedFeatures.key(ResourceKey.minecraft("chorus_plant"));

    public static final RegistryReference<PlacedFeature> CLASSIC_VINES_CAVE_FEATURE = PlacedFeatures.key(ResourceKey.minecraft("classic_vines_cave_feature"));

    public static final RegistryReference<PlacedFeature> CRIMSON_FOREST_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("crimson_forest_vegetation"));

    public static final RegistryReference<PlacedFeature> CRIMSON_FUNGI = PlacedFeatures.key(ResourceKey.minecraft("crimson_fungi"));

    public static final RegistryReference<PlacedFeature> DARK_FOREST_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("dark_forest_vegetation"));

    public static final RegistryReference<PlacedFeature> DARK_OAK_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("dark_oak_checked"));

    public static final RegistryReference<PlacedFeature> DELTA = PlacedFeatures.key(ResourceKey.minecraft("delta"));

    public static final RegistryReference<PlacedFeature> DESERT_WELL = PlacedFeatures.key(ResourceKey.minecraft("desert_well"));

    public static final RegistryReference<PlacedFeature> DISK_CLAY = PlacedFeatures.key(ResourceKey.minecraft("disk_clay"));

    public static final RegistryReference<PlacedFeature> DISK_GRASS = PlacedFeatures.key(ResourceKey.minecraft("disk_grass"));

    public static final RegistryReference<PlacedFeature> DISK_GRAVEL = PlacedFeatures.key(ResourceKey.minecraft("disk_gravel"));

    public static final RegistryReference<PlacedFeature> DISK_SAND = PlacedFeatures.key(ResourceKey.minecraft("disk_sand"));

    public static final RegistryReference<PlacedFeature> DRIPSTONE_CLUSTER = PlacedFeatures.key(ResourceKey.minecraft("dripstone_cluster"));

    public static final RegistryReference<PlacedFeature> END_GATEWAY_RETURN = PlacedFeatures.key(ResourceKey.minecraft("end_gateway_return"));

    public static final RegistryReference<PlacedFeature> END_ISLAND_DECORATED = PlacedFeatures.key(ResourceKey.minecraft("end_island_decorated"));

    public static final RegistryReference<PlacedFeature> END_SPIKE = PlacedFeatures.key(ResourceKey.minecraft("end_spike"));

    public static final RegistryReference<PlacedFeature> FANCY_OAK_BEES = PlacedFeatures.key(ResourceKey.minecraft("fancy_oak_bees"));

    public static final RegistryReference<PlacedFeature> FANCY_OAK_BEES_0002 = PlacedFeatures.key(ResourceKey.minecraft("fancy_oak_bees_0002"));

    public static final RegistryReference<PlacedFeature> FANCY_OAK_BEES_002 = PlacedFeatures.key(ResourceKey.minecraft("fancy_oak_bees_002"));

    public static final RegistryReference<PlacedFeature> FANCY_OAK_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("fancy_oak_checked"));

    public static final RegistryReference<PlacedFeature> FLOWER_DEFAULT = PlacedFeatures.key(ResourceKey.minecraft("flower_default"));

    public static final RegistryReference<PlacedFeature> FLOWER_FLOWER_FOREST = PlacedFeatures.key(ResourceKey.minecraft("flower_flower_forest"));

    public static final RegistryReference<PlacedFeature> FLOWER_FOREST_FLOWERS = PlacedFeatures.key(ResourceKey.minecraft("flower_forest_flowers"));

    public static final RegistryReference<PlacedFeature> FLOWER_MEADOW = PlacedFeatures.key(ResourceKey.minecraft("flower_meadow"));

    public static final RegistryReference<PlacedFeature> FLOWER_PLAIN = PlacedFeatures.key(ResourceKey.minecraft("flower_plain"));

    public static final RegistryReference<PlacedFeature> FLOWER_PLAINS = PlacedFeatures.key(ResourceKey.minecraft("flower_plains"));

    public static final RegistryReference<PlacedFeature> FLOWER_SWAMP = PlacedFeatures.key(ResourceKey.minecraft("flower_swamp"));

    public static final RegistryReference<PlacedFeature> FLOWER_WARM = PlacedFeatures.key(ResourceKey.minecraft("flower_warm"));

    public static final RegistryReference<PlacedFeature> FOREST_FLOWERS = PlacedFeatures.key(ResourceKey.minecraft("forest_flowers"));

    public static final RegistryReference<PlacedFeature> FOREST_ROCK = PlacedFeatures.key(ResourceKey.minecraft("forest_rock"));

    public static final RegistryReference<PlacedFeature> FOSSIL_LOWER = PlacedFeatures.key(ResourceKey.minecraft("fossil_lower"));

    public static final RegistryReference<PlacedFeature> FOSSIL_UPPER = PlacedFeatures.key(ResourceKey.minecraft("fossil_upper"));

    public static final RegistryReference<PlacedFeature> FREEZE_TOP_LAYER = PlacedFeatures.key(ResourceKey.minecraft("freeze_top_layer"));

    public static final RegistryReference<PlacedFeature> GLOW_LICHEN = PlacedFeatures.key(ResourceKey.minecraft("glow_lichen"));

    public static final RegistryReference<PlacedFeature> GLOWSTONE = PlacedFeatures.key(ResourceKey.minecraft("glowstone"));

    public static final RegistryReference<PlacedFeature> GLOWSTONE_EXTRA = PlacedFeatures.key(ResourceKey.minecraft("glowstone_extra"));

    public static final RegistryReference<PlacedFeature> GRASS_BONEMEAL = PlacedFeatures.key(ResourceKey.minecraft("grass_bonemeal"));

    public static final RegistryReference<PlacedFeature> ICE_PATCH = PlacedFeatures.key(ResourceKey.minecraft("ice_patch"));

    public static final RegistryReference<PlacedFeature> ICE_SPIKE = PlacedFeatures.key(ResourceKey.minecraft("ice_spike"));

    public static final RegistryReference<PlacedFeature> ICEBERG_BLUE = PlacedFeatures.key(ResourceKey.minecraft("iceberg_blue"));

    public static final RegistryReference<PlacedFeature> ICEBERG_PACKED = PlacedFeatures.key(ResourceKey.minecraft("iceberg_packed"));

    public static final RegistryReference<PlacedFeature> JUNGLE_BUSH = PlacedFeatures.key(ResourceKey.minecraft("jungle_bush"));

    public static final RegistryReference<PlacedFeature> JUNGLE_TREE = PlacedFeatures.key(ResourceKey.minecraft("jungle_tree"));

    public static final RegistryReference<PlacedFeature> KELP_COLD = PlacedFeatures.key(ResourceKey.minecraft("kelp_cold"));

    public static final RegistryReference<PlacedFeature> KELP_WARM = PlacedFeatures.key(ResourceKey.minecraft("kelp_warm"));

    public static final RegistryReference<PlacedFeature> LAKE_LAVA_SURFACE = PlacedFeatures.key(ResourceKey.minecraft("lake_lava_surface"));

    public static final RegistryReference<PlacedFeature> LAKE_LAVA_UNDERGROUND = PlacedFeatures.key(ResourceKey.minecraft("lake_lava_underground"));

    public static final RegistryReference<PlacedFeature> LARGE_BASALT_COLUMNS = PlacedFeatures.key(ResourceKey.minecraft("large_basalt_columns"));

    public static final RegistryReference<PlacedFeature> LARGE_DRIPSTONE = PlacedFeatures.key(ResourceKey.minecraft("large_dripstone"));

    public static final RegistryReference<PlacedFeature> LUSH_CAVES_CEILING_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("lush_caves_ceiling_vegetation"));

    public static final RegistryReference<PlacedFeature> LUSH_CAVES_CLAY = PlacedFeatures.key(ResourceKey.minecraft("lush_caves_clay"));

    public static final RegistryReference<PlacedFeature> LUSH_CAVES_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("lush_caves_vegetation"));

    public static final RegistryReference<PlacedFeature> MANGROVE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("mangrove_checked"));

    public static final RegistryReference<PlacedFeature> MEGA_JUNGLE_TREE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("mega_jungle_tree_checked"));

    public static final RegistryReference<PlacedFeature> MEGA_PINE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("mega_pine_checked"));

    public static final RegistryReference<PlacedFeature> MEGA_SPRUCE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("mega_spruce_checked"));

    public static final RegistryReference<PlacedFeature> MONSTER_ROOM = PlacedFeatures.key(ResourceKey.minecraft("monster_room"));

    public static final RegistryReference<PlacedFeature> MONSTER_ROOM_DEEP = PlacedFeatures.key(ResourceKey.minecraft("monster_room_deep"));

    public static final RegistryReference<PlacedFeature> MUSHROOM_ISLAND_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("mushroom_island_vegetation"));

    public static final RegistryReference<PlacedFeature> NETHER_SPROUTS = PlacedFeatures.key(ResourceKey.minecraft("nether_sprouts"));

    public static final RegistryReference<PlacedFeature> OAK = PlacedFeatures.key(ResourceKey.minecraft("oak"));

    public static final RegistryReference<PlacedFeature> OAK_BEES_0002 = PlacedFeatures.key(ResourceKey.minecraft("oak_bees_0002"));

    public static final RegistryReference<PlacedFeature> OAK_BEES_002 = PlacedFeatures.key(ResourceKey.minecraft("oak_bees_002"));

    public static final RegistryReference<PlacedFeature> OAK_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("oak_checked"));

    public static final RegistryReference<PlacedFeature> ORE_ANCIENT_DEBRIS_LARGE = PlacedFeatures.key(ResourceKey.minecraft("ore_ancient_debris_large"));

    public static final RegistryReference<PlacedFeature> ORE_ANDESITE_LOWER = PlacedFeatures.key(ResourceKey.minecraft("ore_andesite_lower"));

    public static final RegistryReference<PlacedFeature> ORE_ANDESITE_UPPER = PlacedFeatures.key(ResourceKey.minecraft("ore_andesite_upper"));

    public static final RegistryReference<PlacedFeature> ORE_BLACKSTONE = PlacedFeatures.key(ResourceKey.minecraft("ore_blackstone"));

    public static final RegistryReference<PlacedFeature> ORE_CLAY = PlacedFeatures.key(ResourceKey.minecraft("ore_clay"));

    public static final RegistryReference<PlacedFeature> ORE_COAL_LOWER = PlacedFeatures.key(ResourceKey.minecraft("ore_coal_lower"));

    public static final RegistryReference<PlacedFeature> ORE_COAL_UPPER = PlacedFeatures.key(ResourceKey.minecraft("ore_coal_upper"));

    public static final RegistryReference<PlacedFeature> ORE_COPPER = PlacedFeatures.key(ResourceKey.minecraft("ore_copper"));

    public static final RegistryReference<PlacedFeature> ORE_COPPER_LARGE = PlacedFeatures.key(ResourceKey.minecraft("ore_copper_large"));

    public static final RegistryReference<PlacedFeature> ORE_DEBRIS_SMALL = PlacedFeatures.key(ResourceKey.minecraft("ore_debris_small"));

    public static final RegistryReference<PlacedFeature> ORE_DIAMOND = PlacedFeatures.key(ResourceKey.minecraft("ore_diamond"));

    public static final RegistryReference<PlacedFeature> ORE_DIAMOND_BURIED = PlacedFeatures.key(ResourceKey.minecraft("ore_diamond_buried"));

    public static final RegistryReference<PlacedFeature> ORE_DIAMOND_LARGE = PlacedFeatures.key(ResourceKey.minecraft("ore_diamond_large"));

    public static final RegistryReference<PlacedFeature> ORE_DIORITE_LOWER = PlacedFeatures.key(ResourceKey.minecraft("ore_diorite_lower"));

    public static final RegistryReference<PlacedFeature> ORE_DIORITE_UPPER = PlacedFeatures.key(ResourceKey.minecraft("ore_diorite_upper"));

    public static final RegistryReference<PlacedFeature> ORE_DIRT = PlacedFeatures.key(ResourceKey.minecraft("ore_dirt"));

    public static final RegistryReference<PlacedFeature> ORE_EMERALD = PlacedFeatures.key(ResourceKey.minecraft("ore_emerald"));

    public static final RegistryReference<PlacedFeature> ORE_GOLD = PlacedFeatures.key(ResourceKey.minecraft("ore_gold"));

    public static final RegistryReference<PlacedFeature> ORE_GOLD_DELTAS = PlacedFeatures.key(ResourceKey.minecraft("ore_gold_deltas"));

    public static final RegistryReference<PlacedFeature> ORE_GOLD_EXTRA = PlacedFeatures.key(ResourceKey.minecraft("ore_gold_extra"));

    public static final RegistryReference<PlacedFeature> ORE_GOLD_LOWER = PlacedFeatures.key(ResourceKey.minecraft("ore_gold_lower"));

    public static final RegistryReference<PlacedFeature> ORE_GOLD_NETHER = PlacedFeatures.key(ResourceKey.minecraft("ore_gold_nether"));

    public static final RegistryReference<PlacedFeature> ORE_GRANITE_LOWER = PlacedFeatures.key(ResourceKey.minecraft("ore_granite_lower"));

    public static final RegistryReference<PlacedFeature> ORE_GRANITE_UPPER = PlacedFeatures.key(ResourceKey.minecraft("ore_granite_upper"));

    public static final RegistryReference<PlacedFeature> ORE_GRAVEL = PlacedFeatures.key(ResourceKey.minecraft("ore_gravel"));

    public static final RegistryReference<PlacedFeature> ORE_GRAVEL_NETHER = PlacedFeatures.key(ResourceKey.minecraft("ore_gravel_nether"));

    public static final RegistryReference<PlacedFeature> ORE_INFESTED = PlacedFeatures.key(ResourceKey.minecraft("ore_infested"));

    public static final RegistryReference<PlacedFeature> ORE_IRON_MIDDLE = PlacedFeatures.key(ResourceKey.minecraft("ore_iron_middle"));

    public static final RegistryReference<PlacedFeature> ORE_IRON_SMALL = PlacedFeatures.key(ResourceKey.minecraft("ore_iron_small"));

    public static final RegistryReference<PlacedFeature> ORE_IRON_UPPER = PlacedFeatures.key(ResourceKey.minecraft("ore_iron_upper"));

    public static final RegistryReference<PlacedFeature> ORE_LAPIS = PlacedFeatures.key(ResourceKey.minecraft("ore_lapis"));

    public static final RegistryReference<PlacedFeature> ORE_LAPIS_BURIED = PlacedFeatures.key(ResourceKey.minecraft("ore_lapis_buried"));

    public static final RegistryReference<PlacedFeature> ORE_MAGMA = PlacedFeatures.key(ResourceKey.minecraft("ore_magma"));

    public static final RegistryReference<PlacedFeature> ORE_QUARTZ_DELTAS = PlacedFeatures.key(ResourceKey.minecraft("ore_quartz_deltas"));

    public static final RegistryReference<PlacedFeature> ORE_QUARTZ_NETHER = PlacedFeatures.key(ResourceKey.minecraft("ore_quartz_nether"));

    public static final RegistryReference<PlacedFeature> ORE_REDSTONE = PlacedFeatures.key(ResourceKey.minecraft("ore_redstone"));

    public static final RegistryReference<PlacedFeature> ORE_REDSTONE_LOWER = PlacedFeatures.key(ResourceKey.minecraft("ore_redstone_lower"));

    public static final RegistryReference<PlacedFeature> ORE_SOUL_SAND = PlacedFeatures.key(ResourceKey.minecraft("ore_soul_sand"));

    public static final RegistryReference<PlacedFeature> ORE_TUFF = PlacedFeatures.key(ResourceKey.minecraft("ore_tuff"));

    public static final RegistryReference<PlacedFeature> PATCH_BERRY_BUSH = PlacedFeatures.key(ResourceKey.minecraft("patch_berry_bush"));

    public static final RegistryReference<PlacedFeature> PATCH_BERRY_COMMON = PlacedFeatures.key(ResourceKey.minecraft("patch_berry_common"));

    public static final RegistryReference<PlacedFeature> PATCH_BERRY_RARE = PlacedFeatures.key(ResourceKey.minecraft("patch_berry_rare"));

    public static final RegistryReference<PlacedFeature> PATCH_CACTUS = PlacedFeatures.key(ResourceKey.minecraft("patch_cactus"));

    public static final RegistryReference<PlacedFeature> PATCH_CACTUS_DECORATED = PlacedFeatures.key(ResourceKey.minecraft("patch_cactus_decorated"));

    public static final RegistryReference<PlacedFeature> PATCH_CACTUS_DESERT = PlacedFeatures.key(ResourceKey.minecraft("patch_cactus_desert"));

    public static final RegistryReference<PlacedFeature> PATCH_CRIMSON_ROOTS = PlacedFeatures.key(ResourceKey.minecraft("patch_crimson_roots"));

    public static final RegistryReference<PlacedFeature> PATCH_DEAD_BUSH = PlacedFeatures.key(ResourceKey.minecraft("patch_dead_bush"));

    public static final RegistryReference<PlacedFeature> PATCH_DEAD_BUSH_2 = PlacedFeatures.key(ResourceKey.minecraft("patch_dead_bush_2"));

    public static final RegistryReference<PlacedFeature> PATCH_DEAD_BUSH_BADLANDS = PlacedFeatures.key(ResourceKey.minecraft("patch_dead_bush_badlands"));

    public static final RegistryReference<PlacedFeature> PATCH_FIRE = PlacedFeatures.key(ResourceKey.minecraft("patch_fire"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_BADLANDS = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_badlands"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_FOREST = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_forest"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_JUNGLE = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_jungle"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_NORMAL = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_normal"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_PLAIN = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_plain"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_SAVANNA = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_savanna"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_TAIGA = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_taiga"));

    public static final RegistryReference<PlacedFeature> PATCH_GRASS_TAIGA_2 = PlacedFeatures.key(ResourceKey.minecraft("patch_grass_taiga_2"));

    public static final RegistryReference<PlacedFeature> PATCH_LARGE_FERN = PlacedFeatures.key(ResourceKey.minecraft("patch_large_fern"));

    public static final RegistryReference<PlacedFeature> PATCH_MELON = PlacedFeatures.key(ResourceKey.minecraft("patch_melon"));

    public static final RegistryReference<PlacedFeature> PATCH_MELON_SPARSE = PlacedFeatures.key(ResourceKey.minecraft("patch_melon_sparse"));

    public static final RegistryReference<PlacedFeature> PATCH_PUMPKIN = PlacedFeatures.key(ResourceKey.minecraft("patch_pumpkin"));

    public static final RegistryReference<PlacedFeature> PATCH_SOUL_FIRE = PlacedFeatures.key(ResourceKey.minecraft("patch_soul_fire"));

    public static final RegistryReference<PlacedFeature> PATCH_SUGAR_CANE = PlacedFeatures.key(ResourceKey.minecraft("patch_sugar_cane"));

    public static final RegistryReference<PlacedFeature> PATCH_SUGAR_CANE_BADLANDS = PlacedFeatures.key(ResourceKey.minecraft("patch_sugar_cane_badlands"));

    public static final RegistryReference<PlacedFeature> PATCH_SUGAR_CANE_DESERT = PlacedFeatures.key(ResourceKey.minecraft("patch_sugar_cane_desert"));

    public static final RegistryReference<PlacedFeature> PATCH_SUGAR_CANE_SWAMP = PlacedFeatures.key(ResourceKey.minecraft("patch_sugar_cane_swamp"));

    public static final RegistryReference<PlacedFeature> PATCH_SUNFLOWER = PlacedFeatures.key(ResourceKey.minecraft("patch_sunflower"));

    public static final RegistryReference<PlacedFeature> PATCH_TAIGA_GRASS = PlacedFeatures.key(ResourceKey.minecraft("patch_taiga_grass"));

    public static final RegistryReference<PlacedFeature> PATCH_TALL_GRASS = PlacedFeatures.key(ResourceKey.minecraft("patch_tall_grass"));

    public static final RegistryReference<PlacedFeature> PATCH_TALL_GRASS_2 = PlacedFeatures.key(ResourceKey.minecraft("patch_tall_grass_2"));

    public static final RegistryReference<PlacedFeature> PATCH_WATERLILY = PlacedFeatures.key(ResourceKey.minecraft("patch_waterlily"));

    public static final RegistryReference<PlacedFeature> PILE_HAY = PlacedFeatures.key(ResourceKey.minecraft("pile_hay"));

    public static final RegistryReference<PlacedFeature> PILE_ICE = PlacedFeatures.key(ResourceKey.minecraft("pile_ice"));

    public static final RegistryReference<PlacedFeature> PILE_MELON = PlacedFeatures.key(ResourceKey.minecraft("pile_melon"));

    public static final RegistryReference<PlacedFeature> PILE_PUMPKIN = PlacedFeatures.key(ResourceKey.minecraft("pile_pumpkin"));

    public static final RegistryReference<PlacedFeature> PILE_SNOW = PlacedFeatures.key(ResourceKey.minecraft("pile_snow"));

    public static final RegistryReference<PlacedFeature> PINE = PlacedFeatures.key(ResourceKey.minecraft("pine"));

    public static final RegistryReference<PlacedFeature> PINE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("pine_checked"));

    public static final RegistryReference<PlacedFeature> PINE_ON_SNOW = PlacedFeatures.key(ResourceKey.minecraft("pine_on_snow"));

    public static final RegistryReference<PlacedFeature> POINTED_DRIPSTONE = PlacedFeatures.key(ResourceKey.minecraft("pointed_dripstone"));

    public static final RegistryReference<PlacedFeature> RED_MUSHROOM_NETHER = PlacedFeatures.key(ResourceKey.minecraft("red_mushroom_nether"));

    public static final RegistryReference<PlacedFeature> RED_MUSHROOM_NORMAL = PlacedFeatures.key(ResourceKey.minecraft("red_mushroom_normal"));

    public static final RegistryReference<PlacedFeature> RED_MUSHROOM_OLD_GROWTH = PlacedFeatures.key(ResourceKey.minecraft("red_mushroom_old_growth"));

    public static final RegistryReference<PlacedFeature> RED_MUSHROOM_SWAMP = PlacedFeatures.key(ResourceKey.minecraft("red_mushroom_swamp"));

    public static final RegistryReference<PlacedFeature> RED_MUSHROOM_TAIGA = PlacedFeatures.key(ResourceKey.minecraft("red_mushroom_taiga"));

    public static final RegistryReference<PlacedFeature> ROOTED_AZALEA_TREE = PlacedFeatures.key(ResourceKey.minecraft("rooted_azalea_tree"));

    public static final RegistryReference<PlacedFeature> SCULK_PATCH_ANCIENT_CITY = PlacedFeatures.key(ResourceKey.minecraft("sculk_patch_ancient_city"));

    public static final RegistryReference<PlacedFeature> SCULK_PATCH_DEEP_DARK = PlacedFeatures.key(ResourceKey.minecraft("sculk_patch_deep_dark"));

    public static final RegistryReference<PlacedFeature> SCULK_VEIN = PlacedFeatures.key(ResourceKey.minecraft("sculk_vein"));

    public static final RegistryReference<PlacedFeature> SEA_PICKLE = PlacedFeatures.key(ResourceKey.minecraft("sea_pickle"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_COLD = PlacedFeatures.key(ResourceKey.minecraft("seagrass_cold"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_DEEP = PlacedFeatures.key(ResourceKey.minecraft("seagrass_deep"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_DEEP_COLD = PlacedFeatures.key(ResourceKey.minecraft("seagrass_deep_cold"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_DEEP_WARM = PlacedFeatures.key(ResourceKey.minecraft("seagrass_deep_warm"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_NORMAL = PlacedFeatures.key(ResourceKey.minecraft("seagrass_normal"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_RIVER = PlacedFeatures.key(ResourceKey.minecraft("seagrass_river"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_SIMPLE = PlacedFeatures.key(ResourceKey.minecraft("seagrass_simple"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_SWAMP = PlacedFeatures.key(ResourceKey.minecraft("seagrass_swamp"));

    public static final RegistryReference<PlacedFeature> SEAGRASS_WARM = PlacedFeatures.key(ResourceKey.minecraft("seagrass_warm"));

    public static final RegistryReference<PlacedFeature> SMALL_BASALT_COLUMNS = PlacedFeatures.key(ResourceKey.minecraft("small_basalt_columns"));

    public static final RegistryReference<PlacedFeature> SPORE_BLOSSOM = PlacedFeatures.key(ResourceKey.minecraft("spore_blossom"));

    public static final RegistryReference<PlacedFeature> SPRING_CLOSED = PlacedFeatures.key(ResourceKey.minecraft("spring_closed"));

    public static final RegistryReference<PlacedFeature> SPRING_CLOSED_DOUBLE = PlacedFeatures.key(ResourceKey.minecraft("spring_closed_double"));

    public static final RegistryReference<PlacedFeature> SPRING_DELTA = PlacedFeatures.key(ResourceKey.minecraft("spring_delta"));

    public static final RegistryReference<PlacedFeature> SPRING_LAVA = PlacedFeatures.key(ResourceKey.minecraft("spring_lava"));

    public static final RegistryReference<PlacedFeature> SPRING_LAVA_FROZEN = PlacedFeatures.key(ResourceKey.minecraft("spring_lava_frozen"));

    public static final RegistryReference<PlacedFeature> SPRING_OPEN = PlacedFeatures.key(ResourceKey.minecraft("spring_open"));

    public static final RegistryReference<PlacedFeature> SPRING_WATER = PlacedFeatures.key(ResourceKey.minecraft("spring_water"));

    public static final RegistryReference<PlacedFeature> SPRUCE = PlacedFeatures.key(ResourceKey.minecraft("spruce"));

    public static final RegistryReference<PlacedFeature> SPRUCE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("spruce_checked"));

    public static final RegistryReference<PlacedFeature> SPRUCE_ON_SNOW = PlacedFeatures.key(ResourceKey.minecraft("spruce_on_snow"));

    public static final RegistryReference<PlacedFeature> SUPER_BIRCH_BEES = PlacedFeatures.key(ResourceKey.minecraft("super_birch_bees"));

    public static final RegistryReference<PlacedFeature> SUPER_BIRCH_BEES_0002 = PlacedFeatures.key(ResourceKey.minecraft("super_birch_bees_0002"));

    public static final RegistryReference<PlacedFeature> TALL_MANGROVE_CHECKED = PlacedFeatures.key(ResourceKey.minecraft("tall_mangrove_checked"));

    public static final RegistryReference<PlacedFeature> TREES_BADLANDS = PlacedFeatures.key(ResourceKey.minecraft("trees_badlands"));

    public static final RegistryReference<PlacedFeature> TREES_BIRCH = PlacedFeatures.key(ResourceKey.minecraft("trees_birch"));

    public static final RegistryReference<PlacedFeature> TREES_BIRCH_AND_OAK = PlacedFeatures.key(ResourceKey.minecraft("trees_birch_and_oak"));

    public static final RegistryReference<PlacedFeature> TREES_FLOWER_FOREST = PlacedFeatures.key(ResourceKey.minecraft("trees_flower_forest"));

    public static final RegistryReference<PlacedFeature> TREES_GROVE = PlacedFeatures.key(ResourceKey.minecraft("trees_grove"));

    public static final RegistryReference<PlacedFeature> TREES_JUNGLE = PlacedFeatures.key(ResourceKey.minecraft("trees_jungle"));

    public static final RegistryReference<PlacedFeature> TREES_MANGROVE = PlacedFeatures.key(ResourceKey.minecraft("trees_mangrove"));

    public static final RegistryReference<PlacedFeature> TREES_MEADOW = PlacedFeatures.key(ResourceKey.minecraft("trees_meadow"));

    public static final RegistryReference<PlacedFeature> TREES_OLD_GROWTH_PINE_TAIGA = PlacedFeatures.key(ResourceKey.minecraft("trees_old_growth_pine_taiga"));

    public static final RegistryReference<PlacedFeature> TREES_OLD_GROWTH_SPRUCE_TAIGA = PlacedFeatures.key(ResourceKey.minecraft("trees_old_growth_spruce_taiga"));

    public static final RegistryReference<PlacedFeature> TREES_PLAINS = PlacedFeatures.key(ResourceKey.minecraft("trees_plains"));

    public static final RegistryReference<PlacedFeature> TREES_SAVANNA = PlacedFeatures.key(ResourceKey.minecraft("trees_savanna"));

    public static final RegistryReference<PlacedFeature> TREES_SNOWY = PlacedFeatures.key(ResourceKey.minecraft("trees_snowy"));

    public static final RegistryReference<PlacedFeature> TREES_SPARSE_JUNGLE = PlacedFeatures.key(ResourceKey.minecraft("trees_sparse_jungle"));

    public static final RegistryReference<PlacedFeature> TREES_SWAMP = PlacedFeatures.key(ResourceKey.minecraft("trees_swamp"));

    public static final RegistryReference<PlacedFeature> TREES_TAIGA = PlacedFeatures.key(ResourceKey.minecraft("trees_taiga"));

    public static final RegistryReference<PlacedFeature> TREES_WATER = PlacedFeatures.key(ResourceKey.minecraft("trees_water"));

    public static final RegistryReference<PlacedFeature> TREES_WINDSWEPT_FOREST = PlacedFeatures.key(ResourceKey.minecraft("trees_windswept_forest"));

    public static final RegistryReference<PlacedFeature> TREES_WINDSWEPT_HILLS = PlacedFeatures.key(ResourceKey.minecraft("trees_windswept_hills"));

    public static final RegistryReference<PlacedFeature> TREES_WINDSWEPT_SAVANNA = PlacedFeatures.key(ResourceKey.minecraft("trees_windswept_savanna"));

    public static final RegistryReference<PlacedFeature> TWISTING_VINES = PlacedFeatures.key(ResourceKey.minecraft("twisting_vines"));

    public static final RegistryReference<PlacedFeature> UNDERWATER_MAGMA = PlacedFeatures.key(ResourceKey.minecraft("underwater_magma"));

    public static final RegistryReference<PlacedFeature> VINES = PlacedFeatures.key(ResourceKey.minecraft("vines"));

    public static final RegistryReference<PlacedFeature> VOID_START_PLATFORM = PlacedFeatures.key(ResourceKey.minecraft("void_start_platform"));

    public static final RegistryReference<PlacedFeature> WARM_OCEAN_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("warm_ocean_vegetation"));

    public static final RegistryReference<PlacedFeature> WARPED_FOREST_VEGETATION = PlacedFeatures.key(ResourceKey.minecraft("warped_forest_vegetation"));

    public static final RegistryReference<PlacedFeature> WARPED_FUNGI = PlacedFeatures.key(ResourceKey.minecraft("warped_fungi"));

    public static final RegistryReference<PlacedFeature> WEEPING_VINES = PlacedFeatures.key(ResourceKey.minecraft("weeping_vines"));

    // @formatter:on
    private PlacedFeatures() {
    }

    public static Registry<PlacedFeature> registry(final ServerWorld world) {
        return world.registry(RegistryTypes.PLACED_FEATURE);
    }

    private static RegistryReference<PlacedFeature> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.PLACED_FEATURE, location).asReference();
    }
}
