/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.gamerule;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class GameRules {

    public static final DefaultedRegistryReference<GameRule<Boolean>> ADVANCE_TIME = GameRules.key(ResourceKey.minecraft("advance_time"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> ADVANCE_WEATHER = GameRules.key(ResourceKey.minecraft("advance_weather"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> ALLOW_ENTERING_NETHER_USING_PORTALS = GameRules.key(ResourceKey.minecraft("allow_entering_nether_using_portals"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> BLOCK_DROPS = GameRules.key(ResourceKey.minecraft("block_drops"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> BLOCK_EXPLOSION_DROP_DECAY = GameRules.key(ResourceKey.minecraft("block_explosion_drop_decay"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> COMMAND_BLOCKS_WORK = GameRules.key(ResourceKey.minecraft("command_blocks_work"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> COMMAND_BLOCK_OUTPUT = GameRules.key(ResourceKey.minecraft("command_block_output"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> DROWNING_DAMAGE = GameRules.key(ResourceKey.minecraft("drowning_damage"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> ELYTRA_MOVEMENT_CHECK = GameRules.key(ResourceKey.minecraft("elytra_movement_check"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> ENDER_PEARLS_VANISH_ON_DEATH = GameRules.key(ResourceKey.minecraft("ender_pearls_vanish_on_death"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> ENTITY_DROPS = GameRules.key(ResourceKey.minecraft("entity_drops"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> FALL_DAMAGE = GameRules.key(ResourceKey.minecraft("fall_damage"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> FIRE_DAMAGE = GameRules.key(ResourceKey.minecraft("fire_damage"));

    public static final DefaultedRegistryReference<GameRule<Integer>> FIRE_SPREAD_RADIUS_AROUND_PLAYER = GameRules.key(ResourceKey.minecraft("fire_spread_radius_around_player"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> FORGIVE_DEAD_PLAYERS = GameRules.key(ResourceKey.minecraft("forgive_dead_players"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> FREEZE_DAMAGE = GameRules.key(ResourceKey.minecraft("freeze_damage"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> GLOBAL_SOUND_EVENTS = GameRules.key(ResourceKey.minecraft("global_sound_events"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> IMMEDIATE_RESPAWN = GameRules.key(ResourceKey.minecraft("immediate_respawn"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> KEEP_INVENTORY = GameRules.key(ResourceKey.minecraft("keep_inventory"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> LAVA_SOURCE_CONVERSION = GameRules.key(ResourceKey.minecraft("lava_source_conversion"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> LIMITED_CRAFTING = GameRules.key(ResourceKey.minecraft("limited_crafting"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> LOCATOR_BAR = GameRules.key(ResourceKey.minecraft("locator_bar"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> LOG_ADMIN_COMMANDS = GameRules.key(ResourceKey.minecraft("log_admin_commands"));

    public static final DefaultedRegistryReference<GameRule<Integer>> MAX_BLOCK_MODIFICATIONS = GameRules.key(ResourceKey.minecraft("max_block_modifications"));

    public static final DefaultedRegistryReference<GameRule<Integer>> MAX_COMMAND_FORKS = GameRules.key(ResourceKey.minecraft("max_command_forks"));

    public static final DefaultedRegistryReference<GameRule<Integer>> MAX_COMMAND_SEQUENCE_LENGTH = GameRules.key(ResourceKey.minecraft("max_command_sequence_length"));

    public static final DefaultedRegistryReference<GameRule<Integer>> MAX_ENTITY_CRAMMING = GameRules.key(ResourceKey.minecraft("max_entity_cramming"));

    public static final DefaultedRegistryReference<GameRule<Integer>> MAX_MINECART_SPEED = GameRules.key(ResourceKey.minecraft("max_minecart_speed"));

    public static final DefaultedRegistryReference<GameRule<Integer>> MAX_SNOW_ACCUMULATION_HEIGHT = GameRules.key(ResourceKey.minecraft("max_snow_accumulation_height"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> MOB_DROPS = GameRules.key(ResourceKey.minecraft("mob_drops"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> MOB_EXPLOSION_DROP_DECAY = GameRules.key(ResourceKey.minecraft("mob_explosion_drop_decay"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> MOB_GRIEFING = GameRules.key(ResourceKey.minecraft("mob_griefing"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> NATURAL_HEALTH_REGENERATION = GameRules.key(ResourceKey.minecraft("natural_health_regeneration"));

    public static final DefaultedRegistryReference<GameRule<Integer>> PLAYERS_NETHER_PORTAL_CREATIVE_DELAY = GameRules.key(ResourceKey.minecraft("players_nether_portal_creative_delay"));

    public static final DefaultedRegistryReference<GameRule<Integer>> PLAYERS_NETHER_PORTAL_DEFAULT_DELAY = GameRules.key(ResourceKey.minecraft("players_nether_portal_default_delay"));

    public static final DefaultedRegistryReference<GameRule<Integer>> PLAYERS_SLEEPING_PERCENTAGE = GameRules.key(ResourceKey.minecraft("players_sleeping_percentage"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> PLAYER_MOVEMENT_CHECK = GameRules.key(ResourceKey.minecraft("player_movement_check"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> PROJECTILES_CAN_BREAK_BLOCKS = GameRules.key(ResourceKey.minecraft("projectiles_can_break_blocks"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> PVP = GameRules.key(ResourceKey.minecraft("pvp"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> RAIDS = GameRules.key(ResourceKey.minecraft("raids"));

    public static final DefaultedRegistryReference<GameRule<Integer>> RANDOM_TICK_SPEED = GameRules.key(ResourceKey.minecraft("random_tick_speed"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> REDUCED_DEBUG_INFO = GameRules.key(ResourceKey.minecraft("reduced_debug_info"));

    public static final DefaultedRegistryReference<GameRule<Integer>> RESPAWN_RADIUS = GameRules.key(ResourceKey.minecraft("respawn_radius"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SEND_COMMAND_FEEDBACK = GameRules.key(ResourceKey.minecraft("send_command_feedback"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SHOW_ADVANCEMENT_MESSAGES = GameRules.key(ResourceKey.minecraft("show_advancement_messages"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SHOW_DEATH_MESSAGES = GameRules.key(ResourceKey.minecraft("show_death_messages"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWNER_BLOCKS_WORK = GameRules.key(ResourceKey.minecraft("spawner_blocks_work"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWN_MOBS = GameRules.key(ResourceKey.minecraft("spawn_mobs"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWN_MONSTERS = GameRules.key(ResourceKey.minecraft("spawn_monsters"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWN_PATROLS = GameRules.key(ResourceKey.minecraft("spawn_patrols"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWN_PHANTOMS = GameRules.key(ResourceKey.minecraft("spawn_phantoms"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWN_WANDERING_TRADERS = GameRules.key(ResourceKey.minecraft("spawn_wandering_traders"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPAWN_WARDENS = GameRules.key(ResourceKey.minecraft("spawn_wardens"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPECTATORS_GENERATE_CHUNKS = GameRules.key(ResourceKey.minecraft("spectators_generate_chunks"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> SPREAD_VINES = GameRules.key(ResourceKey.minecraft("spread_vines"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> TNT_EXPLODES = GameRules.key(ResourceKey.minecraft("tnt_explodes"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> TNT_EXPLOSION_DROP_DECAY = GameRules.key(ResourceKey.minecraft("tnt_explosion_drop_decay"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> UNIVERSAL_ANGER = GameRules.key(ResourceKey.minecraft("universal_anger"));

    public static final DefaultedRegistryReference<GameRule<Boolean>> WATER_SOURCE_CONVERSION = GameRules.key(ResourceKey.minecraft("water_source_conversion"));

    private GameRules() {
    }

    public static Registry<GameRule<?>> registry() {
        return Sponge.game().registry(RegistryTypes.GAME_RULE);
    }

    private static <T> DefaultedRegistryReference<GameRule<T>> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.GAME_RULE, location).asDefaultedReference(Sponge::game);
    }
}
