/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.state;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
public final class IntegerStateProperties {

    private IntegerStateProperties() {
    }

    public static IntegerStateProperty property_AGE_1() {
        return IntegerStateProperty.of("AGE_1");
    }

    public static IntegerStateProperty property_AGE_15() {
        return IntegerStateProperty.of("AGE_15");
    }

    public static IntegerStateProperty property_AGE_2() {
        return IntegerStateProperty.of("AGE_2");
    }

    public static IntegerStateProperty property_AGE_25() {
        return IntegerStateProperty.of("AGE_25");
    }

    public static IntegerStateProperty property_AGE_3() {
        return IntegerStateProperty.of("AGE_3");
    }

    public static IntegerStateProperty property_AGE_4() {
        return IntegerStateProperty.of("AGE_4");
    }

    public static IntegerStateProperty property_AGE_5() {
        return IntegerStateProperty.of("AGE_5");
    }

    public static IntegerStateProperty property_AGE_7() {
        return IntegerStateProperty.of("AGE_7");
    }

    public static IntegerStateProperty property_BITES() {
        return IntegerStateProperty.of("BITES");
    }

    public static IntegerStateProperty property_CANDLES() {
        return IntegerStateProperty.of("CANDLES");
    }

    public static IntegerStateProperty property_DELAY() {
        return IntegerStateProperty.of("DELAY");
    }

    public static IntegerStateProperty property_DISTANCE() {
        return IntegerStateProperty.of("DISTANCE");
    }

    public static IntegerStateProperty property_DUSTED() {
        return IntegerStateProperty.of("DUSTED");
    }

    public static IntegerStateProperty property_EGGS() {
        return IntegerStateProperty.of("EGGS");
    }

    public static IntegerStateProperty property_FLOWER_AMOUNT() {
        return IntegerStateProperty.of("FLOWER_AMOUNT");
    }

    public static IntegerStateProperty property_HATCH() {
        return IntegerStateProperty.of("HATCH");
    }

    public static IntegerStateProperty property_LAYERS() {
        return IntegerStateProperty.of("LAYERS");
    }

    public static IntegerStateProperty property_LEVEL() {
        return IntegerStateProperty.of("LEVEL");
    }

    public static IntegerStateProperty property_LEVEL_CAULDRON() {
        return IntegerStateProperty.of("LEVEL_CAULDRON");
    }

    public static IntegerStateProperty property_LEVEL_COMPOSTER() {
        return IntegerStateProperty.of("LEVEL_COMPOSTER");
    }

    public static IntegerStateProperty property_LEVEL_HONEY() {
        return IntegerStateProperty.of("LEVEL_HONEY");
    }

    public static IntegerStateProperty property_MOISTURE() {
        return IntegerStateProperty.of("MOISTURE");
    }

    public static IntegerStateProperty property_NOTE() {
        return IntegerStateProperty.of("NOTE");
    }

    public static IntegerStateProperty property_PICKLES() {
        return IntegerStateProperty.of("PICKLES");
    }

    public static IntegerStateProperty property_POWER() {
        return IntegerStateProperty.of("POWER");
    }

    public static IntegerStateProperty property_RESPAWN_ANCHOR_CHARGES() {
        return IntegerStateProperty.of("RESPAWN_ANCHOR_CHARGES");
    }

    public static IntegerStateProperty property_ROTATION_16() {
        return IntegerStateProperty.of("ROTATION_16");
    }

    public static IntegerStateProperty property_STABILITY_DISTANCE() {
        return IntegerStateProperty.of("STABILITY_DISTANCE");
    }

    public static IntegerStateProperty property_STAGE() {
        return IntegerStateProperty.of("STAGE");
    }
}
