/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.entity.attribute.type;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class AttributeTypes {

    public static final DefaultedRegistryReference<RangedAttributeType> ARMOR = AttributeTypes.key(ResourceKey.minecraft("armor"));

    public static final DefaultedRegistryReference<RangedAttributeType> ARMOR_TOUGHNESS = AttributeTypes.key(ResourceKey.minecraft("armor_toughness"));

    public static final DefaultedRegistryReference<RangedAttributeType> ATTACK_DAMAGE = AttributeTypes.key(ResourceKey.minecraft("attack_damage"));

    public static final DefaultedRegistryReference<RangedAttributeType> ATTACK_KNOCKBACK = AttributeTypes.key(ResourceKey.minecraft("attack_knockback"));

    public static final DefaultedRegistryReference<RangedAttributeType> ATTACK_SPEED = AttributeTypes.key(ResourceKey.minecraft("attack_speed"));

    public static final DefaultedRegistryReference<RangedAttributeType> BLOCK_BREAK_SPEED = AttributeTypes.key(ResourceKey.minecraft("block_break_speed"));

    public static final DefaultedRegistryReference<RangedAttributeType> BLOCK_INTERACTION_RANGE = AttributeTypes.key(ResourceKey.minecraft("block_interaction_range"));

    public static final DefaultedRegistryReference<RangedAttributeType> BURNING_TIME = AttributeTypes.key(ResourceKey.minecraft("burning_time"));

    public static final DefaultedRegistryReference<RangedAttributeType> ENTITY_INTERACTION_RANGE = AttributeTypes.key(ResourceKey.minecraft("entity_interaction_range"));

    public static final DefaultedRegistryReference<RangedAttributeType> EXPLOSION_KNOCKBACK_RESISTANCE = AttributeTypes.key(ResourceKey.minecraft("explosion_knockback_resistance"));

    public static final DefaultedRegistryReference<RangedAttributeType> FALL_DAMAGE_MULTIPLIER = AttributeTypes.key(ResourceKey.minecraft("fall_damage_multiplier"));

    public static final DefaultedRegistryReference<RangedAttributeType> FLYING_SPEED = AttributeTypes.key(ResourceKey.minecraft("flying_speed"));

    public static final DefaultedRegistryReference<RangedAttributeType> FOLLOW_RANGE = AttributeTypes.key(ResourceKey.minecraft("follow_range"));

    public static final DefaultedRegistryReference<RangedAttributeType> GRAVITY = AttributeTypes.key(ResourceKey.minecraft("gravity"));

    public static final DefaultedRegistryReference<RangedAttributeType> JUMP_STRENGTH = AttributeTypes.key(ResourceKey.minecraft("jump_strength"));

    public static final DefaultedRegistryReference<RangedAttributeType> KNOCKBACK_RESISTANCE = AttributeTypes.key(ResourceKey.minecraft("knockback_resistance"));

    public static final DefaultedRegistryReference<RangedAttributeType> LUCK = AttributeTypes.key(ResourceKey.minecraft("luck"));

    public static final DefaultedRegistryReference<RangedAttributeType> MAX_ABSORPTION = AttributeTypes.key(ResourceKey.minecraft("max_absorption"));

    public static final DefaultedRegistryReference<RangedAttributeType> MAX_HEALTH = AttributeTypes.key(ResourceKey.minecraft("max_health"));

    public static final DefaultedRegistryReference<RangedAttributeType> MINING_EFFICIENCY = AttributeTypes.key(ResourceKey.minecraft("mining_efficiency"));

    public static final DefaultedRegistryReference<RangedAttributeType> MOVEMENT_EFFICIENCY = AttributeTypes.key(ResourceKey.minecraft("movement_efficiency"));

    public static final DefaultedRegistryReference<RangedAttributeType> MOVEMENT_SPEED = AttributeTypes.key(ResourceKey.minecraft("movement_speed"));

    public static final DefaultedRegistryReference<RangedAttributeType> OXYGEN_BONUS = AttributeTypes.key(ResourceKey.minecraft("oxygen_bonus"));

    public static final DefaultedRegistryReference<RangedAttributeType> SAFE_FALL_DISTANCE = AttributeTypes.key(ResourceKey.minecraft("safe_fall_distance"));

    public static final DefaultedRegistryReference<RangedAttributeType> SCALE = AttributeTypes.key(ResourceKey.minecraft("scale"));

    public static final DefaultedRegistryReference<RangedAttributeType> SNEAKING_SPEED = AttributeTypes.key(ResourceKey.minecraft("sneaking_speed"));

    public static final DefaultedRegistryReference<RangedAttributeType> SPAWN_REINFORCEMENTS = AttributeTypes.key(ResourceKey.minecraft("spawn_reinforcements"));

    public static final DefaultedRegistryReference<RangedAttributeType> STEP_HEIGHT = AttributeTypes.key(ResourceKey.minecraft("step_height"));

    public static final DefaultedRegistryReference<RangedAttributeType> SUBMERGED_MINING_SPEED = AttributeTypes.key(ResourceKey.minecraft("submerged_mining_speed"));

    public static final DefaultedRegistryReference<RangedAttributeType> SWEEPING_DAMAGE_RATIO = AttributeTypes.key(ResourceKey.minecraft("sweeping_damage_ratio"));

    public static final DefaultedRegistryReference<RangedAttributeType> TEMPT_RANGE = AttributeTypes.key(ResourceKey.minecraft("tempt_range"));

    public static final DefaultedRegistryReference<RangedAttributeType> WATER_MOVEMENT_EFFICIENCY = AttributeTypes.key(ResourceKey.minecraft("water_movement_efficiency"));

    private AttributeTypes() {
    }

    public static Registry<AttributeType> registry() {
        return Sponge.game().registry(RegistryTypes.ATTRIBUTE_TYPE);
    }

    private static DefaultedRegistryReference<RangedAttributeType> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.ATTRIBUTE_TYPE, location).asDefaultedReference(Sponge::game);
    }
}
