/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.event.cause.entity.damage;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class DamageTypes {

    public static final DefaultedRegistryReference<DamageType> ARROW = DamageTypes.key(ResourceKey.minecraft("arrow"));

    public static final DefaultedRegistryReference<DamageType> BAD_RESPAWN_POINT = DamageTypes.key(ResourceKey.minecraft("bad_respawn_point"));

    public static final DefaultedRegistryReference<DamageType> CACTUS = DamageTypes.key(ResourceKey.minecraft("cactus"));

    public static final DefaultedRegistryReference<DamageType> CAMPFIRE = DamageTypes.key(ResourceKey.minecraft("campfire"));

    public static final DefaultedRegistryReference<DamageType> CRAMMING = DamageTypes.key(ResourceKey.minecraft("cramming"));

    public static final DefaultedRegistryReference<DamageType> DRAGON_BREATH = DamageTypes.key(ResourceKey.minecraft("dragon_breath"));

    public static final DefaultedRegistryReference<DamageType> DROWN = DamageTypes.key(ResourceKey.minecraft("drown"));

    public static final DefaultedRegistryReference<DamageType> DRY_OUT = DamageTypes.key(ResourceKey.minecraft("dry_out"));

    public static final DefaultedRegistryReference<DamageType> ENDER_PEARL = DamageTypes.key(ResourceKey.minecraft("ender_pearl"));

    public static final DefaultedRegistryReference<DamageType> EXPLOSION = DamageTypes.key(ResourceKey.minecraft("explosion"));

    public static final DefaultedRegistryReference<DamageType> FALL = DamageTypes.key(ResourceKey.minecraft("fall"));

    public static final DefaultedRegistryReference<DamageType> FALLING_ANVIL = DamageTypes.key(ResourceKey.minecraft("falling_anvil"));

    public static final DefaultedRegistryReference<DamageType> FALLING_BLOCK = DamageTypes.key(ResourceKey.minecraft("falling_block"));

    public static final DefaultedRegistryReference<DamageType> FALLING_STALACTITE = DamageTypes.key(ResourceKey.minecraft("falling_stalactite"));

    public static final DefaultedRegistryReference<DamageType> FIREBALL = DamageTypes.key(ResourceKey.minecraft("fireball"));

    public static final DefaultedRegistryReference<DamageType> FIREWORKS = DamageTypes.key(ResourceKey.minecraft("fireworks"));

    public static final DefaultedRegistryReference<DamageType> FLY_INTO_WALL = DamageTypes.key(ResourceKey.minecraft("fly_into_wall"));

    public static final DefaultedRegistryReference<DamageType> FREEZE = DamageTypes.key(ResourceKey.minecraft("freeze"));

    public static final DefaultedRegistryReference<DamageType> GENERIC = DamageTypes.key(ResourceKey.minecraft("generic"));

    public static final DefaultedRegistryReference<DamageType> GENERIC_KILL = DamageTypes.key(ResourceKey.minecraft("generic_kill"));

    public static final DefaultedRegistryReference<DamageType> HOT_FLOOR = DamageTypes.key(ResourceKey.minecraft("hot_floor"));

    public static final DefaultedRegistryReference<DamageType> INDIRECT_MAGIC = DamageTypes.key(ResourceKey.minecraft("indirect_magic"));

    public static final DefaultedRegistryReference<DamageType> IN_FIRE = DamageTypes.key(ResourceKey.minecraft("in_fire"));

    public static final DefaultedRegistryReference<DamageType> IN_WALL = DamageTypes.key(ResourceKey.minecraft("in_wall"));

    public static final DefaultedRegistryReference<DamageType> LAVA = DamageTypes.key(ResourceKey.minecraft("lava"));

    public static final DefaultedRegistryReference<DamageType> LIGHTNING_BOLT = DamageTypes.key(ResourceKey.minecraft("lightning_bolt"));

    public static final DefaultedRegistryReference<DamageType> MACE_SMASH = DamageTypes.key(ResourceKey.minecraft("mace_smash"));

    public static final DefaultedRegistryReference<DamageType> MAGIC = DamageTypes.key(ResourceKey.minecraft("magic"));

    public static final DefaultedRegistryReference<DamageType> MOB_ATTACK = DamageTypes.key(ResourceKey.minecraft("mob_attack"));

    public static final DefaultedRegistryReference<DamageType> MOB_ATTACK_NO_AGGRO = DamageTypes.key(ResourceKey.minecraft("mob_attack_no_aggro"));

    public static final DefaultedRegistryReference<DamageType> MOB_PROJECTILE = DamageTypes.key(ResourceKey.minecraft("mob_projectile"));

    public static final DefaultedRegistryReference<DamageType> ON_FIRE = DamageTypes.key(ResourceKey.minecraft("on_fire"));

    public static final DefaultedRegistryReference<DamageType> OUTSIDE_BORDER = DamageTypes.key(ResourceKey.minecraft("outside_border"));

    public static final DefaultedRegistryReference<DamageType> OUT_OF_WORLD = DamageTypes.key(ResourceKey.minecraft("out_of_world"));

    public static final DefaultedRegistryReference<DamageType> PLAYER_ATTACK = DamageTypes.key(ResourceKey.minecraft("player_attack"));

    public static final DefaultedRegistryReference<DamageType> PLAYER_EXPLOSION = DamageTypes.key(ResourceKey.minecraft("player_explosion"));

    public static final DefaultedRegistryReference<DamageType> SONIC_BOOM = DamageTypes.key(ResourceKey.minecraft("sonic_boom"));

    public static final DefaultedRegistryReference<DamageType> SPIT = DamageTypes.key(ResourceKey.minecraft("spit"));

    public static final DefaultedRegistryReference<DamageType> STALAGMITE = DamageTypes.key(ResourceKey.minecraft("stalagmite"));

    public static final DefaultedRegistryReference<DamageType> STARVE = DamageTypes.key(ResourceKey.minecraft("starve"));

    public static final DefaultedRegistryReference<DamageType> STING = DamageTypes.key(ResourceKey.minecraft("sting"));

    public static final DefaultedRegistryReference<DamageType> SWEET_BERRY_BUSH = DamageTypes.key(ResourceKey.minecraft("sweet_berry_bush"));

    public static final DefaultedRegistryReference<DamageType> THORNS = DamageTypes.key(ResourceKey.minecraft("thorns"));

    public static final DefaultedRegistryReference<DamageType> THROWN = DamageTypes.key(ResourceKey.minecraft("thrown"));

    public static final DefaultedRegistryReference<DamageType> TRIDENT = DamageTypes.key(ResourceKey.minecraft("trident"));

    public static final DefaultedRegistryReference<DamageType> UNATTRIBUTED_FIREBALL = DamageTypes.key(ResourceKey.minecraft("unattributed_fireball"));

    public static final DefaultedRegistryReference<DamageType> WIND_CHARGE = DamageTypes.key(ResourceKey.minecraft("wind_charge"));

    public static final DefaultedRegistryReference<DamageType> WITHER = DamageTypes.key(ResourceKey.minecraft("wither"));

    public static final DefaultedRegistryReference<DamageType> WITHER_SKULL = DamageTypes.key(ResourceKey.minecraft("wither_skull"));

    private DamageTypes() {
    }

    public static Registry<DamageType> registry() {
        return Sponge.server().registry(RegistryTypes.DAMAGE_TYPE);
    }

    private static DefaultedRegistryReference<DamageType> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.DAMAGE_TYPE, location).asDefaultedReference(Sponge::server);
    }
}
