/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.map.decoration;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class MapDecorationTypes {

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_BLACK = MapDecorationTypes.key(ResourceKey.minecraft("banner_black"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_BLUE = MapDecorationTypes.key(ResourceKey.minecraft("banner_blue"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_BROWN = MapDecorationTypes.key(ResourceKey.minecraft("banner_brown"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_CYAN = MapDecorationTypes.key(ResourceKey.minecraft("banner_cyan"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_GRAY = MapDecorationTypes.key(ResourceKey.minecraft("banner_gray"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_GREEN = MapDecorationTypes.key(ResourceKey.minecraft("banner_green"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_LIGHT_BLUE = MapDecorationTypes.key(ResourceKey.minecraft("banner_light_blue"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_LIGHT_GRAY = MapDecorationTypes.key(ResourceKey.minecraft("banner_light_gray"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_LIME = MapDecorationTypes.key(ResourceKey.minecraft("banner_lime"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_MAGENTA = MapDecorationTypes.key(ResourceKey.minecraft("banner_magenta"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_ORANGE = MapDecorationTypes.key(ResourceKey.minecraft("banner_orange"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_PINK = MapDecorationTypes.key(ResourceKey.minecraft("banner_pink"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_PURPLE = MapDecorationTypes.key(ResourceKey.minecraft("banner_purple"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_RED = MapDecorationTypes.key(ResourceKey.minecraft("banner_red"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_WHITE = MapDecorationTypes.key(ResourceKey.minecraft("banner_white"));

    public static final DefaultedRegistryReference<MapDecorationType> BANNER_YELLOW = MapDecorationTypes.key(ResourceKey.minecraft("banner_yellow"));

    public static final DefaultedRegistryReference<MapDecorationType> BLUE_MARKER = MapDecorationTypes.key(ResourceKey.minecraft("blue_marker"));

    public static final DefaultedRegistryReference<MapDecorationType> FRAME = MapDecorationTypes.key(ResourceKey.minecraft("frame"));

    public static final DefaultedRegistryReference<MapDecorationType> JUNGLE_TEMPLE = MapDecorationTypes.key(ResourceKey.minecraft("jungle_temple"));

    public static final DefaultedRegistryReference<MapDecorationType> MANSION = MapDecorationTypes.key(ResourceKey.minecraft("mansion"));

    public static final DefaultedRegistryReference<MapDecorationType> MONUMENT = MapDecorationTypes.key(ResourceKey.minecraft("monument"));

    public static final DefaultedRegistryReference<MapDecorationType> PLAYER = MapDecorationTypes.key(ResourceKey.minecraft("player"));

    public static final DefaultedRegistryReference<MapDecorationType> PLAYER_OFF_LIMITS = MapDecorationTypes.key(ResourceKey.minecraft("player_off_limits"));

    public static final DefaultedRegistryReference<MapDecorationType> PLAYER_OFF_MAP = MapDecorationTypes.key(ResourceKey.minecraft("player_off_map"));

    public static final DefaultedRegistryReference<MapDecorationType> RED_MARKER = MapDecorationTypes.key(ResourceKey.minecraft("red_marker"));

    public static final DefaultedRegistryReference<MapDecorationType> RED_X = MapDecorationTypes.key(ResourceKey.minecraft("red_x"));

    public static final DefaultedRegistryReference<MapDecorationType> SWAMP_HUT = MapDecorationTypes.key(ResourceKey.minecraft("swamp_hut"));

    public static final DefaultedRegistryReference<MapDecorationType> TARGET_POINT = MapDecorationTypes.key(ResourceKey.minecraft("target_point"));

    public static final DefaultedRegistryReference<MapDecorationType> TARGET_X = MapDecorationTypes.key(ResourceKey.minecraft("target_x"));

    public static final DefaultedRegistryReference<MapDecorationType> TRIAL_CHAMBERS = MapDecorationTypes.key(ResourceKey.minecraft("trial_chambers"));

    public static final DefaultedRegistryReference<MapDecorationType> VILLAGE_DESERT = MapDecorationTypes.key(ResourceKey.minecraft("village_desert"));

    public static final DefaultedRegistryReference<MapDecorationType> VILLAGE_PLAINS = MapDecorationTypes.key(ResourceKey.minecraft("village_plains"));

    public static final DefaultedRegistryReference<MapDecorationType> VILLAGE_SAVANNA = MapDecorationTypes.key(ResourceKey.minecraft("village_savanna"));

    public static final DefaultedRegistryReference<MapDecorationType> VILLAGE_SNOWY = MapDecorationTypes.key(ResourceKey.minecraft("village_snowy"));

    public static final DefaultedRegistryReference<MapDecorationType> VILLAGE_TAIGA = MapDecorationTypes.key(ResourceKey.minecraft("village_taiga"));

    private MapDecorationTypes() {
    }

    public static Registry<MapDecorationType> registry() {
        return Sponge.game().registry(RegistryTypes.MAP_DECORATION_TYPE);
    }

    private static DefaultedRegistryReference<MapDecorationType> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.MAP_DECORATION_TYPE, location).asDefaultedReference(Sponge::game);
    }
}
