/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.tag;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.data.type.BannerPatternShape;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class BannerPatternShapeTags {

    public static final DefaultedTag<BannerPatternShape> NO_ITEM_REQUIRED = BannerPatternShapeTags.key(ResourceKey.minecraft("no_item_required"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_BORDURE_INDENTED = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/bordure_indented"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_CREEPER = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/creeper"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_FIELD_MASONED = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/field_masoned"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_FLOW = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/flow"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_FLOWER = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/flower"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_GLOBE = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/globe"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_GUSTER = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/guster"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_MOJANG = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/mojang"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_PIGLIN = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/piglin"));

    public static final DefaultedTag<BannerPatternShape> PATTERN_ITEM_SKULL = BannerPatternShapeTags.key(ResourceKey.minecraft("pattern_item/skull"));

    private BannerPatternShapeTags() {
    }

    private static DefaultedTag<BannerPatternShape> key(final ResourceKey key) {
        return DefaultedTag.of(RegistryTypes.BANNER_PATTERN_SHAPE, key);
    }
}
