/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.tag;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.block.BlockType;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class BlockTypeTags {

    public static final DefaultedTag<BlockType> ACACIA_LOGS = BlockTypeTags.key(ResourceKey.minecraft("acacia_logs"));

    public static final DefaultedTag<BlockType> AIR = BlockTypeTags.key(ResourceKey.minecraft("air"));

    public static final DefaultedTag<BlockType> ALL_HANGING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("all_hanging_signs"));

    public static final DefaultedTag<BlockType> ALL_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("all_signs"));

    public static final DefaultedTag<BlockType> ANCIENT_CITY_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("ancient_city_replaceable"));

    public static final DefaultedTag<BlockType> ANIMALS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("animals_spawnable_on"));

    public static final DefaultedTag<BlockType> ANVIL = BlockTypeTags.key(ResourceKey.minecraft("anvil"));

    public static final DefaultedTag<BlockType> ARMADILLO_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("armadillo_spawnable_on"));

    public static final DefaultedTag<BlockType> AXOLOTLS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("axolotls_spawnable_on"));

    public static final DefaultedTag<BlockType> AZALEA_GROWS_ON = BlockTypeTags.key(ResourceKey.minecraft("azalea_grows_on"));

    public static final DefaultedTag<BlockType> AZALEA_ROOT_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("azalea_root_replaceable"));

    public static final DefaultedTag<BlockType> BADLANDS_TERRACOTTA = BlockTypeTags.key(ResourceKey.minecraft("badlands_terracotta"));

    public static final DefaultedTag<BlockType> BAMBOO_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("bamboo_blocks"));

    public static final DefaultedTag<BlockType> BANNERS = BlockTypeTags.key(ResourceKey.minecraft("banners"));

    public static final DefaultedTag<BlockType> BARS = BlockTypeTags.key(ResourceKey.minecraft("bars"));

    public static final DefaultedTag<BlockType> BASE_STONE_NETHER = BlockTypeTags.key(ResourceKey.minecraft("base_stone_nether"));

    public static final DefaultedTag<BlockType> BASE_STONE_OVERWORLD = BlockTypeTags.key(ResourceKey.minecraft("base_stone_overworld"));

    public static final DefaultedTag<BlockType> BATS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("bats_spawnable_on"));

    public static final DefaultedTag<BlockType> BEACON_BASE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("beacon_base_blocks"));

    public static final DefaultedTag<BlockType> BEDS = BlockTypeTags.key(ResourceKey.minecraft("beds"));

    public static final DefaultedTag<BlockType> BEE_ATTRACTIVE = BlockTypeTags.key(ResourceKey.minecraft("bee_attractive"));

    public static final DefaultedTag<BlockType> BEE_GROWABLES = BlockTypeTags.key(ResourceKey.minecraft("bee_growables"));

    public static final DefaultedTag<BlockType> BEEHIVES = BlockTypeTags.key(ResourceKey.minecraft("beehives"));

    public static final DefaultedTag<BlockType> BENEATH_BAMBOO_PODZOL_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("beneath_bamboo_podzol_replaceable"));

    public static final DefaultedTag<BlockType> BENEATH_TREE_PODZOL_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("beneath_tree_podzol_replaceable"));

    public static final DefaultedTag<BlockType> BIRCH_LOGS = BlockTypeTags.key(ResourceKey.minecraft("birch_logs"));

    public static final DefaultedTag<BlockType> BLOCKS_DOLPHIN_JUMP = BlockTypeTags.key(ResourceKey.minecraft("blocks_dolphin_jump"));

    public static final DefaultedTag<BlockType> BLOCKS_FLUID_FLOW = BlockTypeTags.key(ResourceKey.minecraft("blocks_fluid_flow"));

    public static final DefaultedTag<BlockType> BLOCKS_LAVA_FIRE_SPREAD = BlockTypeTags.key(ResourceKey.minecraft("blocks_lava_fire_spread"));

    public static final DefaultedTag<BlockType> BLOCKS_MOTION = BlockTypeTags.key(ResourceKey.minecraft("blocks_motion"));

    public static final DefaultedTag<BlockType> BLOCKS_MOTION_IN_HEIGHTMAP = BlockTypeTags.key(ResourceKey.minecraft("blocks_motion_in_heightmap"));

    public static final DefaultedTag<BlockType> BLOCKS_MOTION_IN_HEIGHTMAP_NO_LEAVES = BlockTypeTags.key(ResourceKey.minecraft("blocks_motion_in_heightmap_no_leaves"));

    public static final DefaultedTag<BlockType> BLOCKS_MOTION_NO_LEAVES = BlockTypeTags.key(ResourceKey.minecraft("blocks_motion_no_leaves"));

    public static final DefaultedTag<BlockType> BLOCKS_WIND_CHARGE_EXPLOSIONS = BlockTypeTags.key(ResourceKey.minecraft("blocks_wind_charge_explosions"));

    public static final DefaultedTag<BlockType> BUTTONS = BlockTypeTags.key(ResourceKey.minecraft("buttons"));

    public static final DefaultedTag<BlockType> CAMEL_SAND_STEP_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("camel_sand_step_sound_blocks"));

    public static final DefaultedTag<BlockType> CAMELS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("camels_spawnable_on"));

    public static final DefaultedTag<BlockType> CAMPFIRES = BlockTypeTags.key(ResourceKey.minecraft("campfires"));

    public static final DefaultedTag<BlockType> CAN_GLIDE_THROUGH = BlockTypeTags.key(ResourceKey.minecraft("can_glide_through"));

    public static final DefaultedTag<BlockType> CANDLE_CAKES = BlockTypeTags.key(ResourceKey.minecraft("candle_cakes"));

    public static final DefaultedTag<BlockType> CANDLES = BlockTypeTags.key(ResourceKey.minecraft("candles"));

    public static final DefaultedTag<BlockType> CANNOT_PLACE_BASALT_PILLAR_ON = BlockTypeTags.key(ResourceKey.minecraft("cannot_place_basalt_pillar_on"));

    public static final DefaultedTag<BlockType> CANNOT_REPLACE_BELOW_TREE_TRUNK = BlockTypeTags.key(ResourceKey.minecraft("cannot_replace_below_tree_trunk"));

    public static final DefaultedTag<BlockType> CANNOT_SUPPORT_KELP = BlockTypeTags.key(ResourceKey.minecraft("cannot_support_kelp"));

    public static final DefaultedTag<BlockType> CANNOT_SUPPORT_SEAGRASS = BlockTypeTags.key(ResourceKey.minecraft("cannot_support_seagrass"));

    public static final DefaultedTag<BlockType> CANNOT_SUPPORT_SNOW_LAYER = BlockTypeTags.key(ResourceKey.minecraft("cannot_support_snow_layer"));

    public static final DefaultedTag<BlockType> CAT_DOES_NOT_TELEPORT_TO = BlockTypeTags.key(ResourceKey.minecraft("cat_does_not_teleport_to"));

    public static final DefaultedTag<BlockType> CATS_CAN_LIE_ON = BlockTypeTags.key(ResourceKey.minecraft("cats_can_lie_on"));

    public static final DefaultedTag<BlockType> CATS_CAN_SIT_ON = BlockTypeTags.key(ResourceKey.minecraft("cats_can_sit_on"));

    public static final DefaultedTag<BlockType> CAULDRONS = BlockTypeTags.key(ResourceKey.minecraft("cauldrons"));

    public static final DefaultedTag<BlockType> CAUSES_CONTINUOUS_GEYSER_ERUPTIONS = BlockTypeTags.key(ResourceKey.minecraft("causes_continuous_geyser_eruptions"));

    public static final DefaultedTag<BlockType> CAUSES_PERIODIC_GEYSER_ERUPTIONS = BlockTypeTags.key(ResourceKey.minecraft("causes_periodic_geyser_eruptions"));

    public static final DefaultedTag<BlockType> CAUSES_SUFFOCATION = BlockTypeTags.key(ResourceKey.minecraft("causes_suffocation"));

    public static final DefaultedTag<BlockType> CAVE_VINES = BlockTypeTags.key(ResourceKey.minecraft("cave_vines"));

    public static final DefaultedTag<BlockType> CEILING_HANGING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("ceiling_hanging_signs"));

    public static final DefaultedTag<BlockType> CHAINS = BlockTypeTags.key(ResourceKey.minecraft("chains"));

    public static final DefaultedTag<BlockType> CHERRY_LOGS = BlockTypeTags.key(ResourceKey.minecraft("cherry_logs"));

    public static final DefaultedTag<BlockType> CLIMBABLE = BlockTypeTags.key(ResourceKey.minecraft("climbable"));

    public static final DefaultedTag<BlockType> COAL_ORES = BlockTypeTags.key(ResourceKey.minecraft("coal_ores"));

    public static final DefaultedTag<BlockType> COMBINATION_STEP_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("combination_step_sound_blocks"));

    public static final DefaultedTag<BlockType> COMPLETES_FIND_TREE_TUTORIAL = BlockTypeTags.key(ResourceKey.minecraft("completes_find_tree_tutorial"));

    public static final DefaultedTag<BlockType> CONCRETE = BlockTypeTags.key(ResourceKey.minecraft("concrete"));

    public static final DefaultedTag<BlockType> CONCRETE_POWDERS = BlockTypeTags.key(ResourceKey.minecraft("concrete_powders"));

    public static final DefaultedTag<BlockType> CONCRETE_SLABS = BlockTypeTags.key(ResourceKey.minecraft("concrete_slabs"));

    public static final DefaultedTag<BlockType> CONCRETE_STAIRS = BlockTypeTags.key(ResourceKey.minecraft("concrete_stairs"));

    public static final DefaultedTag<BlockType> CONVERTIBLE_TO_MUD = BlockTypeTags.key(ResourceKey.minecraft("convertible_to_mud"));

    public static final DefaultedTag<BlockType> COPPER = BlockTypeTags.key(ResourceKey.minecraft("copper"));

    public static final DefaultedTag<BlockType> COPPER_CHESTS = BlockTypeTags.key(ResourceKey.minecraft("copper_chests"));

    public static final DefaultedTag<BlockType> COPPER_GOLEM_STATUES = BlockTypeTags.key(ResourceKey.minecraft("copper_golem_statues"));

    public static final DefaultedTag<BlockType> COPPER_ORES = BlockTypeTags.key(ResourceKey.minecraft("copper_ores"));

    public static final DefaultedTag<BlockType> CORAL_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("coral_blocks"));

    public static final DefaultedTag<BlockType> CORAL_PLANTS = BlockTypeTags.key(ResourceKey.minecraft("coral_plants"));

    public static final DefaultedTag<BlockType> CORALS = BlockTypeTags.key(ResourceKey.minecraft("corals"));

    public static final DefaultedTag<BlockType> CRIMSON_STEMS = BlockTypeTags.key(ResourceKey.minecraft("crimson_stems"));

    public static final DefaultedTag<BlockType> CROPS = BlockTypeTags.key(ResourceKey.minecraft("crops"));

    public static final DefaultedTag<BlockType> CRYSTAL_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("crystal_sound_blocks"));

    public static final DefaultedTag<BlockType> CUSHION_USES_COLLISION_SHAPE = BlockTypeTags.key(ResourceKey.minecraft("cushion_uses_collision_shape"));

    public static final DefaultedTag<BlockType> DAMPENS_VIBRATIONS = BlockTypeTags.key(ResourceKey.minecraft("dampens_vibrations"));

    public static final DefaultedTag<BlockType> DANGEROUS_FOR_TELEPORTATION = BlockTypeTags.key(ResourceKey.minecraft("dangerous_for_teleportation"));

    public static final DefaultedTag<BlockType> DARK_OAK_LOGS = BlockTypeTags.key(ResourceKey.minecraft("dark_oak_logs"));

    public static final DefaultedTag<BlockType> DEEPSLATE_ORE_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("deepslate_ore_replaceables"));

    public static final DefaultedTag<BlockType> DEFAULT_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("default_immune_to"));

    public static final DefaultedTag<BlockType> DIAMOND_ORES = BlockTypeTags.key(ResourceKey.minecraft("diamond_ores"));

    public static final DefaultedTag<BlockType> DIRT = BlockTypeTags.key(ResourceKey.minecraft("dirt"));

    public static final DefaultedTag<BlockType> DOES_NOT_BLOCK_HOPPERS = BlockTypeTags.key(ResourceKey.minecraft("does_not_block_hoppers"));

    public static final DefaultedTag<BlockType> DOORS = BlockTypeTags.key(ResourceKey.minecraft("doors"));

    public static final DefaultedTag<BlockType> DRAGON_IMMUNE = BlockTypeTags.key(ResourceKey.minecraft("dragon_immune"));

    public static final DefaultedTag<BlockType> DRAGON_TRANSPARENT = BlockTypeTags.key(ResourceKey.minecraft("dragon_transparent"));

    public static final DefaultedTag<BlockType> DRIPSTONE_REPLACEABLE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("dripstone_replaceable_blocks"));

    public static final DefaultedTag<BlockType> EDIBLE_FOR_SHEEP = BlockTypeTags.key(ResourceKey.minecraft("edible_for_sheep"));

    public static final DefaultedTag<BlockType> EMERALD_ORES = BlockTypeTags.key(ResourceKey.minecraft("emerald_ores"));

    public static final DefaultedTag<BlockType> ENABLES_BUBBLE_COLUMN_DRAG_DOWN = BlockTypeTags.key(ResourceKey.minecraft("enables_bubble_column_drag_down"));

    public static final DefaultedTag<BlockType> ENABLES_BUBBLE_COLUMN_PUSH_UP = BlockTypeTags.key(ResourceKey.minecraft("enables_bubble_column_push_up"));

    public static final DefaultedTag<BlockType> ENCHANTMENT_POWER_PROVIDER = BlockTypeTags.key(ResourceKey.minecraft("enchantment_power_provider"));

    public static final DefaultedTag<BlockType> ENCHANTMENT_POWER_TRANSMITTER = BlockTypeTags.key(ResourceKey.minecraft("enchantment_power_transmitter"));

    public static final DefaultedTag<BlockType> ENDERMAN_DOES_NOT_TELEPORT_TO = BlockTypeTags.key(ResourceKey.minecraft("enderman_does_not_teleport_to"));

    public static final DefaultedTag<BlockType> ENDERMAN_HOLDABLE = BlockTypeTags.key(ResourceKey.minecraft("enderman_holdable"));

    public static final DefaultedTag<BlockType> ENTITIES_CAN_TELEPORT_TO = BlockTypeTags.key(ResourceKey.minecraft("entities_can_teleport_to"));

    public static final DefaultedTag<BlockType> FALL_DAMAGE_RESETTING = BlockTypeTags.key(ResourceKey.minecraft("fall_damage_resetting"));

    public static final DefaultedTag<BlockType> FEATURES_CANNOT_REPLACE = BlockTypeTags.key(ResourceKey.minecraft("features_cannot_replace"));

    public static final DefaultedTag<BlockType> FENCE_GATES = BlockTypeTags.key(ResourceKey.minecraft("fence_gates"));

    public static final DefaultedTag<BlockType> FENCES = BlockTypeTags.key(ResourceKey.minecraft("fences"));

    public static final DefaultedTag<BlockType> FIRE = BlockTypeTags.key(ResourceKey.minecraft("fire"));

    public static final DefaultedTag<BlockType> FLOWER_POTS = BlockTypeTags.key(ResourceKey.minecraft("flower_pots"));

    public static final DefaultedTag<BlockType> FLOWERS = BlockTypeTags.key(ResourceKey.minecraft("flowers"));

    public static final DefaultedTag<BlockType> FOREST_ROCK_CAN_PLACE_ON = BlockTypeTags.key(ResourceKey.minecraft("forest_rock_can_place_on"));

    public static final DefaultedTag<BlockType> FOX_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("fox_immune_to"));

    public static final DefaultedTag<BlockType> FOXES_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("foxes_spawnable_on"));

    public static final DefaultedTag<BlockType> FROG_PREFER_JUMP_TO = BlockTypeTags.key(ResourceKey.minecraft("frog_prefer_jump_to"));

    public static final DefaultedTag<BlockType> FROGS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("frogs_spawnable_on"));

    public static final DefaultedTag<BlockType> GEODE_INVALID_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("geode_invalid_blocks"));

    public static final DefaultedTag<BlockType> GLAZED_TERRACOTTA = BlockTypeTags.key(ResourceKey.minecraft("glazed_terracotta"));

    public static final DefaultedTag<BlockType> GOATS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("goats_spawnable_on"));

    public static final DefaultedTag<BlockType> GOLD_ORES = BlockTypeTags.key(ResourceKey.minecraft("gold_ores"));

    public static final DefaultedTag<BlockType> GRASS_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("grass_blocks"));

    public static final DefaultedTag<BlockType> GROWS_CROPS = BlockTypeTags.key(ResourceKey.minecraft("grows_crops"));

    public static final DefaultedTag<BlockType> GUARDED_BY_PIGLINS = BlockTypeTags.key(ResourceKey.minecraft("guarded_by_piglins"));

    public static final DefaultedTag<BlockType> HAPPY_GHAST_AVOIDS = BlockTypeTags.key(ResourceKey.minecraft("happy_ghast_avoids"));

    public static final DefaultedTag<BlockType> HEIGHT_SPECIFIC_ORE_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("height_specific_ore_replaceables"));

    public static final DefaultedTag<BlockType> HOGLIN_REPELLENTS = BlockTypeTags.key(ResourceKey.minecraft("hoglin_repellents"));

    public static final DefaultedTag<BlockType> HUGE_BROWN_MUSHROOM_CAN_PLACE_ON = BlockTypeTags.key(ResourceKey.minecraft("huge_brown_mushroom_can_place_on"));

    public static final DefaultedTag<BlockType> HUGE_RED_MUSHROOM_CAN_PLACE_ON = BlockTypeTags.key(ResourceKey.minecraft("huge_red_mushroom_can_place_on"));

    public static final DefaultedTag<BlockType> ICE = BlockTypeTags.key(ResourceKey.minecraft("ice"));

    public static final DefaultedTag<BlockType> ICE_MELTS_WHEN_DESTROYED_ABOVE = BlockTypeTags.key(ResourceKey.minecraft("ice_melts_when_destroyed_above"));

    public static final DefaultedTag<BlockType> ICE_SPIKE_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("ice_spike_replaceable"));

    public static final DefaultedTag<BlockType> IMPERMEABLE = BlockTypeTags.key(ResourceKey.minecraft("impermeable"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_COPPER_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_copper_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_DIAMOND_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_diamond_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_GOLD_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_gold_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_IRON_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_iron_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_NETHERITE_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_netherite_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_STONE_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_stone_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_WOODEN_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_wooden_tool"));

    public static final DefaultedTag<BlockType> INFINIBURN_END = BlockTypeTags.key(ResourceKey.minecraft("infiniburn_end"));

    public static final DefaultedTag<BlockType> INFINIBURN_NETHER = BlockTypeTags.key(ResourceKey.minecraft("infiniburn_nether"));

    public static final DefaultedTag<BlockType> INFINIBURN_OVERWORLD = BlockTypeTags.key(ResourceKey.minecraft("infiniburn_overworld"));

    public static final DefaultedTag<BlockType> INSIDE_STEP_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("inside_step_sound_blocks"));

    public static final DefaultedTag<BlockType> INVALID_SPAWN_INSIDE = BlockTypeTags.key(ResourceKey.minecraft("invalid_spawn_inside"));

    public static final DefaultedTag<BlockType> IRON_ORES = BlockTypeTags.key(ResourceKey.minecraft("iron_ores"));

    public static final DefaultedTag<BlockType> JUNGLE_LOGS = BlockTypeTags.key(ResourceKey.minecraft("jungle_logs"));

    public static final DefaultedTag<BlockType> LANTERNS = BlockTypeTags.key(ResourceKey.minecraft("lanterns"));

    public static final DefaultedTag<BlockType> LAPIS_ORES = BlockTypeTags.key(ResourceKey.minecraft("lapis_ores"));

    public static final DefaultedTag<BlockType> LAVA_POOL_STONE_CANNOT_REPLACE = BlockTypeTags.key(ResourceKey.minecraft("lava_pool_stone_cannot_replace"));

    public static final DefaultedTag<BlockType> LEAVES = BlockTypeTags.key(ResourceKey.minecraft("leaves"));

    public static final DefaultedTag<BlockType> LIGHTNING_RODS = BlockTypeTags.key(ResourceKey.minecraft("lightning_rods"));

    public static final DefaultedTag<BlockType> LOGS = BlockTypeTags.key(ResourceKey.minecraft("logs"));

    public static final DefaultedTag<BlockType> LOGS_THAT_BURN = BlockTypeTags.key(ResourceKey.minecraft("logs_that_burn"));

    public static final DefaultedTag<BlockType> LUSH_GROUND_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("lush_ground_replaceable"));

    public static final DefaultedTag<BlockType> MAINTAINS_FARMLAND = BlockTypeTags.key(ResourceKey.minecraft("maintains_farmland"));

    public static final DefaultedTag<BlockType> MANGROVE_LOGS = BlockTypeTags.key(ResourceKey.minecraft("mangrove_logs"));

    public static final DefaultedTag<BlockType> MANGROVE_LOGS_CAN_GROW_THROUGH = BlockTypeTags.key(ResourceKey.minecraft("mangrove_logs_can_grow_through"));

    public static final DefaultedTag<BlockType> MANGROVE_ROOTS_CAN_GROW_THROUGH = BlockTypeTags.key(ResourceKey.minecraft("mangrove_roots_can_grow_through"));

    public static final DefaultedTag<BlockType> MINEABLE_AXE = BlockTypeTags.key(ResourceKey.minecraft("mineable/axe"));

    public static final DefaultedTag<BlockType> MINEABLE_HOE = BlockTypeTags.key(ResourceKey.minecraft("mineable/hoe"));

    public static final DefaultedTag<BlockType> MINEABLE_PICKAXE = BlockTypeTags.key(ResourceKey.minecraft("mineable/pickaxe"));

    public static final DefaultedTag<BlockType> MINEABLE_SHOVEL = BlockTypeTags.key(ResourceKey.minecraft("mineable/shovel"));

    public static final DefaultedTag<BlockType> MOB_INTERACTABLE_DOORS = BlockTypeTags.key(ResourceKey.minecraft("mob_interactable_doors"));

    public static final DefaultedTag<BlockType> MOOSHROOMS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("mooshrooms_spawnable_on"));

    public static final DefaultedTag<BlockType> MOSS_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("moss_blocks"));

    public static final DefaultedTag<BlockType> MOSS_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("moss_replaceable"));

    public static final DefaultedTag<BlockType> MUD = BlockTypeTags.key(ResourceKey.minecraft("mud"));

    public static final DefaultedTag<BlockType> NEEDS_DIAMOND_TOOL = BlockTypeTags.key(ResourceKey.minecraft("needs_diamond_tool"));

    public static final DefaultedTag<BlockType> NEEDS_IRON_TOOL = BlockTypeTags.key(ResourceKey.minecraft("needs_iron_tool"));

    public static final DefaultedTag<BlockType> NEEDS_STONE_TOOL = BlockTypeTags.key(ResourceKey.minecraft("needs_stone_tool"));

    public static final DefaultedTag<BlockType> NYLIUM = BlockTypeTags.key(ResourceKey.minecraft("nylium"));

    public static final DefaultedTag<BlockType> OAK_LOGS = BlockTypeTags.key(ResourceKey.minecraft("oak_logs"));

    public static final DefaultedTag<BlockType> OCCLUDES_VIBRATION_SIGNALS = BlockTypeTags.key(ResourceKey.minecraft("occludes_vibration_signals"));

    public static final DefaultedTag<BlockType> ORES = BlockTypeTags.key(ResourceKey.minecraft("ores"));

    public static final DefaultedTag<BlockType> OVERRIDES_MUSHROOM_LIGHT_REQUIREMENT = BlockTypeTags.key(ResourceKey.minecraft("overrides_mushroom_light_requirement"));

    public static final DefaultedTag<BlockType> OVERWORLD_NATURAL_LOGS = BlockTypeTags.key(ResourceKey.minecraft("overworld_natural_logs"));

    public static final DefaultedTag<BlockType> PALE_OAK_LOGS = BlockTypeTags.key(ResourceKey.minecraft("pale_oak_logs"));

    public static final DefaultedTag<BlockType> PARROTS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("parrots_spawnable_on"));

    public static final DefaultedTag<BlockType> PIGLIN_REPELLENTS = BlockTypeTags.key(ResourceKey.minecraft("piglin_repellents"));

    public static final DefaultedTag<BlockType> PLANKS = BlockTypeTags.key(ResourceKey.minecraft("planks"));

    public static final DefaultedTag<BlockType> POLAR_BEAR_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("polar_bear_immune_to"));

    public static final DefaultedTag<BlockType> POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = BlockTypeTags.key(ResourceKey.minecraft("polar_bears_spawnable_on_alternate"));

    public static final DefaultedTag<BlockType> POPLAR_LOGS = BlockTypeTags.key(ResourceKey.minecraft("poplar_logs"));

    public static final DefaultedTag<BlockType> PORTALS = BlockTypeTags.key(ResourceKey.minecraft("portals"));

    public static final DefaultedTag<BlockType> PRESSURE_PLATES = BlockTypeTags.key(ResourceKey.minecraft("pressure_plates"));

    public static final DefaultedTag<BlockType> PREVENT_MOB_SPAWNING_INSIDE = BlockTypeTags.key(ResourceKey.minecraft("prevent_mob_spawning_inside"));

    public static final DefaultedTag<BlockType> PREVENTS_NEARBY_LEAF_DECAY = BlockTypeTags.key(ResourceKey.minecraft("prevents_nearby_leaf_decay"));

    public static final DefaultedTag<BlockType> RABBITS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("rabbits_spawnable_on"));

    public static final DefaultedTag<BlockType> RAILS = BlockTypeTags.key(ResourceKey.minecraft("rails"));

    public static final DefaultedTag<BlockType> REDSTONE_ORES = BlockTypeTags.key(ResourceKey.minecraft("redstone_ores"));

    public static final DefaultedTag<BlockType> REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("replaceable"));

    public static final DefaultedTag<BlockType> REPLACEABLE_BY_MUSHROOMS = BlockTypeTags.key(ResourceKey.minecraft("replaceable_by_mushrooms"));

    public static final DefaultedTag<BlockType> REPLACEABLE_BY_TREES = BlockTypeTags.key(ResourceKey.minecraft("replaceable_by_trees"));

    public static final DefaultedTag<BlockType> REQUIRED_FOR_POPLAR_LEAF_AMBIENCE = BlockTypeTags.key(ResourceKey.minecraft("required_for_poplar_leaf_ambience"));

    public static final DefaultedTag<BlockType> SAND = BlockTypeTags.key(ResourceKey.minecraft("sand"));

    public static final DefaultedTag<BlockType> SAPLINGS = BlockTypeTags.key(ResourceKey.minecraft("saplings"));

    public static final DefaultedTag<BlockType> SCULK_GROWTH_INHIBITORS = BlockTypeTags.key(ResourceKey.minecraft("sculk_growth_inhibitors"));

    public static final DefaultedTag<BlockType> SCULK_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("sculk_replaceable"));

    public static final DefaultedTag<BlockType> SCULK_REPLACEABLE_WORLD_GEN = BlockTypeTags.key(ResourceKey.minecraft("sculk_replaceable_world_gen"));

    public static final DefaultedTag<BlockType> SHEARS_EXTREME_BREAKING_SPEED = BlockTypeTags.key(ResourceKey.minecraft("shears_extreme_breaking_speed"));

    public static final DefaultedTag<BlockType> SHEARS_MAJOR_BREAKING_SPEED = BlockTypeTags.key(ResourceKey.minecraft("shears_major_breaking_speed"));

    public static final DefaultedTag<BlockType> SHEARS_MINOR_BREAKING_SPEED = BlockTypeTags.key(ResourceKey.minecraft("shears_minor_breaking_speed"));

    public static final DefaultedTag<BlockType> SHULKER_BOXES = BlockTypeTags.key(ResourceKey.minecraft("shulker_boxes"));

    public static final DefaultedTag<BlockType> SHULKER_DOES_NOT_TELEPORT_TO = BlockTypeTags.key(ResourceKey.minecraft("shulker_does_not_teleport_to"));

    public static final DefaultedTag<BlockType> SIGNS = BlockTypeTags.key(ResourceKey.minecraft("signs"));

    public static final DefaultedTag<BlockType> SKULLS = BlockTypeTags.key(ResourceKey.minecraft("skulls"));

    public static final DefaultedTag<BlockType> SLABS = BlockTypeTags.key(ResourceKey.minecraft("slabs"));

    public static final DefaultedTag<BlockType> SMALL_FLOWERS = BlockTypeTags.key(ResourceKey.minecraft("small_flowers"));

    public static final DefaultedTag<BlockType> SMELTS_TO_GLASS = BlockTypeTags.key(ResourceKey.minecraft("smelts_to_glass"));

    public static final DefaultedTag<BlockType> SNAPS_GOAT_HORN = BlockTypeTags.key(ResourceKey.minecraft("snaps_goat_horn"));

    public static final DefaultedTag<BlockType> SNIFFER_DIGGABLE_BLOCK = BlockTypeTags.key(ResourceKey.minecraft("sniffer_diggable_block"));

    public static final DefaultedTag<BlockType> SNIFFER_EGG_HATCH_BOOST = BlockTypeTags.key(ResourceKey.minecraft("sniffer_egg_hatch_boost"));

    public static final DefaultedTag<BlockType> SNOW = BlockTypeTags.key(ResourceKey.minecraft("snow"));

    public static final DefaultedTag<BlockType> SNOW_GOLEM_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("snow_golem_immune_to"));

    public static final DefaultedTag<BlockType> SOUL_FIRE_BASE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("soul_fire_base_blocks"));

    public static final DefaultedTag<BlockType> SOUL_SPEED_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("soul_speed_blocks"));

    public static final DefaultedTag<BlockType> SPEEDS_UP_ZOMBIE_VILLAGER_CURING = BlockTypeTags.key(ResourceKey.minecraft("speeds_up_zombie_villager_curing"));

    public static final DefaultedTag<BlockType> SPELEOTHEMS = BlockTypeTags.key(ResourceKey.minecraft("speleothems"));

    public static final DefaultedTag<BlockType> SPRUCE_LOGS = BlockTypeTags.key(ResourceKey.minecraft("spruce_logs"));

    public static final DefaultedTag<BlockType> STAIRS = BlockTypeTags.key(ResourceKey.minecraft("stairs"));

    public static final DefaultedTag<BlockType> STANDING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("standing_signs"));

    public static final DefaultedTag<BlockType> STONE_BRICKS = BlockTypeTags.key(ResourceKey.minecraft("stone_bricks"));

    public static final DefaultedTag<BlockType> STONE_BUTTONS = BlockTypeTags.key(ResourceKey.minecraft("stone_buttons"));

    public static final DefaultedTag<BlockType> STONE_ORE_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("stone_ore_replaceables"));

    public static final DefaultedTag<BlockType> STONE_PRESSURE_PLATES = BlockTypeTags.key(ResourceKey.minecraft("stone_pressure_plates"));

    public static final DefaultedTag<BlockType> STRAY_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("stray_immune_to"));

    public static final DefaultedTag<BlockType> STRIDER_WARM_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("strider_warm_blocks"));

    public static final DefaultedTag<BlockType> SUBSTRATE_OVERWORLD = BlockTypeTags.key(ResourceKey.minecraft("substrate_overworld"));

    public static final DefaultedTag<BlockType> SULFUR_SPIKE_REPLACEABLE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("sulfur_spike_replaceable_blocks"));

    public static final DefaultedTag<BlockType> SUPPORT_OVERRIDE_CACTUS_FLOWER = BlockTypeTags.key(ResourceKey.minecraft("support_override_cactus_flower"));

    public static final DefaultedTag<BlockType> SUPPORT_OVERRIDE_SNOW_LAYER = BlockTypeTags.key(ResourceKey.minecraft("support_override_snow_layer"));

    public static final DefaultedTag<BlockType> SUPPORTS_AZALEA = BlockTypeTags.key(ResourceKey.minecraft("supports_azalea"));

    public static final DefaultedTag<BlockType> SUPPORTS_BAMBOO = BlockTypeTags.key(ResourceKey.minecraft("supports_bamboo"));

    public static final DefaultedTag<BlockType> SUPPORTS_BIG_DRIPLEAF = BlockTypeTags.key(ResourceKey.minecraft("supports_big_dripleaf"));

    public static final DefaultedTag<BlockType> SUPPORTS_CACTUS = BlockTypeTags.key(ResourceKey.minecraft("supports_cactus"));

    public static final DefaultedTag<BlockType> SUPPORTS_CHORUS_FLOWER = BlockTypeTags.key(ResourceKey.minecraft("supports_chorus_flower"));

    public static final DefaultedTag<BlockType> SUPPORTS_CHORUS_PLANT = BlockTypeTags.key(ResourceKey.minecraft("supports_chorus_plant"));

    public static final DefaultedTag<BlockType> SUPPORTS_COCOA = BlockTypeTags.key(ResourceKey.minecraft("supports_cocoa"));

    public static final DefaultedTag<BlockType> SUPPORTS_CRIMSON_FUNGUS = BlockTypeTags.key(ResourceKey.minecraft("supports_crimson_fungus"));

    public static final DefaultedTag<BlockType> SUPPORTS_CRIMSON_ROOTS = BlockTypeTags.key(ResourceKey.minecraft("supports_crimson_roots"));

    public static final DefaultedTag<BlockType> SUPPORTS_CROPS = BlockTypeTags.key(ResourceKey.minecraft("supports_crops"));

    public static final DefaultedTag<BlockType> SUPPORTS_DRY_VEGETATION = BlockTypeTags.key(ResourceKey.minecraft("supports_dry_vegetation"));

    public static final DefaultedTag<BlockType> SUPPORTS_FROGSPAWN = BlockTypeTags.key(ResourceKey.minecraft("supports_frogspawn"));

    public static final DefaultedTag<BlockType> SUPPORTS_HANGING_MANGROVE_PROPAGULE = BlockTypeTags.key(ResourceKey.minecraft("supports_hanging_mangrove_propagule"));

    public static final DefaultedTag<BlockType> SUPPORTS_LILY_PAD = BlockTypeTags.key(ResourceKey.minecraft("supports_lily_pad"));

    public static final DefaultedTag<BlockType> SUPPORTS_MANGROVE_PROPAGULE = BlockTypeTags.key(ResourceKey.minecraft("supports_mangrove_propagule"));

    public static final DefaultedTag<BlockType> SUPPORTS_MELON_STEM = BlockTypeTags.key(ResourceKey.minecraft("supports_melon_stem"));

    public static final DefaultedTag<BlockType> SUPPORTS_MELON_STEM_FRUIT = BlockTypeTags.key(ResourceKey.minecraft("supports_melon_stem_fruit"));

    public static final DefaultedTag<BlockType> SUPPORTS_NETHER_SPROUTS = BlockTypeTags.key(ResourceKey.minecraft("supports_nether_sprouts"));

    public static final DefaultedTag<BlockType> SUPPORTS_NETHER_WART = BlockTypeTags.key(ResourceKey.minecraft("supports_nether_wart"));

    public static final DefaultedTag<BlockType> SUPPORTS_PUMPKIN_STEM = BlockTypeTags.key(ResourceKey.minecraft("supports_pumpkin_stem"));

    public static final DefaultedTag<BlockType> SUPPORTS_PUMPKIN_STEM_FRUIT = BlockTypeTags.key(ResourceKey.minecraft("supports_pumpkin_stem_fruit"));

    public static final DefaultedTag<BlockType> SUPPORTS_SMALL_DRIPLEAF = BlockTypeTags.key(ResourceKey.minecraft("supports_small_dripleaf"));

    public static final DefaultedTag<BlockType> SUPPORTS_STEM_CROPS = BlockTypeTags.key(ResourceKey.minecraft("supports_stem_crops"));

    public static final DefaultedTag<BlockType> SUPPORTS_STEM_FRUIT = BlockTypeTags.key(ResourceKey.minecraft("supports_stem_fruit"));

    public static final DefaultedTag<BlockType> SUPPORTS_SUGAR_CANE = BlockTypeTags.key(ResourceKey.minecraft("supports_sugar_cane"));

    public static final DefaultedTag<BlockType> SUPPORTS_SUGAR_CANE_ADJACENTLY = BlockTypeTags.key(ResourceKey.minecraft("supports_sugar_cane_adjacently"));

    public static final DefaultedTag<BlockType> SUPPORTS_VEGETATION = BlockTypeTags.key(ResourceKey.minecraft("supports_vegetation"));

    public static final DefaultedTag<BlockType> SUPPORTS_WARPED_FUNGUS = BlockTypeTags.key(ResourceKey.minecraft("supports_warped_fungus"));

    public static final DefaultedTag<BlockType> SUPPORTS_WARPED_ROOTS = BlockTypeTags.key(ResourceKey.minecraft("supports_warped_roots"));

    public static final DefaultedTag<BlockType> SUPPORTS_WITHER_ROSE = BlockTypeTags.key(ResourceKey.minecraft("supports_wither_rose"));

    public static final DefaultedTag<BlockType> SUPPRESSES_BOUNCE = BlockTypeTags.key(ResourceKey.minecraft("suppresses_bounce"));

    public static final DefaultedTag<BlockType> SWORD_EFFICIENT = BlockTypeTags.key(ResourceKey.minecraft("sword_efficient"));

    public static final DefaultedTag<BlockType> SWORD_INSTANTLY_MINES = BlockTypeTags.key(ResourceKey.minecraft("sword_instantly_mines"));

    public static final DefaultedTag<BlockType> TERRACOTTA = BlockTypeTags.key(ResourceKey.minecraft("terracotta"));

    public static final DefaultedTag<BlockType> TRAIL_RUINS_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("trail_ruins_replaceable"));

    public static final DefaultedTag<BlockType> TRAPDOORS = BlockTypeTags.key(ResourceKey.minecraft("trapdoors"));

    public static final DefaultedTag<BlockType> TRIGGERS_AMBIENT_DESERT_DRY_VEGETATION_BLOCK_SOUNDS = BlockTypeTags.key(ResourceKey.minecraft("triggers_ambient_desert_dry_vegetation_block_sounds"));

    public static final DefaultedTag<BlockType> TRIGGERS_AMBIENT_DESERT_SAND_BLOCK_SOUNDS = BlockTypeTags.key(ResourceKey.minecraft("triggers_ambient_desert_sand_block_sounds"));

    public static final DefaultedTag<BlockType> TRIGGERS_AMBIENT_DRIED_GHAST_BLOCK_SOUNDS = BlockTypeTags.key(ResourceKey.minecraft("triggers_ambient_dried_ghast_block_sounds"));

    public static final DefaultedTag<BlockType> TURNS_INTO_DIRT_PATH = BlockTypeTags.key(ResourceKey.minecraft("turns_into_dirt_path"));

    public static final DefaultedTag<BlockType> TURNS_INTO_FARMLAND = BlockTypeTags.key(ResourceKey.minecraft("turns_into_farmland"));

    public static final DefaultedTag<BlockType> UNCARVABLE = BlockTypeTags.key(ResourceKey.minecraft("uncarvable"));

    public static final DefaultedTag<BlockType> UNDERWATER_BONEMEALS = BlockTypeTags.key(ResourceKey.minecraft("underwater_bonemeals"));

    public static final DefaultedTag<BlockType> UNSTABLE_BOTTOM_CENTER = BlockTypeTags.key(ResourceKey.minecraft("unstable_bottom_center"));

    public static final DefaultedTag<BlockType> VALID_SPAWN = BlockTypeTags.key(ResourceKey.minecraft("valid_spawn"));

    public static final DefaultedTag<BlockType> VIBRATION_RESONATORS = BlockTypeTags.key(ResourceKey.minecraft("vibration_resonators"));

    public static final DefaultedTag<BlockType> VILLAGER_BABIES_CAN_JUMP_ON_BED = BlockTypeTags.key(ResourceKey.minecraft("villager_babies_can_jump_on_bed"));

    public static final DefaultedTag<BlockType> VILLAGERS_CAN_SLEEP_ON_BED = BlockTypeTags.key(ResourceKey.minecraft("villagers_can_sleep_on_bed"));

    public static final DefaultedTag<BlockType> WALL_CORALS = BlockTypeTags.key(ResourceKey.minecraft("wall_corals"));

    public static final DefaultedTag<BlockType> WALL_HANGING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("wall_hanging_signs"));

    public static final DefaultedTag<BlockType> WALL_POST_OVERRIDE = BlockTypeTags.key(ResourceKey.minecraft("wall_post_override"));

    public static final DefaultedTag<BlockType> WALL_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("wall_signs"));

    public static final DefaultedTag<BlockType> WALLS = BlockTypeTags.key(ResourceKey.minecraft("walls"));

    public static final DefaultedTag<BlockType> WARPED_STEMS = BlockTypeTags.key(ResourceKey.minecraft("warped_stems"));

    public static final DefaultedTag<BlockType> WART_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("wart_blocks"));

    public static final DefaultedTag<BlockType> WASHED_AWAY_BY_FLUIDS = BlockTypeTags.key(ResourceKey.minecraft("washed_away_by_fluids"));

    public static final DefaultedTag<BlockType> WITHER_IMMUNE = BlockTypeTags.key(ResourceKey.minecraft("wither_immune"));

    public static final DefaultedTag<BlockType> WITHER_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("wither_immune_to"));

    public static final DefaultedTag<BlockType> WITHER_SKELETON_IMMUNE_TO = BlockTypeTags.key(ResourceKey.minecraft("wither_skeleton_immune_to"));

    public static final DefaultedTag<BlockType> WITHER_SUMMON_BASE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("wither_summon_base_blocks"));

    public static final DefaultedTag<BlockType> WOLVES_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("wolves_spawnable_on"));

    public static final DefaultedTag<BlockType> WOODEN_BUTTONS = BlockTypeTags.key(ResourceKey.minecraft("wooden_buttons"));

    public static final DefaultedTag<BlockType> WOODEN_DOORS = BlockTypeTags.key(ResourceKey.minecraft("wooden_doors"));

    public static final DefaultedTag<BlockType> WOODEN_FENCES = BlockTypeTags.key(ResourceKey.minecraft("wooden_fences"));

    public static final DefaultedTag<BlockType> WOODEN_PRESSURE_PLATES = BlockTypeTags.key(ResourceKey.minecraft("wooden_pressure_plates"));

    public static final DefaultedTag<BlockType> WOODEN_SHELVES = BlockTypeTags.key(ResourceKey.minecraft("wooden_shelves"));

    public static final DefaultedTag<BlockType> WOODEN_SLABS = BlockTypeTags.key(ResourceKey.minecraft("wooden_slabs"));

    public static final DefaultedTag<BlockType> WOODEN_STAIRS = BlockTypeTags.key(ResourceKey.minecraft("wooden_stairs"));

    public static final DefaultedTag<BlockType> WOODEN_TRAPDOORS = BlockTypeTags.key(ResourceKey.minecraft("wooden_trapdoors"));

    public static final DefaultedTag<BlockType> WOOL = BlockTypeTags.key(ResourceKey.minecraft("wool"));

    public static final DefaultedTag<BlockType> WOOL_CARPETS = BlockTypeTags.key(ResourceKey.minecraft("wool_carpets"));

    public static final DefaultedTag<BlockType> WOOL_SLABS = BlockTypeTags.key(ResourceKey.minecraft("wool_slabs"));

    public static final DefaultedTag<BlockType> WOOL_STAIRS = BlockTypeTags.key(ResourceKey.minecraft("wool_stairs"));

    private BlockTypeTags() {
    }

    private static DefaultedTag<BlockType> key(final ResourceKey key) {
        return DefaultedTag.of(RegistryTypes.BLOCK_TYPE, key);
    }
}
