/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.tag;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.block.BlockType;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class BlockTypeTags {

    public static final DefaultedTag<BlockType> ACACIA_LOGS = BlockTypeTags.key(ResourceKey.minecraft("acacia_logs"));

    public static final DefaultedTag<BlockType> AIR = BlockTypeTags.key(ResourceKey.minecraft("air"));

    public static final DefaultedTag<BlockType> ALL_HANGING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("all_hanging_signs"));

    public static final DefaultedTag<BlockType> ALL_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("all_signs"));

    public static final DefaultedTag<BlockType> ANCIENT_CITY_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("ancient_city_replaceable"));

    public static final DefaultedTag<BlockType> ANIMALS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("animals_spawnable_on"));

    public static final DefaultedTag<BlockType> ANVIL = BlockTypeTags.key(ResourceKey.minecraft("anvil"));

    public static final DefaultedTag<BlockType> ARMADILLO_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("armadillo_spawnable_on"));

    public static final DefaultedTag<BlockType> AXOLOTLS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("axolotls_spawnable_on"));

    public static final DefaultedTag<BlockType> AZALEA_GROWS_ON = BlockTypeTags.key(ResourceKey.minecraft("azalea_grows_on"));

    public static final DefaultedTag<BlockType> AZALEA_ROOT_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("azalea_root_replaceable"));

    public static final DefaultedTag<BlockType> BADLANDS_TERRACOTTA = BlockTypeTags.key(ResourceKey.minecraft("badlands_terracotta"));

    public static final DefaultedTag<BlockType> BAMBOO_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("bamboo_blocks"));

    public static final DefaultedTag<BlockType> BAMBOO_PLANTABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("bamboo_plantable_on"));

    public static final DefaultedTag<BlockType> BANNERS = BlockTypeTags.key(ResourceKey.minecraft("banners"));

    public static final DefaultedTag<BlockType> BASE_STONE_NETHER = BlockTypeTags.key(ResourceKey.minecraft("base_stone_nether"));

    public static final DefaultedTag<BlockType> BASE_STONE_OVERWORLD = BlockTypeTags.key(ResourceKey.minecraft("base_stone_overworld"));

    public static final DefaultedTag<BlockType> BATS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("bats_spawnable_on"));

    public static final DefaultedTag<BlockType> BEACON_BASE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("beacon_base_blocks"));

    public static final DefaultedTag<BlockType> BEDS = BlockTypeTags.key(ResourceKey.minecraft("beds"));

    public static final DefaultedTag<BlockType> BEE_ATTRACTIVE = BlockTypeTags.key(ResourceKey.minecraft("bee_attractive"));

    public static final DefaultedTag<BlockType> BEE_GROWABLES = BlockTypeTags.key(ResourceKey.minecraft("bee_growables"));

    public static final DefaultedTag<BlockType> BEEHIVES = BlockTypeTags.key(ResourceKey.minecraft("beehives"));

    public static final DefaultedTag<BlockType> BIG_DRIPLEAF_PLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("big_dripleaf_placeable"));

    public static final DefaultedTag<BlockType> BIRCH_LOGS = BlockTypeTags.key(ResourceKey.minecraft("birch_logs"));

    public static final DefaultedTag<BlockType> BLOCKS_WIND_CHARGE_EXPLOSIONS = BlockTypeTags.key(ResourceKey.minecraft("blocks_wind_charge_explosions"));

    public static final DefaultedTag<BlockType> BUTTONS = BlockTypeTags.key(ResourceKey.minecraft("buttons"));

    public static final DefaultedTag<BlockType> CAMEL_SAND_STEP_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("camel_sand_step_sound_blocks"));

    public static final DefaultedTag<BlockType> CAMPFIRES = BlockTypeTags.key(ResourceKey.minecraft("campfires"));

    public static final DefaultedTag<BlockType> CANDLE_CAKES = BlockTypeTags.key(ResourceKey.minecraft("candle_cakes"));

    public static final DefaultedTag<BlockType> CANDLES = BlockTypeTags.key(ResourceKey.minecraft("candles"));

    public static final DefaultedTag<BlockType> CAULDRONS = BlockTypeTags.key(ResourceKey.minecraft("cauldrons"));

    public static final DefaultedTag<BlockType> CAVE_VINES = BlockTypeTags.key(ResourceKey.minecraft("cave_vines"));

    public static final DefaultedTag<BlockType> CEILING_HANGING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("ceiling_hanging_signs"));

    public static final DefaultedTag<BlockType> CHERRY_LOGS = BlockTypeTags.key(ResourceKey.minecraft("cherry_logs"));

    public static final DefaultedTag<BlockType> CLIMBABLE = BlockTypeTags.key(ResourceKey.minecraft("climbable"));

    public static final DefaultedTag<BlockType> COAL_ORES = BlockTypeTags.key(ResourceKey.minecraft("coal_ores"));

    public static final DefaultedTag<BlockType> COMBINATION_STEP_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("combination_step_sound_blocks"));

    public static final DefaultedTag<BlockType> COMPLETES_FIND_TREE_TUTORIAL = BlockTypeTags.key(ResourceKey.minecraft("completes_find_tree_tutorial"));

    public static final DefaultedTag<BlockType> CONCRETE_POWDER = BlockTypeTags.key(ResourceKey.minecraft("concrete_powder"));

    public static final DefaultedTag<BlockType> CONVERTABLE_TO_MUD = BlockTypeTags.key(ResourceKey.minecraft("convertable_to_mud"));

    public static final DefaultedTag<BlockType> COPPER_ORES = BlockTypeTags.key(ResourceKey.minecraft("copper_ores"));

    public static final DefaultedTag<BlockType> CORAL_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("coral_blocks"));

    public static final DefaultedTag<BlockType> CORAL_PLANTS = BlockTypeTags.key(ResourceKey.minecraft("coral_plants"));

    public static final DefaultedTag<BlockType> CORALS = BlockTypeTags.key(ResourceKey.minecraft("corals"));

    public static final DefaultedTag<BlockType> CRIMSON_STEMS = BlockTypeTags.key(ResourceKey.minecraft("crimson_stems"));

    public static final DefaultedTag<BlockType> CROPS = BlockTypeTags.key(ResourceKey.minecraft("crops"));

    public static final DefaultedTag<BlockType> CRYSTAL_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("crystal_sound_blocks"));

    public static final DefaultedTag<BlockType> DAMPENS_VIBRATIONS = BlockTypeTags.key(ResourceKey.minecraft("dampens_vibrations"));

    public static final DefaultedTag<BlockType> DARK_OAK_LOGS = BlockTypeTags.key(ResourceKey.minecraft("dark_oak_logs"));

    public static final DefaultedTag<BlockType> DEAD_BUSH_MAY_PLACE_ON = BlockTypeTags.key(ResourceKey.minecraft("dead_bush_may_place_on"));

    public static final DefaultedTag<BlockType> DEEPSLATE_ORE_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("deepslate_ore_replaceables"));

    public static final DefaultedTag<BlockType> DIAMOND_ORES = BlockTypeTags.key(ResourceKey.minecraft("diamond_ores"));

    public static final DefaultedTag<BlockType> DIRT = BlockTypeTags.key(ResourceKey.minecraft("dirt"));

    public static final DefaultedTag<BlockType> DOES_NOT_BLOCK_HOPPERS = BlockTypeTags.key(ResourceKey.minecraft("does_not_block_hoppers"));

    public static final DefaultedTag<BlockType> DOORS = BlockTypeTags.key(ResourceKey.minecraft("doors"));

    public static final DefaultedTag<BlockType> DRAGON_IMMUNE = BlockTypeTags.key(ResourceKey.minecraft("dragon_immune"));

    public static final DefaultedTag<BlockType> DRAGON_TRANSPARENT = BlockTypeTags.key(ResourceKey.minecraft("dragon_transparent"));

    public static final DefaultedTag<BlockType> DRIPSTONE_REPLACEABLE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("dripstone_replaceable_blocks"));

    public static final DefaultedTag<BlockType> EMERALD_ORES = BlockTypeTags.key(ResourceKey.minecraft("emerald_ores"));

    public static final DefaultedTag<BlockType> ENCHANTMENT_POWER_PROVIDER = BlockTypeTags.key(ResourceKey.minecraft("enchantment_power_provider"));

    public static final DefaultedTag<BlockType> ENCHANTMENT_POWER_TRANSMITTER = BlockTypeTags.key(ResourceKey.minecraft("enchantment_power_transmitter"));

    public static final DefaultedTag<BlockType> ENDERMAN_HOLDABLE = BlockTypeTags.key(ResourceKey.minecraft("enderman_holdable"));

    public static final DefaultedTag<BlockType> FALL_DAMAGE_RESETTING = BlockTypeTags.key(ResourceKey.minecraft("fall_damage_resetting"));

    public static final DefaultedTag<BlockType> FEATURES_CANNOT_REPLACE = BlockTypeTags.key(ResourceKey.minecraft("features_cannot_replace"));

    public static final DefaultedTag<BlockType> FENCE_GATES = BlockTypeTags.key(ResourceKey.minecraft("fence_gates"));

    public static final DefaultedTag<BlockType> FENCES = BlockTypeTags.key(ResourceKey.minecraft("fences"));

    public static final DefaultedTag<BlockType> FIRE = BlockTypeTags.key(ResourceKey.minecraft("fire"));

    public static final DefaultedTag<BlockType> FLOWER_POTS = BlockTypeTags.key(ResourceKey.minecraft("flower_pots"));

    public static final DefaultedTag<BlockType> FLOWERS = BlockTypeTags.key(ResourceKey.minecraft("flowers"));

    public static final DefaultedTag<BlockType> FOXES_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("foxes_spawnable_on"));

    public static final DefaultedTag<BlockType> FROG_PREFER_JUMP_TO = BlockTypeTags.key(ResourceKey.minecraft("frog_prefer_jump_to"));

    public static final DefaultedTag<BlockType> FROGS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("frogs_spawnable_on"));

    public static final DefaultedTag<BlockType> GEODE_INVALID_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("geode_invalid_blocks"));

    public static final DefaultedTag<BlockType> GOATS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("goats_spawnable_on"));

    public static final DefaultedTag<BlockType> GOLD_ORES = BlockTypeTags.key(ResourceKey.minecraft("gold_ores"));

    public static final DefaultedTag<BlockType> GUARDED_BY_PIGLINS = BlockTypeTags.key(ResourceKey.minecraft("guarded_by_piglins"));

    public static final DefaultedTag<BlockType> HOGLIN_REPELLENTS = BlockTypeTags.key(ResourceKey.minecraft("hoglin_repellents"));

    public static final DefaultedTag<BlockType> ICE = BlockTypeTags.key(ResourceKey.minecraft("ice"));

    public static final DefaultedTag<BlockType> IMPERMEABLE = BlockTypeTags.key(ResourceKey.minecraft("impermeable"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_DIAMOND_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_diamond_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_GOLD_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_gold_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_IRON_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_iron_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_NETHERITE_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_netherite_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_STONE_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_stone_tool"));

    public static final DefaultedTag<BlockType> INCORRECT_FOR_WOODEN_TOOL = BlockTypeTags.key(ResourceKey.minecraft("incorrect_for_wooden_tool"));

    public static final DefaultedTag<BlockType> INFINIBURN_END = BlockTypeTags.key(ResourceKey.minecraft("infiniburn_end"));

    public static final DefaultedTag<BlockType> INFINIBURN_NETHER = BlockTypeTags.key(ResourceKey.minecraft("infiniburn_nether"));

    public static final DefaultedTag<BlockType> INFINIBURN_OVERWORLD = BlockTypeTags.key(ResourceKey.minecraft("infiniburn_overworld"));

    public static final DefaultedTag<BlockType> INSIDE_STEP_SOUND_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("inside_step_sound_blocks"));

    public static final DefaultedTag<BlockType> INVALID_SPAWN_INSIDE = BlockTypeTags.key(ResourceKey.minecraft("invalid_spawn_inside"));

    public static final DefaultedTag<BlockType> IRON_ORES = BlockTypeTags.key(ResourceKey.minecraft("iron_ores"));

    public static final DefaultedTag<BlockType> JUNGLE_LOGS = BlockTypeTags.key(ResourceKey.minecraft("jungle_logs"));

    public static final DefaultedTag<BlockType> LAPIS_ORES = BlockTypeTags.key(ResourceKey.minecraft("lapis_ores"));

    public static final DefaultedTag<BlockType> LAVA_POOL_STONE_CANNOT_REPLACE = BlockTypeTags.key(ResourceKey.minecraft("lava_pool_stone_cannot_replace"));

    public static final DefaultedTag<BlockType> LEAVES = BlockTypeTags.key(ResourceKey.minecraft("leaves"));

    public static final DefaultedTag<BlockType> LOGS = BlockTypeTags.key(ResourceKey.minecraft("logs"));

    public static final DefaultedTag<BlockType> LOGS_THAT_BURN = BlockTypeTags.key(ResourceKey.minecraft("logs_that_burn"));

    public static final DefaultedTag<BlockType> LUSH_GROUND_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("lush_ground_replaceable"));

    public static final DefaultedTag<BlockType> MAINTAINS_FARMLAND = BlockTypeTags.key(ResourceKey.minecraft("maintains_farmland"));

    public static final DefaultedTag<BlockType> MANGROVE_LOGS = BlockTypeTags.key(ResourceKey.minecraft("mangrove_logs"));

    public static final DefaultedTag<BlockType> MANGROVE_LOGS_CAN_GROW_THROUGH = BlockTypeTags.key(ResourceKey.minecraft("mangrove_logs_can_grow_through"));

    public static final DefaultedTag<BlockType> MANGROVE_ROOTS_CAN_GROW_THROUGH = BlockTypeTags.key(ResourceKey.minecraft("mangrove_roots_can_grow_through"));

    public static final DefaultedTag<BlockType> MINEABLE_AXE = BlockTypeTags.key(ResourceKey.minecraft("mineable/axe"));

    public static final DefaultedTag<BlockType> MINEABLE_HOE = BlockTypeTags.key(ResourceKey.minecraft("mineable/hoe"));

    public static final DefaultedTag<BlockType> MINEABLE_PICKAXE = BlockTypeTags.key(ResourceKey.minecraft("mineable/pickaxe"));

    public static final DefaultedTag<BlockType> MINEABLE_SHOVEL = BlockTypeTags.key(ResourceKey.minecraft("mineable/shovel"));

    public static final DefaultedTag<BlockType> MOB_INTERACTABLE_DOORS = BlockTypeTags.key(ResourceKey.minecraft("mob_interactable_doors"));

    public static final DefaultedTag<BlockType> MOOSHROOMS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("mooshrooms_spawnable_on"));

    public static final DefaultedTag<BlockType> MOSS_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("moss_replaceable"));

    public static final DefaultedTag<BlockType> MUSHROOM_GROW_BLOCK = BlockTypeTags.key(ResourceKey.minecraft("mushroom_grow_block"));

    public static final DefaultedTag<BlockType> NEEDS_DIAMOND_TOOL = BlockTypeTags.key(ResourceKey.minecraft("needs_diamond_tool"));

    public static final DefaultedTag<BlockType> NEEDS_IRON_TOOL = BlockTypeTags.key(ResourceKey.minecraft("needs_iron_tool"));

    public static final DefaultedTag<BlockType> NEEDS_STONE_TOOL = BlockTypeTags.key(ResourceKey.minecraft("needs_stone_tool"));

    public static final DefaultedTag<BlockType> NETHER_CARVER_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("nether_carver_replaceables"));

    public static final DefaultedTag<BlockType> NYLIUM = BlockTypeTags.key(ResourceKey.minecraft("nylium"));

    public static final DefaultedTag<BlockType> OAK_LOGS = BlockTypeTags.key(ResourceKey.minecraft("oak_logs"));

    public static final DefaultedTag<BlockType> OCCLUDES_VIBRATION_SIGNALS = BlockTypeTags.key(ResourceKey.minecraft("occludes_vibration_signals"));

    public static final DefaultedTag<BlockType> OVERWORLD_CARVER_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("overworld_carver_replaceables"));

    public static final DefaultedTag<BlockType> OVERWORLD_NATURAL_LOGS = BlockTypeTags.key(ResourceKey.minecraft("overworld_natural_logs"));

    public static final DefaultedTag<BlockType> PALE_OAK_LOGS = BlockTypeTags.key(ResourceKey.minecraft("pale_oak_logs"));

    public static final DefaultedTag<BlockType> PARROTS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("parrots_spawnable_on"));

    public static final DefaultedTag<BlockType> PIGLIN_REPELLENTS = BlockTypeTags.key(ResourceKey.minecraft("piglin_repellents"));

    public static final DefaultedTag<BlockType> PLANKS = BlockTypeTags.key(ResourceKey.minecraft("planks"));

    public static final DefaultedTag<BlockType> POLAR_BEARS_SPAWNABLE_ON_ALTERNATE = BlockTypeTags.key(ResourceKey.minecraft("polar_bears_spawnable_on_alternate"));

    public static final DefaultedTag<BlockType> PORTALS = BlockTypeTags.key(ResourceKey.minecraft("portals"));

    public static final DefaultedTag<BlockType> PRESSURE_PLATES = BlockTypeTags.key(ResourceKey.minecraft("pressure_plates"));

    public static final DefaultedTag<BlockType> PREVENT_MOB_SPAWNING_INSIDE = BlockTypeTags.key(ResourceKey.minecraft("prevent_mob_spawning_inside"));

    public static final DefaultedTag<BlockType> RABBITS_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("rabbits_spawnable_on"));

    public static final DefaultedTag<BlockType> RAILS = BlockTypeTags.key(ResourceKey.minecraft("rails"));

    public static final DefaultedTag<BlockType> REDSTONE_ORES = BlockTypeTags.key(ResourceKey.minecraft("redstone_ores"));

    public static final DefaultedTag<BlockType> REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("replaceable"));

    public static final DefaultedTag<BlockType> REPLACEABLE_BY_TREES = BlockTypeTags.key(ResourceKey.minecraft("replaceable_by_trees"));

    public static final DefaultedTag<BlockType> SAND = BlockTypeTags.key(ResourceKey.minecraft("sand"));

    public static final DefaultedTag<BlockType> SAPLINGS = BlockTypeTags.key(ResourceKey.minecraft("saplings"));

    public static final DefaultedTag<BlockType> SCULK_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("sculk_replaceable"));

    public static final DefaultedTag<BlockType> SCULK_REPLACEABLE_WORLD_GEN = BlockTypeTags.key(ResourceKey.minecraft("sculk_replaceable_world_gen"));

    public static final DefaultedTag<BlockType> SHULKER_BOXES = BlockTypeTags.key(ResourceKey.minecraft("shulker_boxes"));

    public static final DefaultedTag<BlockType> SIGNS = BlockTypeTags.key(ResourceKey.minecraft("signs"));

    public static final DefaultedTag<BlockType> SLABS = BlockTypeTags.key(ResourceKey.minecraft("slabs"));

    public static final DefaultedTag<BlockType> SMALL_DRIPLEAF_PLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("small_dripleaf_placeable"));

    public static final DefaultedTag<BlockType> SMALL_FLOWERS = BlockTypeTags.key(ResourceKey.minecraft("small_flowers"));

    public static final DefaultedTag<BlockType> SMELTS_TO_GLASS = BlockTypeTags.key(ResourceKey.minecraft("smelts_to_glass"));

    public static final DefaultedTag<BlockType> SNAPS_GOAT_HORN = BlockTypeTags.key(ResourceKey.minecraft("snaps_goat_horn"));

    public static final DefaultedTag<BlockType> SNIFFER_DIGGABLE_BLOCK = BlockTypeTags.key(ResourceKey.minecraft("sniffer_diggable_block"));

    public static final DefaultedTag<BlockType> SNIFFER_EGG_HATCH_BOOST = BlockTypeTags.key(ResourceKey.minecraft("sniffer_egg_hatch_boost"));

    public static final DefaultedTag<BlockType> SNOW = BlockTypeTags.key(ResourceKey.minecraft("snow"));

    public static final DefaultedTag<BlockType> SNOW_LAYER_CAN_SURVIVE_ON = BlockTypeTags.key(ResourceKey.minecraft("snow_layer_can_survive_on"));

    public static final DefaultedTag<BlockType> SNOW_LAYER_CANNOT_SURVIVE_ON = BlockTypeTags.key(ResourceKey.minecraft("snow_layer_cannot_survive_on"));

    public static final DefaultedTag<BlockType> SOUL_FIRE_BASE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("soul_fire_base_blocks"));

    public static final DefaultedTag<BlockType> SOUL_SPEED_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("soul_speed_blocks"));

    public static final DefaultedTag<BlockType> SPRUCE_LOGS = BlockTypeTags.key(ResourceKey.minecraft("spruce_logs"));

    public static final DefaultedTag<BlockType> STAIRS = BlockTypeTags.key(ResourceKey.minecraft("stairs"));

    public static final DefaultedTag<BlockType> STANDING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("standing_signs"));

    public static final DefaultedTag<BlockType> STONE_BRICKS = BlockTypeTags.key(ResourceKey.minecraft("stone_bricks"));

    public static final DefaultedTag<BlockType> STONE_BUTTONS = BlockTypeTags.key(ResourceKey.minecraft("stone_buttons"));

    public static final DefaultedTag<BlockType> STONE_ORE_REPLACEABLES = BlockTypeTags.key(ResourceKey.minecraft("stone_ore_replaceables"));

    public static final DefaultedTag<BlockType> STONE_PRESSURE_PLATES = BlockTypeTags.key(ResourceKey.minecraft("stone_pressure_plates"));

    public static final DefaultedTag<BlockType> STRIDER_WARM_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("strider_warm_blocks"));

    public static final DefaultedTag<BlockType> SWORD_EFFICIENT = BlockTypeTags.key(ResourceKey.minecraft("sword_efficient"));

    public static final DefaultedTag<BlockType> TERRACOTTA = BlockTypeTags.key(ResourceKey.minecraft("terracotta"));

    public static final DefaultedTag<BlockType> TRAIL_RUINS_REPLACEABLE = BlockTypeTags.key(ResourceKey.minecraft("trail_ruins_replaceable"));

    public static final DefaultedTag<BlockType> TRAPDOORS = BlockTypeTags.key(ResourceKey.minecraft("trapdoors"));

    public static final DefaultedTag<BlockType> UNDERWATER_BONEMEALS = BlockTypeTags.key(ResourceKey.minecraft("underwater_bonemeals"));

    public static final DefaultedTag<BlockType> UNSTABLE_BOTTOM_CENTER = BlockTypeTags.key(ResourceKey.minecraft("unstable_bottom_center"));

    public static final DefaultedTag<BlockType> VALID_SPAWN = BlockTypeTags.key(ResourceKey.minecraft("valid_spawn"));

    public static final DefaultedTag<BlockType> VIBRATION_RESONATORS = BlockTypeTags.key(ResourceKey.minecraft("vibration_resonators"));

    public static final DefaultedTag<BlockType> WALL_CORALS = BlockTypeTags.key(ResourceKey.minecraft("wall_corals"));

    public static final DefaultedTag<BlockType> WALL_HANGING_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("wall_hanging_signs"));

    public static final DefaultedTag<BlockType> WALL_POST_OVERRIDE = BlockTypeTags.key(ResourceKey.minecraft("wall_post_override"));

    public static final DefaultedTag<BlockType> WALL_SIGNS = BlockTypeTags.key(ResourceKey.minecraft("wall_signs"));

    public static final DefaultedTag<BlockType> WALLS = BlockTypeTags.key(ResourceKey.minecraft("walls"));

    public static final DefaultedTag<BlockType> WARPED_STEMS = BlockTypeTags.key(ResourceKey.minecraft("warped_stems"));

    public static final DefaultedTag<BlockType> WART_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("wart_blocks"));

    public static final DefaultedTag<BlockType> WITHER_IMMUNE = BlockTypeTags.key(ResourceKey.minecraft("wither_immune"));

    public static final DefaultedTag<BlockType> WITHER_SUMMON_BASE_BLOCKS = BlockTypeTags.key(ResourceKey.minecraft("wither_summon_base_blocks"));

    public static final DefaultedTag<BlockType> WOLVES_SPAWNABLE_ON = BlockTypeTags.key(ResourceKey.minecraft("wolves_spawnable_on"));

    public static final DefaultedTag<BlockType> WOODEN_BUTTONS = BlockTypeTags.key(ResourceKey.minecraft("wooden_buttons"));

    public static final DefaultedTag<BlockType> WOODEN_DOORS = BlockTypeTags.key(ResourceKey.minecraft("wooden_doors"));

    public static final DefaultedTag<BlockType> WOODEN_FENCES = BlockTypeTags.key(ResourceKey.minecraft("wooden_fences"));

    public static final DefaultedTag<BlockType> WOODEN_PRESSURE_PLATES = BlockTypeTags.key(ResourceKey.minecraft("wooden_pressure_plates"));

    public static final DefaultedTag<BlockType> WOODEN_SLABS = BlockTypeTags.key(ResourceKey.minecraft("wooden_slabs"));

    public static final DefaultedTag<BlockType> WOODEN_STAIRS = BlockTypeTags.key(ResourceKey.minecraft("wooden_stairs"));

    public static final DefaultedTag<BlockType> WOODEN_TRAPDOORS = BlockTypeTags.key(ResourceKey.minecraft("wooden_trapdoors"));

    public static final DefaultedTag<BlockType> WOOL = BlockTypeTags.key(ResourceKey.minecraft("wool"));

    public static final DefaultedTag<BlockType> WOOL_CARPETS = BlockTypeTags.key(ResourceKey.minecraft("wool_carpets"));

    private BlockTypeTags() {
    }

    private static DefaultedTag<BlockType> key(final ResourceKey key) {
        return DefaultedTag.of(RegistryTypes.BLOCK_TYPE, key);
    }
}
