/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.tag;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.generation.structure.Structure;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class StructureTags {

    public static final DefaultedTag<Structure> CATS_SPAWN_AS_BLACK = StructureTags.key(ResourceKey.minecraft("cats_spawn_as_black"));

    public static final DefaultedTag<Structure> CATS_SPAWN_IN = StructureTags.key(ResourceKey.minecraft("cats_spawn_in"));

    public static final DefaultedTag<Structure> DOLPHIN_LOCATED = StructureTags.key(ResourceKey.minecraft("dolphin_located"));

    public static final DefaultedTag<Structure> EYE_OF_ENDER_LOCATED = StructureTags.key(ResourceKey.minecraft("eye_of_ender_located"));

    public static final DefaultedTag<Structure> MINESHAFT = StructureTags.key(ResourceKey.minecraft("mineshaft"));

    public static final DefaultedTag<Structure> OCEAN_RUIN = StructureTags.key(ResourceKey.minecraft("ocean_ruin"));

    public static final DefaultedTag<Structure> ON_OCEAN_EXPLORER_MAPS = StructureTags.key(ResourceKey.minecraft("on_ocean_explorer_maps"));

    public static final DefaultedTag<Structure> ON_TREASURE_MAPS = StructureTags.key(ResourceKey.minecraft("on_treasure_maps"));

    public static final DefaultedTag<Structure> ON_TRIAL_CHAMBERS_MAPS = StructureTags.key(ResourceKey.minecraft("on_trial_chambers_maps"));

    public static final DefaultedTag<Structure> ON_WOODLAND_EXPLORER_MAPS = StructureTags.key(ResourceKey.minecraft("on_woodland_explorer_maps"));

    public static final DefaultedTag<Structure> RUINED_PORTAL = StructureTags.key(ResourceKey.minecraft("ruined_portal"));

    public static final DefaultedTag<Structure> SHIPWRECK = StructureTags.key(ResourceKey.minecraft("shipwreck"));

    public static final DefaultedTag<Structure> VILLAGE = StructureTags.key(ResourceKey.minecraft("village"));

    private StructureTags() {
    }

    private static DefaultedTag<Structure> key(final ResourceKey key) {
        return DefaultedTag.of(RegistryTypes.STRUCTURE, key);
    }
}
