/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.structure.jigsaw;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class JigsawPools {

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_CITY_ENTRANCE = JigsawPools.key(ResourceKey.minecraft("ancient_city/city/entrance"));

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_CITY_CENTER = JigsawPools.key(ResourceKey.minecraft("ancient_city/city_center"));

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_CITY_CENTER_WALLS = JigsawPools.key(ResourceKey.minecraft("ancient_city/city_center/walls"));

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_SCULK = JigsawPools.key(ResourceKey.minecraft("ancient_city/sculk"));

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_STRUCTURES = JigsawPools.key(ResourceKey.minecraft("ancient_city/structures"));

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_WALLS = JigsawPools.key(ResourceKey.minecraft("ancient_city/walls"));

    public static final DefaultedRegistryReference<JigsawPool> ANCIENT_CITY_WALLS_NO_CORNERS = JigsawPools.key(ResourceKey.minecraft("ancient_city/walls/no_corners"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BLOCKS_GOLD = JigsawPools.key(ResourceKey.minecraft("bastion/blocks/gold"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_BRIDGE_PIECES = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/bridge_pieces"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_CONNECTORS = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/connectors"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_LEGS = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/legs"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_RAMPART_PLATES = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/rampart_plates"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_RAMPARTS = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/ramparts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_STARTING_PIECES = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/starting_pieces"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_BRIDGE_WALLS = JigsawPools.key(ResourceKey.minecraft("bastion/bridge/walls"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_CONNECTORS = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/connectors"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_LARGE_STABLES_INNER = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/large_stables/inner"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_LARGE_STABLES_OUTER = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/large_stables/outer"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_MIRRORED_STARTING_PIECES = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/mirrored_starting_pieces"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_POSTS = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/posts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_RAMPART_PLATES = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/rampart_plates"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_RAMPARTS = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/ramparts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_SMALL_STABLES_INNER = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/small_stables/inner"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_SMALL_STABLES_OUTER = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/small_stables/outer"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_STAIRS = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/stairs"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_STARTING_PIECES = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/starting_pieces"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_WALL_BASES = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/wall_bases"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_HOGLIN_STABLE_WALLS = JigsawPools.key(ResourceKey.minecraft("bastion/hoglin_stable/walls"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_MOBS_HOGLIN = JigsawPools.key(ResourceKey.minecraft("bastion/mobs/hoglin"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_MOBS_PIGLIN = JigsawPools.key(ResourceKey.minecraft("bastion/mobs/piglin"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_MOBS_PIGLIN_MELEE = JigsawPools.key(ResourceKey.minecraft("bastion/mobs/piglin_melee"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_STARTS = JigsawPools.key(ResourceKey.minecraft("bastion/starts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_BASES = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/bases"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_BASES_CENTERS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/bases/centers"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_BRAINS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/brains"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_CONNECTORS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/connectors"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_CORNERS_BOTTOM = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/corners/bottom"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_CORNERS_EDGES = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/corners/edges"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_CORNERS_MIDDLE = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/corners/middle"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_CORNERS_TOP = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/corners/top"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_ENTRANCES = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/entrances"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_EXTENSIONS_HOUSES = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/extensions/houses"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_EXTENSIONS_LARGE_POOL = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/extensions/large_pool"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_EXTENSIONS_SMALL_POOL = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/extensions/small_pool"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_RAMPARTS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/ramparts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_ROOFS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/roofs"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_STAIRS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/stairs"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_WALLS = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/walls"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_WALLS_BOTTOM = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/walls/bottom"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_WALLS_MID = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/walls/mid"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_WALLS_OUTER = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/walls/outer"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_TREASURE_WALLS_TOP = JigsawPools.key(ResourceKey.minecraft("bastion/treasure/walls/top"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_CENTER_PIECES = JigsawPools.key(ResourceKey.minecraft("bastion/units/center_pieces"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_EDGE_WALL_UNITS = JigsawPools.key(ResourceKey.minecraft("bastion/units/edge_wall_units"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_EDGES = JigsawPools.key(ResourceKey.minecraft("bastion/units/edges"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_FILLERS_STAGE_0 = JigsawPools.key(ResourceKey.minecraft("bastion/units/fillers/stage_0"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_LARGE_RAMPARTS = JigsawPools.key(ResourceKey.minecraft("bastion/units/large_ramparts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_PATHWAYS = JigsawPools.key(ResourceKey.minecraft("bastion/units/pathways"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_RAMPART_PLATES = JigsawPools.key(ResourceKey.minecraft("bastion/units/rampart_plates"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_RAMPARTS = JigsawPools.key(ResourceKey.minecraft("bastion/units/ramparts"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_STAGES_ROT_STAGE_1 = JigsawPools.key(ResourceKey.minecraft("bastion/units/stages/rot/stage_1"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_STAGES_STAGE_0 = JigsawPools.key(ResourceKey.minecraft("bastion/units/stages/stage_0"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_STAGES_STAGE_1 = JigsawPools.key(ResourceKey.minecraft("bastion/units/stages/stage_1"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_STAGES_STAGE_2 = JigsawPools.key(ResourceKey.minecraft("bastion/units/stages/stage_2"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_STAGES_STAGE_3 = JigsawPools.key(ResourceKey.minecraft("bastion/units/stages/stage_3"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_WALL_UNITS = JigsawPools.key(ResourceKey.minecraft("bastion/units/wall_units"));

    public static final DefaultedRegistryReference<JigsawPool> BASTION_UNITS_WALLS_WALL_BASES = JigsawPools.key(ResourceKey.minecraft("bastion/units/walls/wall_bases"));

    public static final DefaultedRegistryReference<JigsawPool> EMPTY = JigsawPools.key(ResourceKey.minecraft("empty"));

    public static final DefaultedRegistryReference<JigsawPool> PILLAGER_OUTPOST_BASE_PLATES = JigsawPools.key(ResourceKey.minecraft("pillager_outpost/base_plates"));

    public static final DefaultedRegistryReference<JigsawPool> PILLAGER_OUTPOST_FEATURE_PLATES = JigsawPools.key(ResourceKey.minecraft("pillager_outpost/feature_plates"));

    public static final DefaultedRegistryReference<JigsawPool> PILLAGER_OUTPOST_FEATURES = JigsawPools.key(ResourceKey.minecraft("pillager_outpost/features"));

    public static final DefaultedRegistryReference<JigsawPool> PILLAGER_OUTPOST_TOWERS = JigsawPools.key(ResourceKey.minecraft("pillager_outpost/towers"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_BUILDINGS = JigsawPools.key(ResourceKey.minecraft("trail_ruins/buildings"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_BUILDINGS_GROUPED = JigsawPools.key(ResourceKey.minecraft("trail_ruins/buildings/grouped"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_DECOR = JigsawPools.key(ResourceKey.minecraft("trail_ruins/decor"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_ROADS = JigsawPools.key(ResourceKey.minecraft("trail_ruins/roads"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_TOWER = JigsawPools.key(ResourceKey.minecraft("trail_ruins/tower"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_TOWER_ADDITIONS = JigsawPools.key(ResourceKey.minecraft("trail_ruins/tower/additions"));

    public static final DefaultedRegistryReference<JigsawPool> TRAIL_RUINS_TOWER_TOWER_TOP = JigsawPools.key(ResourceKey.minecraft("trail_ruins/tower/tower_top"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_COMMON_ANIMALS = JigsawPools.key(ResourceKey.minecraft("village/common/animals"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_COMMON_BUTCHER_ANIMALS = JigsawPools.key(ResourceKey.minecraft("village/common/butcher_animals"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_COMMON_CATS = JigsawPools.key(ResourceKey.minecraft("village/common/cats"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_COMMON_IRON_GOLEM = JigsawPools.key(ResourceKey.minecraft("village/common/iron_golem"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_COMMON_SHEEP = JigsawPools.key(ResourceKey.minecraft("village/common/sheep"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_COMMON_WELL_BOTTOMS = JigsawPools.key(ResourceKey.minecraft("village/common/well_bottoms"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_CAMEL = JigsawPools.key(ResourceKey.minecraft("village/desert/camel"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_DECOR = JigsawPools.key(ResourceKey.minecraft("village/desert/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/desert/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_STREETS = JigsawPools.key(ResourceKey.minecraft("village/desert/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/desert/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_TOWN_CENTERS = JigsawPools.key(ResourceKey.minecraft("village/desert/town_centers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/desert/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_ZOMBIE_DECOR = JigsawPools.key(ResourceKey.minecraft("village/desert/zombie/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_ZOMBIE_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/desert/zombie/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_ZOMBIE_STREETS = JigsawPools.key(ResourceKey.minecraft("village/desert/zombie/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_ZOMBIE_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/desert/zombie/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_DESERT_ZOMBIE_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/desert/zombie/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_DECOR = JigsawPools.key(ResourceKey.minecraft("village/plains/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/plains/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_STREETS = JigsawPools.key(ResourceKey.minecraft("village/plains/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/plains/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_TOWN_CENTERS = JigsawPools.key(ResourceKey.minecraft("village/plains/town_centers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_TREES = JigsawPools.key(ResourceKey.minecraft("village/plains/trees"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/plains/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_ZOMBIE_DECOR = JigsawPools.key(ResourceKey.minecraft("village/plains/zombie/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_ZOMBIE_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/plains/zombie/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_ZOMBIE_STREETS = JigsawPools.key(ResourceKey.minecraft("village/plains/zombie/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_PLAINS_ZOMBIE_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/plains/zombie/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_DECOR = JigsawPools.key(ResourceKey.minecraft("village/savanna/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/savanna/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_STREETS = JigsawPools.key(ResourceKey.minecraft("village/savanna/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/savanna/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_TOWN_CENTERS = JigsawPools.key(ResourceKey.minecraft("village/savanna/town_centers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_TREES = JigsawPools.key(ResourceKey.minecraft("village/savanna/trees"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/savanna/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_ZOMBIE_DECOR = JigsawPools.key(ResourceKey.minecraft("village/savanna/zombie/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_ZOMBIE_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/savanna/zombie/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_ZOMBIE_STREETS = JigsawPools.key(ResourceKey.minecraft("village/savanna/zombie/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_ZOMBIE_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/savanna/zombie/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SAVANNA_ZOMBIE_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/savanna/zombie/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_DECOR = JigsawPools.key(ResourceKey.minecraft("village/snowy/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/snowy/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_STREETS = JigsawPools.key(ResourceKey.minecraft("village/snowy/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/snowy/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_TOWN_CENTERS = JigsawPools.key(ResourceKey.minecraft("village/snowy/town_centers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_TREES = JigsawPools.key(ResourceKey.minecraft("village/snowy/trees"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/snowy/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_ZOMBIE_DECOR = JigsawPools.key(ResourceKey.minecraft("village/snowy/zombie/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_ZOMBIE_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/snowy/zombie/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_ZOMBIE_STREETS = JigsawPools.key(ResourceKey.minecraft("village/snowy/zombie/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_SNOWY_ZOMBIE_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/snowy/zombie/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_DECOR = JigsawPools.key(ResourceKey.minecraft("village/taiga/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/taiga/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_STREETS = JigsawPools.key(ResourceKey.minecraft("village/taiga/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_TERMINATORS = JigsawPools.key(ResourceKey.minecraft("village/taiga/terminators"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_TOWN_CENTERS = JigsawPools.key(ResourceKey.minecraft("village/taiga/town_centers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/taiga/villagers"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_ZOMBIE_DECOR = JigsawPools.key(ResourceKey.minecraft("village/taiga/zombie/decor"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_ZOMBIE_HOUSES = JigsawPools.key(ResourceKey.minecraft("village/taiga/zombie/houses"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_ZOMBIE_STREETS = JigsawPools.key(ResourceKey.minecraft("village/taiga/zombie/streets"));

    public static final DefaultedRegistryReference<JigsawPool> VILLAGE_TAIGA_ZOMBIE_VILLAGERS = JigsawPools.key(ResourceKey.minecraft("village/taiga/zombie/villagers"));

    private JigsawPools() {
    }

    public static Registry<JigsawPool> registry() {
        return Sponge.server().registry(RegistryTypes.JIGSAW_POOL);
    }

    private static DefaultedRegistryReference<JigsawPool> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.JIGSAW_POOL, location).asDefaultedReference(Sponge::server);
    }
}
