/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.structure.jigsaw;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.GAME)
public final class ProcessorTypes {

    // @formatter:off
    public static final DefaultedRegistryReference<ProcessorType> BLACKSTONE_REPLACE = ProcessorTypes.key(ResourceKey.minecraft("blackstone_replace"));

    public static final DefaultedRegistryReference<ProcessorType> BLOCK_AGE = ProcessorTypes.key(ResourceKey.minecraft("block_age"));

    public static final DefaultedRegistryReference<ProcessorType> BLOCK_IGNORE = ProcessorTypes.key(ResourceKey.minecraft("block_ignore"));

    public static final DefaultedRegistryReference<ProcessorType> BLOCK_ROT = ProcessorTypes.key(ResourceKey.minecraft("block_rot"));

    public static final DefaultedRegistryReference<ProcessorType> CAPPED = ProcessorTypes.key(ResourceKey.minecraft("capped"));

    public static final DefaultedRegistryReference<ProcessorType> GRAVITY = ProcessorTypes.key(ResourceKey.minecraft("gravity"));

    public static final DefaultedRegistryReference<ProcessorType> JIGSAW_REPLACEMENT = ProcessorTypes.key(ResourceKey.minecraft("jigsaw_replacement"));

    public static final DefaultedRegistryReference<ProcessorType> LAVA_SUBMERGED_BLOCK = ProcessorTypes.key(ResourceKey.minecraft("lava_submerged_block"));

    public static final DefaultedRegistryReference<ProcessorType> NOP = ProcessorTypes.key(ResourceKey.minecraft("nop"));

    public static final DefaultedRegistryReference<ProcessorType> PROTECTED_BLOCKS = ProcessorTypes.key(ResourceKey.minecraft("protected_blocks"));

    public static final DefaultedRegistryReference<ProcessorType> RULE = ProcessorTypes.key(ResourceKey.minecraft("rule"));

    // @formatter:on
    private ProcessorTypes() {
    }

    public static Registry<ProcessorType> registry() {
        return Sponge.game().registry(RegistryTypes.PROCESSOR_TYPE);
    }

    private static DefaultedRegistryReference<ProcessorType> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.PROCESSOR_TYPE, location).asDefaultedReference(Sponge::game);
    }
}
