/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.world.generation.structure;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.Sponge;
import org.spongepowered.api.registry.DefaultedRegistryReference;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.ENGINE)
public final class StructureSets {

    public static final DefaultedRegistryReference<StructureSet> ANCIENT_CITIES = StructureSets.key(ResourceKey.minecraft("ancient_cities"));

    public static final DefaultedRegistryReference<StructureSet> BURIED_TREASURES = StructureSets.key(ResourceKey.minecraft("buried_treasures"));

    public static final DefaultedRegistryReference<StructureSet> DESERT_PYRAMIDS = StructureSets.key(ResourceKey.minecraft("desert_pyramids"));

    public static final DefaultedRegistryReference<StructureSet> END_CITIES = StructureSets.key(ResourceKey.minecraft("end_cities"));

    public static final DefaultedRegistryReference<StructureSet> IGLOOS = StructureSets.key(ResourceKey.minecraft("igloos"));

    public static final DefaultedRegistryReference<StructureSet> JUNGLE_TEMPLES = StructureSets.key(ResourceKey.minecraft("jungle_temples"));

    public static final DefaultedRegistryReference<StructureSet> MINESHAFTS = StructureSets.key(ResourceKey.minecraft("mineshafts"));

    public static final DefaultedRegistryReference<StructureSet> NETHER_COMPLEXES = StructureSets.key(ResourceKey.minecraft("nether_complexes"));

    public static final DefaultedRegistryReference<StructureSet> NETHER_FOSSILS = StructureSets.key(ResourceKey.minecraft("nether_fossils"));

    public static final DefaultedRegistryReference<StructureSet> OCEAN_MONUMENTS = StructureSets.key(ResourceKey.minecraft("ocean_monuments"));

    public static final DefaultedRegistryReference<StructureSet> OCEAN_RUINS = StructureSets.key(ResourceKey.minecraft("ocean_ruins"));

    public static final DefaultedRegistryReference<StructureSet> PILLAGER_OUTPOSTS = StructureSets.key(ResourceKey.minecraft("pillager_outposts"));

    public static final DefaultedRegistryReference<StructureSet> RUINED_PORTALS = StructureSets.key(ResourceKey.minecraft("ruined_portals"));

    public static final DefaultedRegistryReference<StructureSet> SHIPWRECKS = StructureSets.key(ResourceKey.minecraft("shipwrecks"));

    public static final DefaultedRegistryReference<StructureSet> STRONGHOLDS = StructureSets.key(ResourceKey.minecraft("strongholds"));

    public static final DefaultedRegistryReference<StructureSet> SWAMP_HUTS = StructureSets.key(ResourceKey.minecraft("swamp_huts"));

    public static final DefaultedRegistryReference<StructureSet> TRAIL_RUINS = StructureSets.key(ResourceKey.minecraft("trail_ruins"));

    public static final DefaultedRegistryReference<StructureSet> VILLAGES = StructureSets.key(ResourceKey.minecraft("villages"));

    public static final DefaultedRegistryReference<StructureSet> WOODLAND_MANSIONS = StructureSets.key(ResourceKey.minecraft("woodland_mansions"));

    private StructureSets() {
    }

    public static Registry<StructureSet> registry() {
        return Sponge.server().registry(RegistryTypes.STRUCTURE_SET);
    }

    private static DefaultedRegistryReference<StructureSet> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.STRUCTURE_SET, location).asDefaultedReference(Sponge::server);
    }
}
