/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.data.type;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryReference;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.server.ServerWorld;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.WORLD)
public final class BannerPatternShapes {

    public static final RegistryReference<BannerPatternShape> BASE = BannerPatternShapes.key(ResourceKey.minecraft("base"));

    public static final RegistryReference<BannerPatternShape> BORDER = BannerPatternShapes.key(ResourceKey.minecraft("border"));

    public static final RegistryReference<BannerPatternShape> BRICKS = BannerPatternShapes.key(ResourceKey.minecraft("bricks"));

    public static final RegistryReference<BannerPatternShape> CIRCLE = BannerPatternShapes.key(ResourceKey.minecraft("circle"));

    public static final RegistryReference<BannerPatternShape> CREEPER = BannerPatternShapes.key(ResourceKey.minecraft("creeper"));

    public static final RegistryReference<BannerPatternShape> CROSS = BannerPatternShapes.key(ResourceKey.minecraft("cross"));

    public static final RegistryReference<BannerPatternShape> CURLY_BORDER = BannerPatternShapes.key(ResourceKey.minecraft("curly_border"));

    public static final RegistryReference<BannerPatternShape> DIAGONAL_LEFT = BannerPatternShapes.key(ResourceKey.minecraft("diagonal_left"));

    public static final RegistryReference<BannerPatternShape> DIAGONAL_RIGHT = BannerPatternShapes.key(ResourceKey.minecraft("diagonal_right"));

    public static final RegistryReference<BannerPatternShape> DIAGONAL_UP_LEFT = BannerPatternShapes.key(ResourceKey.minecraft("diagonal_up_left"));

    public static final RegistryReference<BannerPatternShape> DIAGONAL_UP_RIGHT = BannerPatternShapes.key(ResourceKey.minecraft("diagonal_up_right"));

    public static final RegistryReference<BannerPatternShape> FLOWER = BannerPatternShapes.key(ResourceKey.minecraft("flower"));

    public static final RegistryReference<BannerPatternShape> GLOBE = BannerPatternShapes.key(ResourceKey.minecraft("globe"));

    public static final RegistryReference<BannerPatternShape> GRADIENT = BannerPatternShapes.key(ResourceKey.minecraft("gradient"));

    public static final RegistryReference<BannerPatternShape> GRADIENT_UP = BannerPatternShapes.key(ResourceKey.minecraft("gradient_up"));

    public static final RegistryReference<BannerPatternShape> HALF_HORIZONTAL = BannerPatternShapes.key(ResourceKey.minecraft("half_horizontal"));

    public static final RegistryReference<BannerPatternShape> HALF_HORIZONTAL_BOTTOM = BannerPatternShapes.key(ResourceKey.minecraft("half_horizontal_bottom"));

    public static final RegistryReference<BannerPatternShape> HALF_VERTICAL = BannerPatternShapes.key(ResourceKey.minecraft("half_vertical"));

    public static final RegistryReference<BannerPatternShape> HALF_VERTICAL_RIGHT = BannerPatternShapes.key(ResourceKey.minecraft("half_vertical_right"));

    public static final RegistryReference<BannerPatternShape> MOJANG = BannerPatternShapes.key(ResourceKey.minecraft("mojang"));

    public static final RegistryReference<BannerPatternShape> PIGLIN = BannerPatternShapes.key(ResourceKey.minecraft("piglin"));

    public static final RegistryReference<BannerPatternShape> RHOMBUS = BannerPatternShapes.key(ResourceKey.minecraft("rhombus"));

    public static final RegistryReference<BannerPatternShape> SKULL = BannerPatternShapes.key(ResourceKey.minecraft("skull"));

    public static final RegistryReference<BannerPatternShape> SMALL_STRIPES = BannerPatternShapes.key(ResourceKey.minecraft("small_stripes"));

    public static final RegistryReference<BannerPatternShape> SQUARE_BOTTOM_LEFT = BannerPatternShapes.key(ResourceKey.minecraft("square_bottom_left"));

    public static final RegistryReference<BannerPatternShape> SQUARE_BOTTOM_RIGHT = BannerPatternShapes.key(ResourceKey.minecraft("square_bottom_right"));

    public static final RegistryReference<BannerPatternShape> SQUARE_TOP_LEFT = BannerPatternShapes.key(ResourceKey.minecraft("square_top_left"));

    public static final RegistryReference<BannerPatternShape> SQUARE_TOP_RIGHT = BannerPatternShapes.key(ResourceKey.minecraft("square_top_right"));

    public static final RegistryReference<BannerPatternShape> STRAIGHT_CROSS = BannerPatternShapes.key(ResourceKey.minecraft("straight_cross"));

    public static final RegistryReference<BannerPatternShape> STRIPE_BOTTOM = BannerPatternShapes.key(ResourceKey.minecraft("stripe_bottom"));

    public static final RegistryReference<BannerPatternShape> STRIPE_CENTER = BannerPatternShapes.key(ResourceKey.minecraft("stripe_center"));

    public static final RegistryReference<BannerPatternShape> STRIPE_DOWNLEFT = BannerPatternShapes.key(ResourceKey.minecraft("stripe_downleft"));

    public static final RegistryReference<BannerPatternShape> STRIPE_DOWNRIGHT = BannerPatternShapes.key(ResourceKey.minecraft("stripe_downright"));

    public static final RegistryReference<BannerPatternShape> STRIPE_LEFT = BannerPatternShapes.key(ResourceKey.minecraft("stripe_left"));

    public static final RegistryReference<BannerPatternShape> STRIPE_MIDDLE = BannerPatternShapes.key(ResourceKey.minecraft("stripe_middle"));

    public static final RegistryReference<BannerPatternShape> STRIPE_RIGHT = BannerPatternShapes.key(ResourceKey.minecraft("stripe_right"));

    public static final RegistryReference<BannerPatternShape> STRIPE_TOP = BannerPatternShapes.key(ResourceKey.minecraft("stripe_top"));

    public static final RegistryReference<BannerPatternShape> TRIANGLE_BOTTOM = BannerPatternShapes.key(ResourceKey.minecraft("triangle_bottom"));

    public static final RegistryReference<BannerPatternShape> TRIANGLE_TOP = BannerPatternShapes.key(ResourceKey.minecraft("triangle_top"));

    public static final RegistryReference<BannerPatternShape> TRIANGLES_BOTTOM = BannerPatternShapes.key(ResourceKey.minecraft("triangles_bottom"));

    public static final RegistryReference<BannerPatternShape> TRIANGLES_TOP = BannerPatternShapes.key(ResourceKey.minecraft("triangles_top"));

    private BannerPatternShapes() {
    }

    public static Registry<BannerPatternShape> registry(final ServerWorld world) {
        return world.registry(RegistryTypes.BANNER_PATTERN_SHAPE);
    }

    private static RegistryReference<BannerPatternShape> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.BANNER_PATTERN_SHAPE, location).asReference();
    }
}
