/*
 * This file is part of SpongeAPI, licensed under the MIT License (MIT).
 *
 * Copyright (c) SpongePowered <https://www.spongepowered.org>
 * Copyright (c) contributors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.spongepowered.api.data.type;

import org.spongepowered.api.ResourceKey;
import org.spongepowered.api.registry.Registry;
import org.spongepowered.api.registry.RegistryKey;
import org.spongepowered.api.registry.RegistryReference;
import org.spongepowered.api.registry.RegistryScope;
import org.spongepowered.api.registry.RegistryScopes;
import org.spongepowered.api.registry.RegistryTypes;
import org.spongepowered.api.world.server.ServerWorld;

/**
 * <!-- This file is automatically generated. Any manual changes will be overwritten. -->
 */
@SuppressWarnings("unused")
@RegistryScopes(scopes = RegistryScope.WORLD)
public final class WolfVariants {

    public static final RegistryReference<WolfVariant> ASHEN = WolfVariants.key(ResourceKey.minecraft("ashen"));

    public static final RegistryReference<WolfVariant> BLACK = WolfVariants.key(ResourceKey.minecraft("black"));

    public static final RegistryReference<WolfVariant> CHESTNUT = WolfVariants.key(ResourceKey.minecraft("chestnut"));

    public static final RegistryReference<WolfVariant> PALE = WolfVariants.key(ResourceKey.minecraft("pale"));

    public static final RegistryReference<WolfVariant> RUSTY = WolfVariants.key(ResourceKey.minecraft("rusty"));

    public static final RegistryReference<WolfVariant> SNOWY = WolfVariants.key(ResourceKey.minecraft("snowy"));

    public static final RegistryReference<WolfVariant> SPOTTED = WolfVariants.key(ResourceKey.minecraft("spotted"));

    public static final RegistryReference<WolfVariant> STRIPED = WolfVariants.key(ResourceKey.minecraft("striped"));

    public static final RegistryReference<WolfVariant> WOODS = WolfVariants.key(ResourceKey.minecraft("woods"));

    private WolfVariants() {
    }

    public static Registry<WolfVariant> registry(final ServerWorld world) {
        return world.registry(RegistryTypes.WOLF_VARIANT);
    }

    private static RegistryReference<WolfVariant> key(final ResourceKey location) {
        return RegistryKey.of(RegistryTypes.WOLF_VARIANT, location).asReference();
    }
}
