name: Spotless Check

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-check:
    uses: SpongePowered/.github/.github/workflows/shared-check-spotless.yaml@master
    with:
      runtime_version: 21
    secrets: inherit
